casper-network/casper-node

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/linear_chain_sync.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/block.rs
run-dev.sh

This is Mateusz's code from #223 plus a workaround for the issue where the validators switch eras while the joiner is synchronizing.
The workaround causes the joiner to detect whether other validators are in the era it will be able to join or in a later one, and panic if the latter is the case. A great part of the linear chain will be synchronized already, though - so the node's owner should be able to join after restarting the node with a more up-to-date trusted hash.

NDRS-{345-346}: A workaround for a timing issue

---

node/src/reactor/joiner.rs

https://casperlabs.atlassian.net/browse/NDRS-385
Another case of `AddressGossiper` event not being handled.
After this change, I can see 3 nodes being signaled:
```
➜  casperlabs-node git:(master) ✗ cat /tmp/node-4.log | grep "New peer connected"
Sep 16 18:17:57.697 TRACE crank{ev=24}:dispatch events{ev=25}: [casper_node::components::linear_chain_sync linear_chain_sync.rs:262] New peer connected; peer_id=d08d..eb93
Sep 16 18:17:58.474 TRACE crank{ev=270}:dispatch events{ev=271}: [casper_node::components::linear_chain_sync linear_chain_sync.rs:262] New peer connected; peer_id=eb7d..ef6b
Sep 16 18:17:58.502 TRACE crank{ev=336}:dispatch events{ev=337}: [casper_node::components::linear_chain_sync linear_chain_sync.rs:262] New peer connected; peer_id=a54f..1c83
```

NDRS-385: Fix no `NewPeer` event bug.

---

node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/highway_core/state/tests.rs

The only thing that's important is that the round exponent doesn't change within a round.
Limiting how fast it can change and how far it can diverge from the median was only meant to protect against spam attacks, but setting a minimal round exponent is a much easier and effective way to do that.

NO-TICKET: Remove round exponent validity conditions.

---

smart_contracts/contract_as/package-lock.json
smart_contracts/contract_as/package.json

We have npm packages with security issues. These are likely minor, as they only related to command-line argument parsing, but they should not remain.
This contained a potentially breaking change by upgrading the major version of the `ava` library, used to run tests. The tests run fine, but maybe @mpapierski should make sure I did not miss anything.
It somehow is a 6k+ line change because the whole Javascript world is absolutely insane.

NDRS-400: Fix npms with security issues

---

node/src/app/cli.rs
node/src/reactor.rs

Every reactor runner used to come with its own metrics registry, which mean that metrics were not reported properly when going from one reactor to the next.
This PR changes the interface of the runner, making it possible to share a preconstructed registry for metrics that is shared across initializer, joiner and validator.
This requires properly deregistering metrics when dropping a runner/shared component, which is done only for the runner. Should someone attempt to drop and recreate a contract runtime at some point, this will need to be added to the contract runtime metrics as well. For now this is not an issue though and it will be apparent quickly during development, as it will cause a panic when creating the follow-up reactor.

NDRS-399: Fix metrics

---

client/src/deploy/creation_common.rs
client/src/deploy/put.rs
client/src/deploy/transfer.rs

This fixes an issue in the client where if the `--show-arg-examples` flag is passed, it should be evaluated before any other args so the help output can be displayed and the app can exit.
Without this, we were trying to parse other args, some of which are required.  It should be valid to only require these if `--show-arg-examples` is not present.

NO-TICKET: fix bug in client

---

client/src/deploy/creation_common.rs
client/src/query_state.rs
types/src/account.rs
types/src/key.rs
types/src/uref.rs

This PR adds support for passing `AccountHash`es as args in client subcommands such as `put-deploy`.  While we want to continue support for users dealing with the `AccountHash` type, the client should treat this as a non-complex arg type to make it simpler for users to pass.
@henrytill & @mpapierski - please note that this PR changes the prefix for a formatted `AccountHash` from `account-account_hash` to `account-hash`.  This can be reverted if we really require the longer prefix.

NO-TICKET: support account hash as client arg

---

node/src/components/consensus/era_supervisor.rs
node/src/reactor/validator/tests.rs

This prevents accidental equivocations when restarting a node:
If the current process is younger than the era, we know that before the restart, we certainly haven't cast any votes yet, so it is safe to vote.
@arcolife will make a separate PR to update the `run-dev.sh` script and add a few seconds to the genesis timestamp.
https://casperlabs.atlassian.net/browse/NDRS-414

NDRS-414: Only vote in eras younger than the node process.

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state.rs

Logs whenever we detect (or receive evidence of) an equivocation. Since this only lists the validator _index_, I also added a log entry at the beginning of each era that lists that era's validator ID - validator index mapping.

NO-TICKET: Add some INFO log messages for equivocations.

---

run-dev.sh

```
╰─ OFFSET=50 ./run-dev.sh
GENESIS_TIMESTAMP=1600862573000
Wed Sep 23 17:32:53 IST 2020
...
```
@afck Default's to 30. Ref https://github.com/CasperLabs/casper-node/pull/260

NO-TICK: offset timestamp in run-dev.sh by 30 seconds

---

node/src/components/consensus/era_supervisor.rs

Log validators, stakes, timestamps and height when initializing a new era, and whether we are actively voting in it.

NO-TICKET: Log era initialization.

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/validators.rs

This looks like:
```
Sep 24 11:36:18.296 INFO  [casper_node::components::consensus::highway_core::highway highway.rs:127] creating Highway instance 5a0bfdc4d05ebaf245ee3e823200c8fe08509c00ef465c335f410f3aa8b46f44; validators=Validators: index, ID, weight
0, PublicKey::Ed25519(449c5f751e465adabc9885fe8f33b522ab2c069997148e4b65fddde9c4440d31), 300000000000000
1, PublicKey::Ed25519(8f5a3ee4c1221686fcdbe6c0b6168acb24025c5485f59f7c4039ffc444fb7509), 400000000000000
2, PublicKey::Ed25519(b3feeec1d91c7c2f070052315258eeaaf7c24029a80a1aea285814e9f9a20d36), 200000000000000
3, PublicKey::Ed25519(f60bce2bb1059c41910eac1e7ee6c3ef4c8fcc63a901eb9603c1524cadfb0c18), 500000000000000
4, PublicKey::Secp256k1(0248509e67db3127f82d5224c5c18eac00f96d1edeadbadc8eb2c8606227b56873), 100000000000001
```
Not ideal, …

NO-TICKET: impl Display for Validators

---

client/src/deploy/creation_common.rs
node/src/components/deploy_acceptor.rs

As per Frasers comments, I made closed the previous PR and cut a new one. This PR accounts for the changes made in the client to make chain name a mandatory argument along with having no default value.

NDRS-396: make chain name mandatory

---

node/src/components/block_executor.rs
node/src/components/deploy_acceptor.rs
node/src/components/linear_chain_sync.rs
node/src/reactor/joiner.rs

https://casperlabs.atlassian.net/browse/NDRS-429
This PR fixes problems with the synchronization process. There were a couple of them:
- ignored incoming `GetResponse` for `Deploy`
- once added it was routed directly to `Fetcher` instead of `DeployAcceptor` (it resulted in deploys not being persisted in storage while their dependency was considered resolved)
- TTL check on deploy dependencies.
I will port those commits to `charlie-*` branch later.
Tested on blocks with and without deploys in both `SyncingTrustedHash` and `SyncingDescendnts` phases.

NDRS-429: Fix joining process.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/state.rs

Adds some logging to `should_send_confirmation` to address [this comment](https://github.com/CasperLabs/casper-node/pull/283#discussion_r495886951).

NO-TICKET: Add some log messages when not sending a confirmation.

---

node/src/components/consensus.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/tests/consensus_des_testing.rs
node/src/types.rs
node/src/types/block.rs
types/src/auction/constants.rs

This removes `SystemTransactions` and replaces them with an `EraEnd` struct that contains a list of validators to be slashed, and a map of rewards. This will only be contained in the last block of each era (switch block).
The `compute_rewards_test` was updated: Rewards are always applied to all ancestors of the payout block, which in production will be the switch block.
To make the test easier to read, the rewards for individual ancestors are also verified.
Quora in reward calculation apply only to level-1 summits, and don't include the faulty validators. Such a summit finalizes the block if and only if it has > 50% of the weight, regardless of the already known faulty validators. This was incorrect in `compute_rewards_for`.
https://casperlabs.atlassian.net/browse/NDRS-430

NDRS-430: Put slashing and reward information in the switch block only.

---

node/src/components/linear_chain.rs
node/src/components/storage/lmdb_store.rs

This is a quick fix to allow signatures to be appended to blocks.
The plan was to handle signatures as block-related metadata, keeping the immutable parts of the block separate from the mutable parts, hence avoiding deserializing and re-serializing the whole block every time a new signature is appended.
With the upcoming CEP-0003 work, it's probably worth dwelling a pause on spending effort to do that work on the existing storage and block types, in case the effort is wasted.

NDRS-425: allow stored blocks to be mutated to append signatures

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
node/src/reactor.rs
node/src/reactor/validator.rs
node/src/reactor/validator/memory_metrics.rs
run-dev.sh

Initiates a collection of memory usage metrics roughly every 30 seconds, which are also logged.
In passing, fixes a bug where twice as many events as should be were counted.

Add collected memory usage to metrics

---

node/src/components/chainspec_loader/chainspec.rs
node/src/components/deploy_acceptor.rs
node/src/components/deploy_acceptor/event.rs
node/src/components/deploy_buffer.rs

Instead of caching the whole chainspec, which also contains raw bytes of Wasm system contracts, cache only the data that is necessary for deploy validation.

NO-TICK: Cache only the minimal set of data.

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/state.rs

This backports the changes from #283, #297, #291 as suggested by @afck.
Tests run fine, are we sure this has no unforseen impact?

[charlie] logging enhancements & timestamp workaround

---

.gitignore
node/src/components/fetcher/tests.rs
node/src/components/gossiper/tests.rs
node/src/components/storage.rs
node/src/components/storage/config.rs
node/src/reactor/initializer.rs
node/src/utils.rs
resources/charlie/config-example.toml
resources/local/config.toml

Updated the storage configuration by wrapping the `WithDir` struct around it to preserve the directory-context of the `config.toml` file.

NDRS-417: Fix relative storage path bug for node storage

---

grpc/tests/src/test/system_contracts/auction/bids.rs
grpc/tests/src/test/system_contracts/auction/distribute.rs
grpc/tests/src/test/system_contracts/auction/mod.rs
smart_contracts/contracts/system/auction/src/lib.rs
smart_contracts/contracts/test/auction-bids/src/main.rs
types/src/auction.rs

Refs:
https://casperlabs.atlassian.net/browse/EE-1042
https://casperlabs.atlassian.net/browse/EE-1052
Notice `TODO`s in tests.  Something fishy there.  I would expect Wasm-based system contract executions to cost more, I'm suspicious of the fact that none of our other tests have revealed this.

EE-{1042,1052}: update Auction::undelegate to return purse, fix full undelegation

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/traits.rs
node/src/tls.rs

1. Removes `msg` field. It was a vector of bytes that don't tell us anything but was spamming the logs.
2. Displays sender's full key fingerprint instead of capping it.
cherry-picked from another PR to `master`.

[charlie] Improve logging in the era supervisor.

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/traits.rs
node/src/tls.rs

1. Removes `msg` field. It was a vector of bytes that don't tell us anything but was spamming the logs.
2. Displays sender's full key fingerprint instead of capping it.

NO-TICKET: Improve error logging in era supervisor.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs

This is actually not correct!
Instead, let's go back to looking only for summits consisting of honest validators and give up the monotonicity property until the correct monotonous criterion has been worked out.
https://casperlabs.atlassian.net/browse/HWY-157

HWY-157: Don't count faulty validators towards summits.

---

Cargo.lock
execution_engine/src/core/resolvers/v1_function_index.rs
execution_engine/src/core/resolvers/v1_resolver.rs
execution_engine/src/core/runtime/auction_internal.rs
execution_engine/src/core/runtime/externals.rs
execution_engine/src/core/runtime/scoped_instrumenter.rs
grpc/test_support/src/internal/mod.rs
grpc/tests/src/test/contract_api/blake2b.rs
grpc/tests/src/test/contract_api/mod.rs
grpc/tests/src/test/regression/ee_597.rs
grpc/tests/src/test/regression/ee_598.rs
grpc/tests/src/test/system_contracts/auction/bids.rs
grpc/tests/src/test/system_contracts/auction/distribute.rs
grpc/tests/src/test/system_contracts/auction_bidding.rs
node/src/crypto/asymmetric_key.rs
smart_contracts/contract/src/contract_api/runtime.rs
smart_contracts/contract/src/ext_ffi.rs
smart_contracts/contracts/system/auction/src/lib.rs
smart_contracts/contracts/test/blake2b/Cargo.toml
smart_contracts/contracts/test/blake2b/src/main.rs
types/src/account.rs
types/src/auction.rs
types/src/auction/providers.rs
types/src/lib.rs
types/src/public_key.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1041
**Notes:**
- In order to ensure efficient and cheap `AccountHash` construction for the `use-system-contracts` feature, this PR introduces a `runtime::blake2b` function in the contract API.  We aren't ready to officially support this yet - that would require AssemblyScript work and more testing - but this is a first foray in that direction.
- I chose to put the core hashing and construction code alongside `AccountHash` itself.  Providing the explicit `AccountHash::from_public_key` constructor allows us to pass the host-side hashing function while still giving us a better story for moving away from system contract support.  Specifically, the `From<PublicKey>` construction mechanism is much more convenient to use in tests and can …

EE-1042: check key against caller in Auction

---

node/src/components/contract_runtime.rs
node/src/components/small_network/config.rs
node/src/components/storage.rs
node/src/reactor/initializer.rs
node/src/utils.rs

When we changed to use `WithDir` for the storage component (to enable setting the correct path for LMDB), we overlooked doing that for the contract runtime, which piggybacks on the storage config for this path.
This PR fixes that, and also cleans up some unused functions from `utils` (they weren't being flagged by the compiler as they were unnecessarily `pub` rather than `pub(crate)`).

NDRS-455: fix contract runtime initialization issue

---

execution_engine/src/core/runtime/mod.rs
grpc/test_support/src/internal/wasm_test_builder.rs
grpc/tests/src/test/regression/ee_1045.rs
grpc/tests/src/test/regression/mod.rs
grpc/tests/src/test/step.rs
smart_contracts/contracts/system/auction-install/src/main.rs
smart_contracts/contracts/system/auction/src/lib.rs
types/src/auction.rs
types/src/auction/constants.rs
types/src/auction/detail.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1045
Removes `quash_bid` and makes it an impl detail, and then `slash` uses it to slash validator bids.

EE-1045: Fix slashing for validators

---

node/src/components/deploy_buffer.rs
node/src/reactor/queue_kind.rs
node/src/reactor/validator.rs
node/src/types/deploy.rs
node/src/types/timestamp.rs

This implements NDRS-163 by introducing internal mutable state through a reactor timeout that loops after DEPLOY_PRUNE_INTERVAL (10 seconds). This prune does not yet look at descendents.

NDRS-163: limit deploy buffer memory consumption

---

node/src/components/linear_chain_sync.rs

This fixes the bug where the linear chain synchronizer incorrectly runs out of peers to download deploys from.

NO-TICKET: Reset peers on downloaded block

---

node/src/components/api_server/rpcs/info.rs
node/src/components/chainspec_loader.rs

The chainspec info was not being included in the rpc output for some reason; this PR includes it.
```
curl -i -X POST -H 'Content-Type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"info_get_status"}' 'http://localhost:7777/rpc'
```
```
HTTP/1.1 200 OK
content-type: application/json
content-length: 193
date: Tue, 06 Oct 2020 16:51:30 GMT
{"jsonrpc":"2.0","id":1,"result":{"api_version":"1.0.0","chainspec_name":"casper-example","genesis_root_hash":"a59d..42df","peers":{"7561..547f":"127.0.0.1:41742"},"last_finalized_block":null}}>
```

NO-TICKET: include chainspec info in rpc status endpoint

---

stop-dev.sh

This makes the `stop-dev.sh` script use the arguments supplied if there were any, instead of always using "1 2 3 4 5".

NO-TICKET: Use the args supplied in stop-dev.sh

---

Cargo.lock
node/Cargo.toml
node/build.rs
node/src/app/cli.rs
node/src/components/api_server/rpcs/info.rs
node/src/lib.rs
node/src/types/status_feed.rs

As a stopgap measure, make the `--version` command output useful stuff and report the version in RPC status and `/status`.

Add `get_version` utility

---

node/build.rs
node/src/lib.rs

Allows others to tell whether a particular version was compiled with or without the `--release` flag.

Add cargo profile to version string

---

node/src/reactor.rs
node/src/reactor/event_queue_metrics.rs
node/src/reactor/joiner.rs
node/src/reactor/queue_kind.rs
node/src/reactor/validator.rs
node/src/utils/round_robin.rs

https://casperlabs.atlassian.net/browse/NDRS-435
Starts recording sizes of the reactor's event queues. 
For "active node" metrics will be available under `/metrics` endpoint and be dumped in the logs.
For "joining node" measurements will be available only in the logs (since there's no `/metrics` endpoint there at all).

NDRS-435: Add event queue counters. 

---

Cargo.lock
node/Cargo.toml
node/src/reactor.rs

This PR introduces a (hopefully) low-overhead method of measuring event process time, albeit only on CPUs that support it (run `grep tsc /proc/cpuinfo` to find out).
It also tracks the time it takes to process events in a histogram. Events that take longer than 1ms will trigger a `warn!`ing.
If there are long running consensus events, this should root them out via the logs.

Add logging of slow events, track event processing (dispatching) time as metric

---

node/src/components/gossiper.rs
node/src/components/gossiper/gossip_table.rs
node/src/components/gossiper/metrics.rs
node/src/components/gossiper/tests.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This add metrics to the gossiper component and prepare most other reactors for "proper" metrics.
The metrics may note be complete, but they are a good start. This is also a jumping off point for @darthsiroftardis and further metrics implementation.
Whoever is reviewing this, please double check there are no typos in the wiring, because those make metrics silently report invalid data.

Gossiper metrics

---

node/src/components/consensus/highway_core/highway_testing.rs
node/src/logging.rs
resources/charlie/config-example.toml
resources/local/config.toml

Currently, log files where we use `text` rather than `json` for the output get polluted with ANSI escape sequences.
This PR disables colored output by default, allowing users to explicitly enable it when logging to console.

NO-TICKET: add option to enable colored logging output, off by default

---

client/src/deploy/creation_common.rs
execution_engine/src/core/engine_state/executable_deploy_item.rs
node/src/components/deploy_acceptor.rs
node/src/crypto/asymmetric_key.rs
node/src/crypto/hash.rs
node/src/types/deploy.rs
node/src/types/timestamp.rs
types/src/public_key.rs

This PR moves the basic validation of a `Deploy` from the `serde::Deserialize` implementation to a standalone method.  It is called only from within the `DeployAcceptor`, through which all new deploys should pass.  It is not called from the `DeployBuffer` as the check is somewhat expensive and shouldn't be needed there (please confirm whether my assumption is correct or not @goral09?).
This PR also includes an initial tranche of `ToBytes` and `FromBytes` implementations which are used when creating a new `Deploy`.

NDRS-491: fix deploy validation

---

client/src/common.rs
node/src/components/api_server.rs
node/src/components/api_server/rpcs/info.rs
node/src/components/linear_chain.rs
node/src/components/storage.rs
node/src/components/storage/block_height_store.rs
node/src/components/storage/config.rs
node/src/components/storage/in_mem_block_height_store.rs
node/src/components/storage/lmdb_block_height_store.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/types/block.rs
node/src/types/status_feed.rs
resources/charlie/config-example.toml
resources/local/config.toml

This PR updates the `BlockHeightStore` to be a specialized store rather than piggybacking on the existing `Store` trait, which was only designed to be suitable for storing blocks and deploys.  This has allowed for the removal of the `BlockHeightHash` type and the useless `BlockHeightHashMetadata` type.
It simplifies getting a value from the store (the `Store` trait only allows getting a collection of values) and allows us to easily provide a way to get the highest stored value, meaning we have a way to retrieve the highest block from the storage component.  This in turn allows us to remove the cached `last_block` from the linear chain component.
The DB is also able to specify the `DatabaseFlags::INTEGER_KEY` which should provide better performance than the default string sorted by …

NO-TICKET: update BlockHeightStore

---

execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/engine_state/upgrade.rs
grpc/server/protobuf/casper/ipc.proto
grpc/server/src/engine_server/mappings/ipc/exec_config.rs
grpc/server/src/engine_server/mappings/ipc/upgrade_request.rs
grpc/test_support/src/internal/mod.rs
grpc/test_support/src/internal/upgrade_request_builder.rs
grpc/test_support/src/internal/utils.rs
grpc/tests/src/profiling/state_initializer.rs
grpc/tests/src/test/system_contracts/auction_install.rs
grpc/tests/src/test/system_contracts/genesis.rs
grpc/tests/src/test/system_contracts/upgrade.rs
node/src/components/chainspec_loader/chainspec.rs
node/src/components/chainspec_loader/config.rs
resources/charlie/chainspec.toml
resources/local/chainspec.toml
resources/test/valid/chainspec.toml
smart_contracts/contracts/system/auction-install/src/main.rs
types/src/auction.rs
types/src/auction/constants.rs
types/src/auction/internal.rs
types/src/system_contract_errors/auction.rs

This PR makes validator slots a configurable chainspec variable rather than a hardcoded value.
https://casperlabs.atlassian.net/browse/EE-1066

EE-1066: move hardcoded validator slots to chainspec

---

node/src/components/api_server/rpcs/chain.rs
node/src/components/block_executor.rs
node/src/components/block_executor/event.rs
node/src/components/linear_chain.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/reactor/validator.rs
node/src/types/block.rs

https://casperlabs.atlassian.net/browse/NDRS-482
Instead of removing `parent_map` from the `BlockExecutor` entirely, treat it as a cache. If entry is not present in the cache, make a request to the storage. If the key not present in the storage, enqueue the execution for later when the block's parent gets finalized.
Instead of initializing `BlockExecutor::parent_map` with the whole linear chain, built during the joining phase, initialize it only with the last finalized block. 
`parent_map` cannot grow indefinitely and cause memory issues b/c its entries are removed in the `create_block` method.

NDRS-482: Falls back to Linear chain storage if block not present in `BlockExecutor::parent_map`.

---

run-dev.sh

The failure was caused by outdated contract binaries. This fix adds a contract building step to `run-dev.sh` in order to make sure that the contracts are always up to date.

NDRS-514: Fix a panic on get_validators

---

.drone.yml
update-rev.sh
upload.sh

- build deb package for PR and pushes to master, staging, trying, release-*
- push deb package to test repo for above triggers 
- push deb package to prod repo for tag event 
- create draft release on github for tag event 
- support for vault - getting bintray credentials from internal vault 
- support for dynamic revision based on DRONE_BUILD_NR
- CICD tests has been done here : https://drone-auto.casperlabs.io/CasperLabs/test-casper-node-cicd
Howto
https://casperlabs.atlassian.net/wiki/spaces/OPS/pages/827621377/Caser+Node+release

OP-1540 - release to bintray

---

Cargo.lock
grpc/tests/src/test/deploy/context_association.rs
grpc/tests/src/test/deploy/mod.rs
smart_contracts/contracts/test/system-contract-hashes/Cargo.toml
smart_contracts/contracts/test/system-contract-hashes/src/main.rs
types/src/system_contract_type.rs

This PR offers a temporary workaround to allow the contract hashes for mint, pos, and auction to be discoverable on charlie testnet, allowing specific interactions with query in the client such as inspecting bid state.
https://casperlabs.atlassian.net/browse/NDRS-516

NDRS-516: system contract hash capture

---

node/src/app/main.rs
node/src/components/gossiper/gossip_table.rs
node/src/components/storage/lmdb_block_height_store.rs
node/src/components/storage/lmdb_chainspec_store.rs
node/src/components/storage/lmdb_store.rs
node/src/lib.rs

This PR implements some performance improvements based on recent discovery of sub-optimal logic.
It adjusts the gossiper to better follow the intent of the termination condition: now gossiping will actually stop once the desired target infection number has been reached, rather than almost double that as per the existing implementation.
The `finished` and `paused` caches in the gossip table have been optimized with purging in mind.  A benchmark has been added for purging which reveals for a cache with 10,000 entries an improvement from 645,073 ns to 12 ns.
Finally, a constant has been added for use by tokio to set the max thread count, and for use by LMDB to set the max reader count to a common value.  This will ensure we avoid LMDB errors caused by excessive read-only transactions.

NDRS-496 performance improvements

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/protocols/highway.rs

Highway now uses a timestamp set to `Timestamp::now()` where appropriate.
Exceptions to this are:
1. Activity scheduled by the reactor (use the scheduled timestamp instead)
2. Block proposals (use the block timestamp here)
This code assumes that messages with timestamps in the future have been rescheduled and all messages being processed by highway are in the past.
I have made a follow-up ticket to tackle rescheduling future messages here: https://casperlabs.atlassian.net/browse/NDRS-499

[NDRS-433] - Consensus using Timestamp::now() for timestamps

---

Makefile

- client contracts build is a missing target in Makefile atm
- Also, since we're shipping casper-client in `.deb` atm, might as well add that to `make deb`
Or you could just `make build-client-contracts -j`

NO-TICK: add client contracts target in Makefile (and to deb)

---

node/src/components/storage/lmdb_store.rs
node/src/components/storage/store.rs

Solves NDRS-511
This PR adds a query `get()` first before lmdb_store's `put()` to check for the existence of a value. This should be unwinded when we no longer pass WriteFlags::default() and instead pass `NO_OVERWRITE`, and that's left as TODO's in this code.

NDRS-511 - fix storage component's put() return value

---

node/src/components/consensus/era_supervisor.rs

The fault tolerance threshold is specified in percent, but when multiplying the total weight by the percentage, we risk exceeding `u64::MAX`.

Prevent arithmetic overflow in FTT computation.

---

node/src/components/deploy_buffer.rs
node/src/components/storage.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/block.rs

This PR adds the `linear_chain` as an argument to the `DeployBuffer`'s constructor, allowing it to load the finalized deploys from storage.

NDRS-453 - carry over finalized deploys from joiner to validator phase

---

node/src/components/consensus/era_supervisor.rs

This avoids adding validators to `accusations` in several subsequent eras after they equivocated, which would cause them to be included in the slashing instructions multiple times.
https://casperlabs.atlassian.net/browse/NDRS-495

NDRS-495: Don't slash validators twice.

---

smart_contracts/contracts/client/add-bid/src/main.rs
smart_contracts/contracts/client/delegate/src/main.rs
smart_contracts/contracts/system/auction/src/lib.rs
smart_contracts/contracts/test/auction-bidding/src/main.rs
smart_contracts/contracts/test/ee-597-regression/src/main.rs
smart_contracts/contracts/test/ee-598-regression/src/main.rs
types/src/auction.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1063
Removes `URef` value from return of `add_bid` and `delegate` entrypoints.

EE-1063: Remove purse return value.

---

run-dev.sh

* Determine and print the genesis timestamp after building.
* Set the timestamp 30 seconds in the future, as the comment indicates.
* Refer to the stop-dev script in the instructions.

NO-TICKET: run-dev improvements

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs

This doesn't change any implementation; it just moves `Era` and `EraId` to their own module, since `era_supervisor.rs` is already pretty long.

Extract era module from era supervisor.

---

execution_engine/src/storage/error/in_memory.rs
execution_engine/src/storage/error/lmdb.rs
execution_engine/src/storage/trie/merkle_proof.rs
execution_engine/src/storage/trie/mod.rs
execution_engine/src/storage/trie_store/operations/mod.rs
execution_engine/src/storage/trie_store/operations/tests/mod.rs
execution_engine/src/storage/trie_store/operations/tests/proptests.rs
execution_engine/src/storage/trie_store/operations/tests/write.rs
types/src/bytesrepr.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1068
This is only the first part of the work, introducing the core proof types along with code for creating them and validating them.
Subsequent PRs will integrate this work into the querying mechanism and client.

EE-1068: Introducing Merkle Proofs

---

node/src/components/linear_chain_sync.rs

We currently need to execute everything starting from genesis, to correctly initialize the era supervisor, even if we already have blocks in storage.
https://casperlabs.atlassian.net/browse/NDRS-423

NDRS-423: Execute from genesis even if blocks are in local storage.

---

node/src/components/linear_chain_sync.rs

Log height of the linear chain block and its hash when it's handled properly by the joining node.
This is useful for tracking the status of the joining progress.

NO-TICK: Log progress of syncing.

---

resources/charlie/config-example.toml
resources/local/config.toml
resources/production/config-example.toml
utils/nctl/templates/node-config.toml

When a user tried to join the Charlie network it took 4h:50min to synchronize with a chain that has 2700 blocks. Most of the requests to download block headers were finished in <0.5s but there were 280+ that took more than 1 minute. This was due to the `get_remainder_timeout_secs` that defaults to 60 seconds. After updating the value to 5seconds, the joining process took ~22minutes. Most (if not all) validators will never change configuration parameters if they are not told to do so, we want the defaults to be sane and work for most cases.

NO-TICKET: Change default fetch timeout to 5 seconds.

---

client/src/query_state.rs
execution_engine/src/core.rs
execution_engine/src/core/engine_state/query.rs
execution_engine/src/core/tracking_copy/mod.rs
execution_engine/src/core/tracking_copy/tests.rs
execution_engine/src/storage/global_state/in_memory.rs
execution_engine/src/storage/global_state/lmdb.rs
execution_engine/src/storage/global_state/mod.rs
execution_engine/src/storage/trie/merkle_proof.rs
grpc/server/protobuf/casper/ipc.proto
grpc/server/src/engine_server/mod.rs
grpc/test_support/src/internal/wasm_test_builder.rs
node/src/components/api_server/rpcs/state.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1068 (also 1072, 1073, 1074)
**Note:**
Originally planned to base off @dwerner's branch for #374, but touched base with him and he still has some work to do over there, so decided to open against master here.  The code here should be relatively easy to port to that branch.  Happy to help with that if need be.

EE-1068: enrich queries with merkle proofs, validate

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/highway_testing.rs

Add equivocators seen from a block to the accusations on finalization, even if they weren't included in the candidate block explicitly.
https://casperlabs.atlassian.net/browse/NDRS-440

NDRS-440: Add information from the consensus protocol to accusations.

---

Cargo.lock
node/src/components/api_server.rs
node/src/components/api_server/event.rs
node/src/components/api_server/sse_server.rs
node/src/components/block_executor.rs
node/src/components/block_executor/event.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

The output of a `DeployProcessed` event in the event stream is now equivalent to the following:
```
{
"DeployProcessed": {
"deploy_hash": "871f50ca3cc5627947e4310850b03e0a105a2ae4d028a2a85a9258455da30114",
"account": "010c801c47ed20a9ec40a899ddc7b51a15db2a6c55041313eb0201ae04ee9bf932",
"timestamp": "2020-10-27T01:55:17.276Z",
"ttl": "1day",
"dependencies": [],
"block_hash": "d233ce4865db29eea5c54bb2074ea11b51d736ba46082d62f299323e10f36601",
"execution_result": {
...
}
}
}
```

NDRS-535: add more fields to DeployProcessed server sent event

---

README.md

Add two missing dependencies found while installing on Ubuntu 20.04 
pkg-config
libssl-dev
gcc
g++

Add Missing Dependencies

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs

This collects all accusations of finalized blocks over the course of an era, and when finalizing the switch block, takes their union.
That way you can't remove someone from the list of to-be-slashed validators anymore, by omitting them from the explicit accusations list in a block you propose.
https://casperlabs.atlassian.net/browse/HWY-166

HWY-166: Add all of an era's accusations to the switch block.

---

client/src/balance.rs
client/src/main.rs
client/src/merkle_proofs.rs
client/src/query_state.rs
execution_engine/src/core.rs
execution_engine/src/core/engine_state/balance.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/execution/error.rs
execution_engine/src/core/tracking_copy/ext.rs
execution_engine/src/core/tracking_copy/mod.rs
grpc/test_support/src/internal/wasm_test_builder.rs
grpc/tests/src/test/get_balance.rs
grpc/tests/src/test/mod.rs
node/src/components/api_server/rpcs/state.rs
types/src/key.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1079
Followed a similar approach to what we did with `query-state` here (using the purse lookup scheme as opposed to the query recursion), so nothing should be terribly surprising.

EE-1079: enrich balance with merkle proofs, validate

---

client/src/block/get.rs
client/src/common.rs
client/src/deploy/list.rs
client/src/get_state_hash.rs
node/src/components/api_server.rs
node/src/components/api_server/event.rs
node/src/components/api_server/rpcs/chain.rs
node/src/components/api_server/rpcs/state.rs
node/src/effect/requests.rs

Expanded the client to query and retrieve a block by its height as well as its hash. Renamed the arg from `block-hash` to `block-identifier`
By Hash
By Height:

NDRS-541: Add Get-Block by height

---

client/src/get_auction_info.rs
client/src/main.rs
node/src/components/api_server/rpcs/state.rs

This PR adds a get-auction-info subcommand to client-rs.
https://casperlabs.atlassian.net/browse/NDRS-542
`cargo run --release -- get-auction-info`
```
{
"jsonrpc": "2.0",
"result": {
"bids": {
"0248..6873": {
...
},
...
},
"era_id": 10,
"state_root_hash": "42ad1966f4203dbc41ca63da3ab2e99e0da6b5155369cee7e4bbad1f9230463c",
"validator_weights": {
"0248..6873": "100000000000001",
...
}
},
"id": 572773124
}
```

NDRS-542: add 'get auction info' subcommand to client-rs

---

node/src/crypto/asymmetric_key.rs

The issue was that we had left a way for secp256k1 public keys to be held in uncompressed form internally.  This was a problem when converting the public key to an account hash, as the raw bytes used to generate the hash were different to those of the compressed form.
This PR removes the ability for our `PublicKey` type to hold the secp256k1 variant in uncompressed form.
I have ensured that the flow described in the bug report works correctly with this change.

NDRS-539: handle uncompressed secp256k1 public keys

---

types/src/system_contract_errors/auction.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1085
When doing some related work, I discovered that `Error::InvalidValidatorSlotsValue` was missing conversion code, so here I'm introducing a regression test and fixing it.

EE-1085: add failing test for auction Error conversions, fix failures

---

.drone.yml
build_wasm_package.sh

- package contracts from /target/wasm32-unknown-unknown/release into tar.gz package 
- upload package onto s3 bucket under the path wasm_contracts/${WASM_PACKAGE_VERSION}"
- trigger only for release* and master branch and push event 
- use AWS credentials from internal vault - safe to expose this step also in PR if needed
- make not it's using new build image, s3cmd-build which was already merged into buildenv repo, image is on docker hub as well
- tested on mirrored repo https://drone-auto.casperlabs.io/CasperLabs/test-casper-node-cicd/127/1/11

[OP-1617] package wasm contracts and upload to s3

---

node/src/components/consensus.rs
node/src/components/consensus/cl_context.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/protocols/highway.rs

This cleanup is a preparation for making the era supervisor easier to test ([NDRS-546](https://casperlabs.atlassian.net/browse/NDRS-546)). To do that, I'd like to implement a mock consensus protocol that can be used instead of `HighwayProtocol`, so that tests can be written independently of Highway-specific details. However, that abstraction is currently broken, and we've leaked a lot of Highway logic into the era supervisor. E.g. `activate_validator` is not part of the trait. To put it there, the trait needs `C::ValidatorSecret` (and we'll need to move the instantiation of the Highway `Params` inside of its implementation).
https://casperlabs.atlassian.net/browse/NDRS-546

NDRS-546: Use Context trait in ConsensusProtocol.

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/protocols/highway.rs

Continuing https://github.com/CasperLabs/casper-node/pull/454, this moves `active_validator` into the `ConsensusProtocol` trait and moves some Highway-specific logic from the era supervisor into the `HighwayProtocol` implementation.
https://casperlabs.atlassian.net/browse/NDRS-546

NDRS-546: Further disentangle Highway from EraSupervisor.

---

execution_engine/src/core/runtime/mod.rs
grpc/tests/src/test/system_contracts/standard_payment.rs

This PR makes an adjustment to the amount charged when a gas limit is hit.
https://casperlabs.atlassian.net/browse/EE-1091
If the gas limit would be exceeded, `charge_gas` previously did not increase the gas counter before returning false (which prompts calling logic to raise an out of gas error). 
However, if the gas counter was 0 and the gas limit would be exceeded by the first attempt to charge gas, it resulted in an out of gas error and 0 gas cost. Though an edge case, this was unintended and a potential attack vector.
This PR changes the behavior slightly by setting the gas counter equal to the gas limit before returning false in either case where the amount to be added would exceed the limit, which results in an out of gas error being raised and the correct amount of gas being …

EE-1091: out of gas error amount charged correction

---

ci/casper_updater/src/main.rs
ci/casper_updater/src/regex_data.rs
ci/publish.sh
node_macros/Cargo.toml
node_macros/README.md
node_macros/src/lib.rs
node_macros/src/parse.rs

This PR updates the `casper-updater` tool to also update files affected by version changes in the new `casper-node-macros` crate.

NDRS-549: include casper-node-macros in the casper-updater tool

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/protocols/highway.rs
node/src/reactor/joiner.rs

That way the era supervisor can be configured to work with different protocols.
https://casperlabs.atlassian.net/browse/NDRS-546

NDRS-546: Pass consensus constructor into era supervisor.

---

Cargo.lock
client/Cargo.toml
client/README.md
client/lib/cl_type.rs
client/lib/error.rs
client/lib/keygen.rs
client/lib/lib.rs
client/lib/parsing.rs
client/lib/rpc.rs
client/lib/validation.rs
client/src/block/get.rs
client/src/common.rs
client/src/deploy/creation_common.rs
client/src/deploy/get.rs
client/src/deploy/list.rs
client/src/deploy/make.rs
client/src/deploy/put.rs
client/src/deploy/send.rs
client/src/deploy/sign.rs
client/src/deploy/transfer.rs
client/src/get_balance.rs
client/src/get_state_hash.rs
client/src/main.rs
client/src/query_state.rs
node/Cargo.toml

This PR covers several points:
* The rustdocs for the library and help strings for the binary were all reviewed and consistent terminology used throughout
* The README was fixed (it hadn't been updated after the renaming of `global_state_hash`)
* Since [the PR to warp-json-rpc](https://github.com/AtsukiTak/warp-json-rpc/pull/1) has been merged and published, the node can now handle strings as the RPC IDs, making it compliant with the JSON-RPC spec.  The client has been updated to take advantage of this.
* Simple session args and payment args need to be wrapped in double quotes to be parsed correctly; the help strings were updated to cover this
* The `node_address` arg now has trailing `/`s removed, meaning values like `http://localhost:7777/` now succeed

NO_TICKET: Several client nitpicks

---

node/src/reactor/joiner.rs

Related to https://casperlabs.atlassian.net/browse/NDRS-544
This fixes the panic that happens after the joiner drops proto block validation requests, which drops the responder, breaks the channel and triggers a panic in `make_request`.
If the joiner handles consensus messages, it can receive proposals from validators, and consensus will try to validate proto blocks it receives as proposals, triggering the issue. However, consensus messages are not required for proper functioning of the joiner and can be ignored, which is what this PR does.

NDRS-544: Don't handle consensus messages in the joiner.

---

node/src/components/consensus/highway_core/highway.rs

This may be `None` if validator is not active.
Failed in #486

NO-TICK: Do not unwrap `active_validator.as_mut`.

---

grpc/tests/src/test/system_contracts/auction/bids.rs
node/src/types/json_compatibility/auction_state.rs
smart_contracts/contracts/system/auction-install/src/main.rs
types/src/auction.rs
types/src/auction/bid.rs
types/src/auction/seigniorage_recipient.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1098
> This will improve the auction by disentangling the bid modification logic from the surrounding auction code.

EE-1098: privatize fields on auction::Bid

---

node/src/components/linear_chain_sync.rs

https://casperlabs.atlassian.net/browse/NDRS-571

NDRS-571: LinearChainSync: Verify parent hashes.

---

node/src/components/consensus.rs

The [two log statements](https://github.com/CasperLabs/casper-node/blob/d044ad02f6dce60db322005e5a34f650a6a78880/node/src/reactor.rs#L400) for events now look like:
`Nov 09 16:00:05.590 DEBUG crank{ev=497}:dispatch events{ev=497}: [casper_node::reactor reactor.rs:400] event=network: msg from 3bf5..5908: payload: Consensus::protocol message 0000..b709 in era 0; q=NetworkIncoming`
`Nov 09 16:00:05.590 TRACE crank{ev=497}:dispatch events{ev=497}: [casper_node::reactor reactor.rs:401] event=Network(IncomingMessage { peer_id: KeyFingerprint(3bf5..5908), msg: Message(Consensus(Protocol { era_id.0: 0, .. })) }); q=NetworkIncoming`
Before, they looked like this:
`Nov 09 14:59:44.724 DEBUG crank{ev=7403}:dispatch events{ev=7403}: [casper_node::reactor reactor.rs:400] event=network announcement: …

NO-TICKET: Make ConsensusMessage debug string a bit less verbose.

---

client/lib/deploy.rs
execution_engine/src/core/engine_state/genesis.rs
node/src/components/block_proposer.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/storage.rs
node/src/components/storage/error.rs
node/src/components/storage/lmdb_block_height_store.rs
node/src/components/storage/lmdb_store.rs
node/src/crypto/asymmetric_key.rs
node/src/types/block.rs
node/src/types/deploy.rs
node/src/types/json_compatibility/execution_result.rs

Replaced usage of `serde` with our custom serialization implementation for data structures interacting with the storage component. 
REF: https://casperlabs.atlassian.net/browse/NDRS-484

NDRS-484: Replace Serde with ToBytes/FromBytes implementation

---

.drone.yml

The step to verify genesis .md5 file was missed during pipeline optimization.  This puts that check back in place.

NO-TICK Adding back in missed step for check_genesis_validation.sh

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/tests/mock_proto.rs

It's not a `Result<_, _>` (and doesn't implement `Try`), and the name was a bit long. We already use `HighwayProtocol` where we want to say "Highway Consensus Protocol", so it seems legitimate to omit the `Consensus` part here, too. It's only used within the consensus component anyway.

NO-TICKET: Rename ConsensusProtocolResult to ProtocolOutcome.

---

Cargo.lock
client/Cargo.toml
execution_engine/Cargo.toml
execution_engine/src/lib.rs
grpc/cargo_casper/Cargo.toml
grpc/cargo_casper/src/common.rs
grpc/cargo_casper/src/tests_package.rs
grpc/server/Cargo.toml
grpc/test_support/Cargo.toml
grpc/test_support/src/lib.rs
node/Cargo.toml
node/src/lib.rs
node_macros/Cargo.toml
node_macros/src/lib.rs
smart_contracts/contract/Cargo.toml
smart_contracts/contract/src/lib.rs
smart_contracts/contract_as/package-lock.json
smart_contracts/contract_as/package.json
types/Cargo.toml
types/src/lib.rs

Delta-1 source code (currently 1.6.0 for client and node) will be published on crates.io as 0.1.0.  
This is the post-release version bump so the next release is 0.2.0.

OP-1649 Reset next version of software to 0.2.0.

---

node/src/components/chainspec_loader/chainspec.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/endorsement.rs
node/src/components/consensus/highway_core/evidence.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/finality_detector/horizon.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/panorama.rs
node/src/components/consensus/highway_core/state/tallies.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/highway_core/state/unit.rs
node/src/components/consensus/highway_core/test_macros.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/traits.rs

Use the term "unit" for what we called "votes" so far, to be in line with the paper.
The word "vote" is still used in the `tallies` modules and a few other places, where it is appropriate: A "unit" is considered to carry multiple "votes", one at each block height, for the block that is the ancestor of the unit's new block or fork choice.
https://casperlabs.atlassian.net/browse/NDRS-573

NDRS-573: Rename vote to unit.

---

node/src/components/consensus/candidate_block.rs
node/src/components/consensus/era_supervisor.rs

It's wrong to call it when the proto block has been validated, because at that point it's not necessarily passed into the consensus protocol yet: It may still be waiting for evidence that it depends on.
Only once it's passed in will the protocol be able to detect finalization (or later maybe orphans).

NO-TICKET: Call announce_proposed_proto_block later.

---

grpc/test_support/src/internal/wasm_test_builder.rs
grpc/tests/src/test/regression/ee_1103.rs
grpc/tests/src/test/regression/mod.rs
types/src/auction.rs
types/src/auction/bid.rs
types/src/auction/delegator.rs

Refs:
https://casperlabs.atlassian.net/browse/EE-1101
https://casperlabs.atlassian.net/browse/EE-1103
This PR:
- introduces a `Delegator` struct to track a given delegator's stake and bonding purse.
- adds a `delegators` field to the `Bid` type to track the delegators attached to a particular validator.
- uses the `delegators` and `staked_amount` fields on `Bid` to synthesize a given validator's total stake when calculating bid "scores" or "weights" (fixing [EE-1103](https://casperlabs.atlassian.net/browse/EE-1103)).
**IMPORTANT**:
I'm presenting `Delegator` and and the `delegators` field on `Bid` _not_ as the minimal fix for the bug, but as part of a larger tranche of work to reduce some of the complexity in the auction.  Rather than saving all of the changes for a later PR, I wanted to …

EE-{1101,1103}: add auction::Delegator, fix bid scores

---

execution_engine/src/core/runtime/auction_internal.rs
grpc/tests/src/test/regression/ee_598.rs
grpc/tests/src/test/step.rs
grpc/tests/src/test/system_contracts/auction/bids.rs
grpc/tests/src/test/system_contracts/auction_bidding.rs
grpc/tests/src/test/system_contracts/auction_install.rs
smart_contracts/contracts/system/auction-install/src/main.rs
smart_contracts/contracts/system/auction/src/lib.rs
types/src/auction.rs
types/src/auction/constants.rs
types/src/auction/delegator.rs
types/src/auction/detail.rs
types/src/auction/providers.rs
types/src/auction/types.rs
types/src/auction/unbonding_purse.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1106
This PR follows #524, removing the needless `BidPurses` map.

EE-1106: auction: remove BidPurses map

---

grpc/test_support/src/internal/wasm_test_builder.rs
grpc/tests/src/test/system_contracts/auction/bids.rs
grpc/tests/src/test/system_contracts/auction_install.rs
node/src/effect.rs
smart_contracts/contracts/system/auction-install/src/main.rs
types/src/auction.rs
types/src/auction/constants.rs
types/src/auction/detail.rs
types/src/auction/seigniorage_recipient.rs

Ref: 
https://casperlabs.atlassian.net/browse/EE-1107
https://casperlabs.atlassian.net/browse/EE-1108
This PR:
- cleans up `Auction::run_auction`
- removes the `EraValidators` map stored at `ERA_VALIDATORS_KEY`.
**IMPORTANT**:
~~This PR depends on #530.  Please review the diff here: https://github.com/henrytill/casper-node/compare/EE-1106...henrytill:EE-1107+1108~~

EE-{1107,1108}: clean up Auction::run_auction, remove EraValidators map

---

execution_engine/src/core/tracking_copy/byte_size.rs

This PR fixes a long standing but minor bug in logic ultimately used by the TrackingCopyCache to control sizing. It removes out of date HeapSizeOf trait implementations for Account and ContractWasm and switches the logic to use serialized_length instead, which is consistent with all other StoredValue variants.
https://casperlabs.atlassian.net/browse/EE-798

EE-798: HeapSizeOf fix for Account and ContractWasm

---

run-dev-tmux.sh

This PR adds my own tmux-based variant of the `run-dev.sh`
Depends on #546.  
**ACTUAL DIFF HERE**: https://github.com/henrytill/casper-node/compare/NO-TICKET-envsubst...henrytill:NO-TICKET-add-run-dev-tmux

NO-TICKET: add run-dev-tmux.sh

---

Cargo.lock
execution_engine/src/core/resolvers/v1_resolver.rs
grpc/tests/src/test/regression/ee_1071.rs
grpc/tests/src/test/regression/mod.rs
smart_contracts/contract/src/contract_api/account.rs
smart_contracts/contract/src/contract_api/runtime.rs
smart_contracts/contract/src/contract_api/storage.rs
smart_contracts/contract/src/contract_api/system.rs
smart_contracts/contract/src/ext_ffi.rs
smart_contracts/contract_as/assembly/externals.ts
smart_contracts/contracts/client/counter-define/src/main.rs
smart_contracts/contracts/test/deserialize-error/src/main.rs
smart_contracts/contracts/test/ee-1071-regression/Cargo.toml
smart_contracts/contracts/test/ee-1071-regression/src/lib.rs
smart_contracts/contracts/test/ee-1071-regression/src/main.rs
types/src/api_error.rs
types/src/system_contract_type.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1071
By naming a function inside a library that's part of a contract the same as one of FFI functions we export results in infinite loop if we'd call contract API function that internally uses imported FFI function of said name.
Example:
```rust
// Contract's lib.rs
#[no_mangle]
pub extern "C" fn new_uref() {
let new_uref = storage::new_uref(0); // This results in calling `new_uref` (itself) rather than imported one
runtime::put_key(&new_uref.to_formatted_string(), new_uref.into())
}
// Contract's main.rs
#[allow(unused_imports)]
use ee_1071_regression::new_uref; // doesn't import `new_uref` from the host
```
With this change I prefixed host functions with a `casper_` prefix to avoid obvious naming clashes.
NOTE: Originally I was thinking …

EE-1071: Added regression test for the issue.

---

generate-chainspec.sh
run-dev-tmux.sh

This PR adds a positional delay parameter to `generate-chainspec.sh` and `run-dev-tmux.sh`.  Went with the simple approach here rather than using `getopt` or a bespoke parser.
Examples:
```sh
./generate-chainspec.sh
./generate-chainspec.sh 50
./run-dev-tmux.sh
./run-dev-tmux.sh 50
```

NO-TICKET: {generate-chainspec,run-dev-tmux}.sh: add delay parameter

---

node/src/components/block_proposer.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/tests.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/effect/requests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types.rs
node/src/types/block.rs

https://casperlabs.atlassian.net/browse/NDRS-168
This implements [CEP-20](https://github.com/CasperLabs/ceps/blob/master/text/0020-block-proposer-improvements.md). (EDIT 2020-11-20: with some modifications. The CEP will be updated to reflect them.)

NDRS-168: Don't rely on event order in deploy buffer; fix block handling.

---

node/src/components/consensus/highway_core/endorsement.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/validators.rs

Also check on pre-validation whether endorsements are empty, so we don't create empty entries in those maps.
https://casperlabs.atlassian.net/browse/HWY-181

HWY-181: Simplify State endorsement fields.

---

node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/tests.rs

If the era height is 5, the last block is block 4, not 5, since we start counting at 0.
https://casperlabs.atlassian.net/browse/HWY-199

HWY-199: Fix era height off-by-one error.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/panorama.rs

This will make the diff smaller when we merge LNC-compliant unit creation.
* Add a `Panorama::iter_faulty` to deduplicate some code.
* `citable_panorama` will be replaced with something simpler, so I remove it here.
* Rename a few identifiers that were overlooked or renamed by mistake.
https://casperlabs.atlassian.net/browse/HWY-205

HWY-205: Some cleanups related to LNC.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/protocols/highway.rs

With cross-era slashing there are now faults other than equivocations. If we are a faulty node we should not produce new units.

NO-TICKET: Stop voting on own fault, not just equivocation.

---

Cargo.lock
node/Cargo.toml
node/src/components/block_proposer.rs
node/src/components/block_proposer/deploy_sets.rs
node/src/components/block_proposer/event.rs
node/src/components/block_proposer/metrics.rs
node/src/components/storage.rs
node/src/components/storage/tests.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
resources/local/config.toml
resources/production/config-example.toml

State persistence had been removed during the storage refactoring merged earlier, this PR restores this functionality, albeit slightly different.
Previously no state snapshot was stored by the block proposer, instead the storage component contained custom logic to recalculate the sets of pending deploys, finalized deploys, etc. on demand. This logic was called manually "between reactors", in an `async` function, requiring special-casing and circumventing the component structure. The approach did guarantee that the component was only instantiated once data had been restored.
The new implementation adds a general load/store state logic to the storage component that works within the effect system, to be possibly reused by other components that need to store small state snapshots. For this to …

NDRS-581: Block proposer state persistence

---

node/src/components/block_executor.rs
node/src/components/block_executor/event.rs

When in validator mode, node may end up finalizing (and requesting execution) blocks that have been executed when in joining mode. This PR proposes a solution where double execution does not happen.
JIRA ticket: https://casperlabs.atlassian.net/browse/NDRS-424
The flow for finalized blocks when node is in _validator mode_:
1. Consensus finalizes a proposal and sends an `ExecuteBlock(finalized_block)` to the `BlockExecutor`.
2. `BlockExecutor` executes the `finalized_block` and announces `LinearChainBlock`.
3. Announcement creates two events:
* Sends an event to the event stream about new block being added.
* Sends a `LinearChainBlock` to the `LinearChain` component.
4. `LinearChain` component stores the block and sends an event to the `Consensus` component.
5. `Consensus` component acts …

NDRS-424: Do not execute block when it had been executed in the past.

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/highway_core/endorsement.rs
node/src/components/consensus/highway_core/evidence.rs
node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/panorama.rs
node/src/components/consensus/highway_core/validators.rs

This uses hashes to order messages in the Highway Core DES tests, so that e.g. updates to the vertex structure don't require complicated extensions of this trait implementation.
(In preparation for [HWY-168](https://casperlabs.atlassian.net/browse/HWY-168).)

NO-TICKET: Simplify impl Ord for HighwayMessage.

---

node/src/components/chainspec_loader/chainspec.rs
node/src/components/contract_runtime.rs
node/src/components/small_network.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This PR adds a handshake once a new connection is established between peers whereby the genesis config hashes are exchanged and the connection dropped in the case of a mismatch.
On establishing an outgoing connection, the peer immediately sends the handshake as the first message.  On the receiving side, the handshake is compared to the local genesis config hash, and if different, the connection is dropped.  For simplicity, after dropping any connection, the peer checks to see if it's isolated and terminates if so.  This check was previously only done upon a bootstrap connection failing.  However, now the bootstrap connection can succeed only to be dropped shortly afterwards due to a handshake failure, by which time the isolation check was already completed.
The implementation could be …

NO-TICKET: drop connections to peers which don't have an identical genesis config hash

---

grpc/tests/src/test/system_contracts/auction/bids.rs
grpc/tests/src/test/system_contracts/auction_bidding.rs
types/Cargo.toml
types/src/auction.rs
types/src/auction/detail.rs
types/src/auction/unbonding_purse.rs
types/src/uref.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1117
Adds two additional fields for each unbonding request 
```rust
/// Validator Public Key
pub validator_public_key: Public Key, 
/// Unbonder Public Key
pub unbonder_public_key: Public Key,
```

EE-1117: Extend UnbondingPurse structure.

---

grpc/tests/src/test/system_contracts/auction/bids.rs
grpc/tests/src/test/system_contracts/auction_bidding.rs
types/src/auction/detail.rs
types/src/auction/unbonding_purse.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1118
Instead of checking if unbonding era is reached for given unbonding
attempt, we preserve era where the request was made, and then unbonding
delay is calculated at the time when we process unbonding lists.
This is in preparation to put unbonding delay into chainspec and to make
it upgradable.

EE-1118: Replace unbonding era with a creation era

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/tests/mock_proto.rs
node/src/effect.rs

https://casperlabs.atlassian.net/browse/NDRS-294
Only now the block proposer (formerly the deploy buffer) needs the set of deploys from the non-finalized ancestors instead of the ancestors themselves, so we pass that.

NDRS-294: Pass the list of ancestors to the block proposer

---

node/src/components/gossiper.rs
node/src/components/gossiper/event.rs
node/src/components/gossiper/gossip_table.rs
resources/local/config.toml

This PR fixes a bug which only has an effect if a peer is connected to less than or equal to the `gossip.infection_target` config value (currently 3 by default).
The problem is that when the gossiper calls its internal gossip table to inform it of a new item to gossip, it returns how many peers to gossip to.  The table tracks the state of gossiping this item, including an in-flight count of gossip messages sent, expecting a response or timeout for each.
Neither the gossiper nor the gossip table are aware of how many peers we're actually connected to, so upon sending a gossip event to the network component, it responds with a list of the peers which were actually attempted.  When the gossiper handles this response, it performs the following steps:
* if we didn't gossip to any peers, it …

NO-TICKET: fix gossiper bug

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/validators.rs

In preparation for the HWY-204 (test that validator creates only LNC-complaint units) I've added a wrapper and some helper methods that hide the implementation details of interacting with `ActiveValidator`. The goal is that when writing a test involving multiple `ActiveValidators` we won't have to know who is the next leader or when it should produce the next unit (its timestamp) as all of that will be encapsulated in the helper methods. For example:
```rust
let proposal_round_1 = test_state.next_leader().propose();
let confirmation_bob = test_state.handle_new_unit(BOB, proposal_round_1);
let witness_bob = test_state.handle_next_timer(BOB);
let proposal_round_2 = test_state.next_leader().propose();
// etc.
```
I've left unchanged the manual assertions of the units' timestamps or the …

Refactor `ActiveValidator` tests.

---

node/src/components/small_network.rs

Reverts CasperLabs/casper-node#612

NO-TICKET: reinstate "handshake on outgoing connections to avoid banning peers"

---

Makefile

This came about because docker_make.sh was failing on fresh boxes when building the deb due to missing wasm32-unknown-unknown. I think it makes sense to run setup prior to anytime you build the deb.

NO-TICK: run setup before packaging

---

grpc/test_support/src/internal/wasm_test_builder.rs
grpc/tests/src/test/regression/ee_1119.rs
grpc/tests/src/test/regression/mod.rs
types/src/auction.rs
types/src/auction/unbonding_purse.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1119
Regression test scenario:
- validator X delegates funds on genesis validator Y
- validator Y will do `withdraw_bid` on himself after unlock period is hit
- validator X would `undelegate` funds on Y
- (at this point `unbonding_purses` contains two entries for validator Y: one with `is_validator()` other one with `!is_validator()`)
- slash validator Y
- now only element in the `unbonding_purses` for Y is the `!is_validator()` entry that X originated with `undelegate`

EE-1119: update Auction::slash to handle cases where a validator has delegated using its validator key

---

execution_engine/src/core/resolvers/v1_function_index.rs
execution_engine/src/core/resolvers/v1_resolver.rs
execution_engine/src/core/runtime/auction_internal.rs
execution_engine/src/core/runtime/externals.rs
execution_engine/src/core/runtime/mod.rs
execution_engine/src/core/runtime/scoped_instrumenter.rs
execution_engine/src/core/runtime_context/mod.rs
execution_engine/src/core/tracking_copy/byte_size.rs
execution_engine/src/core/tracking_copy/mod.rs
execution_engine/src/shared/stored_value.rs
execution_engine/src/shared/transform.rs
grpc/server/protobuf/casper/state.proto
grpc/server/src/engine_server/mappings/state/auction_info.rs
grpc/server/src/engine_server/mappings/state/key.rs
grpc/server/src/engine_server/mappings/state/mod.rs
grpc/server/src/engine_server/mappings/state/stored_value.rs
grpc/tests/src/test/system_contracts/auction/distribute.rs
grpc/tests/src/test/system_contracts/auction_install.rs
node/src/types/json_compatibility/stored_value.rs
smart_contracts/contract/src/contract_api/system.rs
smart_contracts/contract/src/ext_ffi.rs
smart_contracts/contracts/system/auction/src/lib.rs
types/src/auction.rs
types/src/auction/auction_info.rs
types/src/auction/detail.rs
types/src/auction/providers.rs
types/src/execution_result.rs
types/src/key.rs
types/src/public_key.rs
types/src/system_contract_errors/auction.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1115
This PR:
- introduces an `AuctionInfo` type, a `Key::AuctionInfo(EraId)` variant, and a `StoredValue::AuctionInfo(AuctionInfo)` value.
- updates `Auction::distribute` to store seigniorage metadata as `AuctionInfo` at these keys.

EE-1115: persist seigniorage metadata

---

node/src/types/status_feed.rs

This will simplify the process of getting the current account's balance since this requires a state root hash to query the global state. 
I've added the creator just for a good measure since it seems like something that might be useful.

NO-TICKET: Add `state_root_hash` and `creator` to /status response.

---

grpc/server/protobuf/casper/ipc.proto
node/src/components/chainspec_loader/chainspec.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/tests/utils.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/reactor/validator/tests.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/production/validation.md5
resources/test/valid/chainspec.toml

...because we already have genesis.timestamp

NDRS-656: Remove highway.genesis_era_start_timestamp

---

client/README.md
client/lib/ffi.rs
client/lib/lib.rs
client/lib/rpc.rs
client/src/block.rs
client/src/block/transfers.rs
client/src/main.rs
node/src/components/block_executor.rs
node/src/components/rpc_server.rs
node/src/components/rpc_server/event.rs
node/src/components/rpc_server/http_server.rs
node/src/components/rpc_server/rpcs/chain.rs
node/src/components/rpc_server/rpcs/docs.rs
node/src/components/storage.rs
node/src/effect.rs
node/src/effect/requests.rs
types/src/account.rs
types/src/transfer.rs

This PR adds the get-block-transfers rpc endpoint and client subcommand, allowing external consumers to easily get all transfers for a given block (if any).
https://casperlabs.atlassian.net/browse/NDRS-625
```
{
"jsonrpc": "2.0",
"result": {
"api_version": "1.0.0",
"block_hash": "d577f98843c2b94b5e7e241aa8005b3ea86188211d10f702db684998143e4f70",
"transfers": [
{
"amount": "100000000",
"deploy_hash": "ab87c5f2c0f6f331bf488703676fb0c68f897282dfbb8e085752f220a3dfc25e",
"from": "account-hash-1ace33e66142d5a0679ba5507ef75b9c09888d1567e86100d1db535fa819a962",
"gas": "0",
"id": null,
"source": "uref-21f7316e72d1baa7b706a9083077d643665ad3a56673c594db9762ceac4f3788-007",
"target": "uref-c5eb9788156b53c9a599dfb5e591c6399580b491c72086a6bc028dd18fdfcb2d-004"
}
]
},
"id": 7229488934468542904
}
```

NDRS-625: get-block-transfers rpc endpoint

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/evidence.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/highway_core/test_macros.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/tests.rs

We will need an upper limit for the size of our messages, and evidence of someone endorsing two conflicting forks includes a list of units. Limiting the number of entries in that list lets you get away with endorsing two conflicting forks at sequence numbers that differ by more than this. It still prevents the _exponential_ number of forks in the "fork bomb" scenario, though.
This PR also makes units invalid whose timestamp is before the beginning of the era. Together with the limit of two units per round, and the minimum round length, this effectively limits the sequence numbers. Thus even the linear increase in the number of conflicting forks that could be endorsed only becomes relevant after sufficiently many rounds have passed.
In `HighwayProtocol` we set the limit to roughly the …

HWY-212: Limit the number of units in endorsement evidence

---

node/src/components/chainspec_loader/chainspec.rs
node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/era_supervisor/tests.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/components/consensus/tests/mock_proto.rs
node/src/components/consensus/tests/utils.rs
node/src/reactor/joiner.rs

This will be needed to create finality signatures only when bonded, and to compute the total weight of collected signatures.
Also removes the concept of `Motes` from the consensus component.
https://casperlabs.atlassian.net/browse/NDRS-527

NO-TICKET: Store validator weights in Era, and simplify their handling.

---

grpc/tests/src/test/regression/ee_1119.rs
grpc/tests/src/test/regression/ee_1120.rs
grpc/tests/src/test/regression/mod.rs
types/src/auction.rs
types/src/auction/detail.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1120
Adds a clause to the slashing logic so delegators present in bids entry for given slashed validator are collected, and then also removed from unbonding purses for given slashed validator.
This also inlines `detail::quash_bid` to get the benefit of removing validator's delegators as part of single step per validator to be slashed.

EE-1120: Slash unbonding delegators.

---

utils/nctl/docs/setup.md

Resolves STS-64. Just a simple documentation update.

Adding contract building step to `nctl` prerequisites documentation

---

execution_engine/src/core/resolvers/v1_function_index.rs
execution_engine/src/core/resolvers/v1_resolver.rs
execution_engine/src/core/runtime/auction_internal.rs
execution_engine/src/core/runtime/externals.rs
execution_engine/src/core/runtime/mod.rs
execution_engine/src/core/runtime/scoped_instrumenter.rs
execution_engine/src/core/runtime_context/mod.rs
execution_engine/src/core/tracking_copy/byte_size.rs
execution_engine/src/core/tracking_copy/mod.rs
execution_engine/src/shared/stored_value.rs
execution_engine/src/shared/transform.rs
grpc/server/protobuf/casper/state.proto
grpc/server/src/engine_server/mappings/state/auction_info.rs
grpc/server/src/engine_server/mappings/state/key.rs
grpc/server/src/engine_server/mappings/state/stored_value.rs
grpc/tests/src/test/system_contracts/auction/distribute.rs
node/src/types/json_compatibility/stored_value.rs
smart_contracts/contract/src/contract_api/system.rs
smart_contracts/contract/src/ext_ffi.rs
smart_contracts/contracts/system/auction/src/lib.rs
types/src/auction.rs
types/src/auction/era_info.rs
types/src/auction/providers.rs
types/src/execution_result.rs
types/src/key.rs
types/src/system_contract_errors/auction.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1127
Doing this to avoid naming conflicts with the existing `GetAuctionInfo` RPC endpoint.

EE-1126: rename AuctionInfo to EraInfo

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway_testing.rs

https://casperlabs.atlassian.net/browse/HWY-207
The warnings were printed for cases that were already covered with different tests (like "is our own proposal?", "is the creator faulty?", etc.) but those checks were done later than the test for `earliest_unit_timestamp`. The solution was simply to rearrange the code so that the `earliest_unit_timestamp is greater than …` is logged only if that's the last error possible.
There was also another small issue in the DES tests setup where it used `Timestamp::now` which was different by a millisecond or two between validators.
I've also modified how equivocation creation is done in the tests to make it more successful to equivocate rather than create an invalid message.

HWY-207: Fix the code to get rid of warnings about too late timestamps.

---

node/src/components/linear_chain.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

https://casperlabs.atlassian.net/browse/NDRS-667

NDRS-667: Keep finality signatures in memory if we don't have their block yet.

---

resources/maintainer_scripts/casper_node/casper-node.service

This is purely a .deb package change, but versioning for less confusion if we relaunch with 0.2.x release rather than 0.3.0.

Change from debug to info logging.

---

node/src/components/consensus/candidate_block.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/traits.rs

https://casperlabs.atlassian.net/browse/HWY-217
If consensus value is empty then consensus doesn't have to ask for its validation and add the vertex to the state immediately, saving some reactor events and processing.
It also simplifies tests since we can propose empty vectors without having to handle `ResolveValidity` requests.

HWY-217: Add `needs_validation` method to `ConsensusValueT`.

---

node/src/components/consensus/candidate_block.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/protocols/highway/tests.rs

https://casperlabs.atlassian.net/browse/HWY-195
This adds a test to `protocols::highway::tests` that creates and sends a valid unit. It's the first step to create a test of the fork spam defence mechanism (we discussed this with @xcthulhu and decided to first create such a simple test, and focus on testing the defence against fork spam only after this works).

HWY-195: Create and send a valid wire unit in tests

---

node/src/components/linear_chain.rs
node/src/testing/test_rng.rs
node/src/types/block.rs

This is another preparation for [NDRS-527](https://casperlabs.atlassian.net/browse/NDRS-527), where we'll need to determine the total weight that signed a switch block.

NO-TICKET: Make Block::proofs a map, keyed by public key.

---

node/src/components/event_stream_server/config.rs
node/src/components/event_stream_server/http_server.rs
node/src/components/event_stream_server/sse_server.rs
resources/local/config.toml
resources/production/config-example.toml

The SSE server now has an configurable parameter that determines the channel broadcast buffer size within the server itself. The default value is set to 100 and is present within both `config.toml` and `config-example.toml`

NDRS-680: Make SSE server channel buffer size configurable.

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/event.rs
node/src/components/block_proposer/tests.rs

This PR is a bugfix for https://casperlabs.atlassian.net/browse/NDRS-636 - with this we are now keeping note of deploys that we have not yet tracked for proposal, and checking them when we propose new deploys for a block.

NDRS-636 - handle untracked finalized deploys

---

client/lib/ffi.rs
client/lib/lib.rs
client/lib/rpc.rs
client/lib/validation.rs
client/src/get_era_info_by_switch_block.rs
client/src/main.rs
node/src/components/rpc_server/http_server.rs
node/src/components/rpc_server/rpcs/chain.rs
node/src/components/rpc_server/rpcs/chain/era_summary.rs
node/src/components/rpc_server/rpcs/docs.rs

Based on comments from @Fraser999 and discussion with @momipsl, this PR:
- updates the name of the rpc method to `chain_get_era_info_by_switch_block`, the library functions to `get_era_info_by_switch_block`, and the CLI command to `get-era-info-by-switch-block`
- updates the response struct to contain an optional struct rather than having it contain several optional fields.

NO-TICKET: update get-era-info endpoint

---

resources/maintainer_scripts/casper_node/casper-node.service

Now that RUST_LOG defaults to info, we are removing this explicit set in serviced unit.

Remove the RUST_LOG env from serviced file, relying on default behavior.

---

execution_engine/src/core/engine_state/error.rs
execution_engine/src/core/engine_state/execution_result.rs
execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/engine_state/transfer.rs
execution_engine/src/core/engine_state/upgrade.rs
execution_engine/src/core/execution/executor.rs
execution_engine/src/storage/protocol_data.rs
grpc/server/protobuf/casper/ipc.proto
grpc/server/src/engine_server/mappings/ipc/deploy_result.rs
grpc/server/src/engine_server/mappings/ipc/exec_config.rs
grpc/server/src/engine_server/mappings/ipc/upgrade_request.rs
grpc/test_support/src/internal/exec_with_return.rs
grpc/test_support/src/internal/mod.rs
grpc/test_support/src/internal/upgrade_request_builder.rs
grpc/test_support/src/internal/utils.rs
grpc/tests/src/profiling/state_initializer.rs
grpc/tests/src/test/deploy/receipts.rs
grpc/tests/src/test/system_contracts/genesis.rs
grpc/tests/src/test/wasmless_transfer.rs
node/src/components/chainspec_loader/chainspec.rs
node/src/components/chainspec_loader/config.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/production/validation.md5
resources/test/valid/chainspec.toml
types/src/proof_of_stake.rs
types/src/proof_of_stake/constants.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1122
- Wasmless transfer now has fixed price which pays to the proposer of the block i.e. payment and finialization code is simulated similar to normal deploys
- Added this cost to chainspec and internally this cost is part of the ProtocolData
- Upgrade support

EE-1122: Wasmless transfer gas cost

---

ci/casper_updater/src/main.rs
ci/casper_updater/src/package.rs

Needed when cutting release branch from higher versioned master.

[casper-updater] Adding --allow-earlier-version flag to revert version manually if needed

---

resources/maintainer_scripts/logrotate.d/casper-node

**maxsize** would only been considered if the system logrotate execution interval was lowered (default daily via /etc/cron.daily) to be less than the casper-node logrotate interval. 
```
maxsize size
Log files are rotated when they grow bigger than size bytes even before the additionally specified time interval ( daily, weekly, monthly, or yearly).
```
remove to avoid confusion. discussed in https://casperlabs.atlassian.net/browse/OP-1705

OP-1705 remove maxsize directive from logrotate config

---

node/src/components/gossiper/config.rs
node/src/components/small_network.rs
node/src/components/small_network/gossiped_address.rs
node/src/components/small_network/tests.rs
node/src/reactor/validator/tests.rs
node/src/testing/network.rs

It appears from examining debug log files that expired addresses are continually circulated around the remaining peers.  This has an avalanche effect in terms of network traffic, latency and the size of nodes' event queues.
The change in this PR should help avoid old gossiped addresses cycling around the network continually, but relies on keeping the config value `gossip.finished_entry_duration_secs` a reasonably low value (we're using 60 seconds as of now), and certainly it must be a significantly lower value than `gossip.gossip_interval` (we'll be using 5 mins as of now).  If not, then nodes will likely be unable to fully connect, as their attempts to gossip their address will be thwarted by peers' filters timing out at varying moments and partially or totally stalling the progress of …

NO-TICKET: avoid injecting unique ID into each fresh round of address gossiping

---

node/src/components/gossiper.rs

This PR should fix #700 although it only addresses the symptom reported there rather than the underlying cause.
By running a 20 node network via nctl and sending a large number of deploys, I was able to see memory usage on a small number of the nodes peak at over 3.3 GiB, with the network killed as a node exceeded 7 GiB.
Investigation of the logs from that node shows that the reactor of that node is choked with consensus and fetcher events in its queue allowing the following flow to occur:
1. a deploy was received and stored locally via gossip
2. the deploy was gossiped to 3 peers, causing the entry in the gossip table to be flagged as finished and adding 3 timeouts of 10 seconds to check that each peer had responded in a timely manner
3. the entry was purged from the gossip table ~60 …

NO-TICKET: remove unreachable calls from gossiper

---

node/src/components/block_proposer.rs
node/src/components/block_validator.rs
node/src/reactor.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/deploy.rs
node/src/utils/round_robin.rs

With this PR I started out trying to solve [NDRS-668](https://casperlabs.atlassian.net/browse/NDRS-668):
1. add a state machine to block_validator that loads the chainspec from storage (needed to validate deploys).
2. validate deploys against chainspec values
That _should_ have been it, but it turned out that `BlockValidator` was the source of many extra events on the queue:
The `BlockValidator` would always fetch all deploys when a `BlockValidationRequest` was received by it, regardless of if it has already validated it, or if there was a previous request in-flight for that block. This PR therefore also implements fetching the deploys for a block _if it has not been successfully validated in the past_. If it has been successfully validated, we can exit early, returning the validation to …

NDRS-668 - block validator - validate blocks similar to block_proposer

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
utils/nctl/sh/assets/setup_node.sh

This fixes two things:
- `has_received_messages` was implemented in an inverted way: it returned true if _no_ messages have been received. An alternative fix would be to change the name of the method, but since it is a trait method, it makes sense to keep it this way.
- PR #705 introduced a new config value which should be treated by `nctl` the same way the storage path is. A relevant line to the asset setup script is added.

NO-TICKET: Small fixes

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs

We panic if consensus doesn't receive any messages in 5 minutes. We currently judge this only by the Highway state - but we won't store anything in the state before we finish syncing the DAG, and this can take more than 5 minutes. Because of this, we should take vertices stored in the synchronizer cache into account as well (we received _them_, after all).

NO-TICKET: Take cached vertices into account

---

resources/maintainer_scripts/casper_node/casper-node.service
resources/maintainer_scripts/logrotate.d/casper-node

- seperate stderr logging as it outputs non-JSON stack traces (without redirection ends up in journald)
- logrotate applied to /var/log/casper/casper-node* (glob)

Op 1750 casper-node redirect stderr into casper-node.stderr.log

---

node/src/components/consensus/protocols/highway/round_success_meter.rs

Since this is hard-coded and it's reasonable to set any fault tolerance threshold up to 50%, let's make sure that fewer than 50% of the validators cannot force the others to increase their round length.

Don't slow down with fewer than 50% failed rounds.

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/config.rs
node/src/components/event_stream_server/http_server.rs
node/src/components/rest_server.rs
node/src/components/rest_server/config.rs
node/src/components/rest_server/http_server.rs
node/src/components/rpc_server.rs
node/src/components/rpc_server/config.rs
node/src/components/rpc_server/http_server.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/reactor/validator/error.rs
node/src/utils.rs
run-dev-tmux.sh
run-dev.sh

Completes [NDRS-698](https://casperlabs.atlassian.net/browse/NDRS-698).
Tagging @momipsl since this will be a new reason for nodes to fail to start in nctl: they need to be able to bind to not just the specified address for the small_network, but also the three addresses for the three HTTP servers.

NDRS-698: if any HTTP server fails to start, causes the node to stop

---

node/src/components/consensus/era_supervisor.rs

It may turn out that era supervisor receives a `Shutdown` event just when it has initialized fresh era in which there are no consensus messages yet.

NO-TICK: Fix conditional consensus shutdown.

---

node_macros/Cargo.toml

Relevant issue: [NDRS-696](https://casperlabs.atlassian.net/browse/NDRS-696).

NDRS-696: fix casper-node-macros build error

---

node/src/crypto/asymmetric_key.rs
node/src/crypto/asymmetric_key_ext.rs
node/src/crypto/error.rs
types/src/account.rs
types/src/crypto.rs
types/src/crypto/asymmetric_key.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-748
Now that we are trafficking in well-formed public keys, we no longer can use the "zero key" for the system account as we did in the olden days.  This PR introduces a `System` variant to the types in the `asymmetric_key` module to allow us to retain a proper identity for the system account which is unrelated to the key types for users.  The most important property of this variant is that it cannot be used to create signatures nor can signatures using this variant be verified.
This work paves the way for the upcoming removal of `AccountHash`.

NDRS-748: add System variant to {PublicKey,SecretKey,Signature}

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/event.rs
node/src/components/event_stream_server/sse_server.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

REF: https://casperlabs.atlassian.net/browse/NDRS-619
Removed the `FinalizedBlock` event from the event stream, "actual block" as mentioned in the description is already part of the event stream as the `BlockHeader`

NDRS-619: Remove FinalizedBlock Event from event stream

---

node/src/components/consensus/protocols/highway/round_success_meter.rs

This makes us a bit less eager to slow down, and a bit more eager to speed up, which is appropriate if we set the minimum round length to a reasonable value anyway.
https://casperlabs.atlassian.net/browse/HWY-229

HWY-229: Use the same numbers for adaptive round length as in the paper.

---

execution_engine/src/core/execution/executor.rs
execution_engine/src/core/runtime/mod.rs
smart_contracts/contracts/test/groups/src/main.rs
types/src/key.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-750
`Key::into_seed` is a vestige of our old "local state" implementation, now removed.  It is currently used in several places where `Key::into_hash` would suffice.  Recent additions to `Key` have rendered it ever more dubious, so this PR does the proverbial deed, liberating it from a confused existence.
(This also paves the way for removal of `AccountHash`)

NDRS-750: remove Key::into_seed

---

Makefile
docker_make.sh

Moving the `list` to after `all` to restore original non-argument `make` invocation.

NO-TICKET Restoring default make execution.

---

client/lib/deploy.rs
node/src/components/deploy_acceptor.rs
node/src/components/rpc_server/rpcs/account.rs
node/src/types.rs
node/src/types/deploy.rs

This PR improves the handling of deploy validation, in particular resulting in more helpful RPC responses when a client sends an unacceptable deploy.  Where currently the client simply receives a message stating `invalid deploy`, with these changes, responses will include details like:
```
invalid deploy: invalid chain name: expected casper-net-1, got casper-net-2
invalid deploy: 11 dependencies exceeds limit of 10
invalid deploy: time-to-live of 1day 1ms exceeds limit of 1day
```

NDRS-754: improve deploy validation error handling

---

node/src/components/small_network/error.rs
node/src/utils.rs

Improves the error reporting in case of DNS failures by ensuring that the failed lookup error includes the address in question.

NO-TICKET: Better reporting of DNS failures

---

node/src/components/network.rs

Tested this in a small local testnet, this lets me use DNS names in bind_address, public_address and known_addresses without issues here.

OP-1748: Support DNS resolution in new networking component

---

.drone.yml
ci/publish.sh
ci/publish_to_crates_io.sh
grpc/server/Cargo.toml

Adding cargo publish to .drone.yml and disabling non-tag workflows on tag.
Correcting grpc/server Cargo.toml to allow correct cargo publish
Adding explicit --token to publish.sh as it didn't honor cargo login in CI.
@Fraser999 Needed to use `--no-verify` with client publish.  Is this an issue?
Tested these changes in release-0.6.3 tagging and reworked until successful.
https://casperlabs.atlassian.net/browse/OP-1650

OP-1650 Enabling cargo publish to crates.io in CI

---

client/lib/deploy.rs
node/src/types/block.rs

This PR implements NDRS-735 - separate transfers and deploys in the block header.

NDRS-735 - separate deploys and transfers in BlockHeader

---

node/src/reactor.rs

This PR directs the queue dump debug mechanism to `/tmp` because, when `cwd` is not set to a writable directory, we simply crash. This also appends a timestamp on the filename.

NO TICKET - direct queues to dump to /tmp with timestamp

---

node/src/components/block_validator.rs
node/src/components/fetcher.rs
node/src/components/fetcher/event.rs
node/src/components/fetcher/tests.rs
node/src/components/linear_chain_sync/event.rs
node/src/effect.rs
node/src/effect/requests.rs

`LinearChainSync` component uses `FetchResult`'s `peer` but it was hardcoded to `NodeId` while the whole component operates with abstract type `I`. This is a vestigial element – everywhere else peer type is parameterized.

NDRS-761: Parameterize `FetchResult` with peer type.

---

node/src/components/block_validator.rs
node/src/components/fetcher.rs
node/src/components/fetcher/event.rs
node/src/components/fetcher/tests.rs
node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/event.rs
node/src/effect.rs
node/src/effect/requests.rs

Since `FetchResult` wasn't parameterized over peer type and `LinearChainSync` was working with `I`, it was not possible to ban `NodeId` type. Now that the missing piece of work is done (see #781), we can ban invalid nodes.
Based on (and blocked by) #781 .

NDRS-762: Ban peer that returns invalid data when syncing (vestigial).

---

node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/event.rs
node/src/components/linear_chain_sync/peers.rs
node/src/components/linear_chain_sync/state.rs
node/src/components/linear_chain_sync/traits.rs

Small clean-up of `lienar_chain_sync.rs` file:
* Extracts `ReactorEventT` trait to a file,
* Extracts `State` struct to a file.
* Wraps peer-related information with a `PeersState` struct and extracts it to a file.
* Adds `peer` to a `DeploysNotFound` result (follows the pattern of other results in the component).
* Adds `GetDeploysResult` enum variant to follow the pattern used when downloading blocks.

NDRS-763: Cleanup of `linear_chain_sync.rs` 

---

node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/peers.rs

https://casperlabs.atlassian.net/browse/NDRS-760
Track which peers we successfully have downloaded data from and prioritize them when we request the next piece of data.
Every 5 successful attempts we will try 1 new peer (which is not in the set of the successful peer). If it has the data, it will be added to the set.

NDRS-760: Track which peers had the data and prioritize them.

---

Makefile
resources/maintainer_scripts/casper_node/casper-node.service

Removed wasm build in Makefile.  Other changes were already done.
Added defaulting to new networking.

OP-1775 0.7.0 packaging updates.

---

node/src/components/linear_chain.rs
node/src/types/block.rs

https://casperlabs.atlassian.net/browse/NDRS-708
When running the network, we observed an unexpectedly high number of `FinalitySignature`s being gossiped. For a single `(block_hash, validator)` pair each peer was broadcasting hundreds of those messages (in a 5 node network). It turns out that the cause of this was the asynchronous nature of a `LinearChain` component communicating with itself. Between the time that a block was updated to include new proofs (finality signatures), another `FinalitySignature` message (for the same `(block_hash, validator)` pair) arrived and was recognized as new. It went through the same chain of `LinearChain::Event`s as the previous one: stored and gossiped eventually. The solution was to cache pending finality signatures (ones that are being validated and …

NDRS-708: Cache finality signatures.

---

node/src/effect.rs

This PR causes the node to panic if we load a corrupted state for the block-proposer. This is a short-term fix to prevent a node from starting in a bad state.

NO_TICKET - panic when block-proposer state is corrupted

---

client/examples/ffi/src/get_auction_info.c
client/examples/ffi/src/put_deploy.c
client/lib/ffi.rs
client/lib/lib.rs
client/lib/rpc.rs
client/src/block/get.rs
client/src/block/transfers.rs
client/src/common.rs
client/src/deploy/get.rs
client/src/deploy/list.rs
client/src/deploy/put.rs
client/src/deploy/send.rs
client/src/deploy/transfer.rs
client/src/docs.rs
client/src/get_auction_info.rs
client/src/get_balance.rs
client/src/get_era_info_by_switch_block.rs
client/src/get_state_hash.rs
client/src/query_state.rs
client/tests/integration_test.rs
types/src/json_pretty_printer.rs
types/src/lib.rs

This provides a `json_pretty_print()` function in casper-types which replaces large (over 100 char) strings with `x chars` where `x` is the number of chars in the field.
The client has been updated to use this function by default.  However, if the user specifies extra verbosity by passing the `-v` arg twice (i.e. `-vv` or `-v -v`) then the full hex-encoded bytes of all values will be shown, as they are currently.
Example output of a `put-deploy` request using `-v`:
```json
{
"id": 1,
"jsonrpc": "2.0",
"method": "account_put_deploy",
"params": {
"deploy": {
"approvals": [
{
"signature": "130 chars",
"signer": "01f60bce2bb1059c41910eac1e7ee6c3ef4c8fcc63a901eb9603c1524cadfb0c18"
}
],
"hash": "5c61b4096243a8bfe89f9337c60c8276a598dfdad94ccbb0eb9497bd614a0e14",
"header": {
"account": …
```

NDRS-785: abbreviate large string JSON fields

---

.drone.yml
node/src/components/block_validator.rs

I've added `data_size(skip)` annotation on `Loading` variant of the enum, mostly because we shouldn't be in the `Loading` state for long enough for this metric to be necessary but also because it is a pain to write an implementation of `DataSize`  for the `Event` enum.

NO-TICKET: Memory usage of `BlockValidator`

---

resources/production/README.md

Unless path is explicitly set an Error missing field path occurs.
https://casperlabs.atlassian.net/browse/OP-1727

remove misleading documentation re: default path

---

node/src/components/linear_chain_sync.rs
node/src/types/block.rs

https://casperlabs.atlassian.net/browse/NDRS-801
The bug was introduced in #760 , where wasmless transfers got separated from the deploys but this change was not propagated when constructing a `ProtoBlock`. Which lead to a consensus not requesting wasmless transfers when fetching dependencies and, in a result, executing an incomplete block (hence different post-state hash).

NDRS-801: Verify that the execution matches expected during sync.

---

execution_engine/src/core/engine_state/execution_result.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine/src/shared/gas.rs

There are some checks in the node (i.e. https://github.com/CasperLabs/casperlabs-node/blob/b992ae0f72fa7a5c72c101dca03e0271a5736481/node/src/components/block_proposer.rs#L454-L463) to avoid overflows so chances are bogus deploys with `gas_price == u64::max_value()` or similar won't reach EE but after merging #766 those are better to be matched rather than unwrap/expected.

NO-TICKET: Fix raw gas/motes conversions.

---

node/src/components/deploy_acceptor.rs
node/src/components/deploy_acceptor/event.rs
node/src/effect.rs

This commit improves UX so sending deploys from invalid account reports
different error than sending account that does not have minimum balance
required.
Testing done:
```
cargo run --bin casper-client -- transfer --node-address http://localhost:50101 --target-account 01cddd9ecbea7b8e2cec8ad2041bd2a8edb554fe737bb6053ab67eb04f40851911 --amount 1 --chain-name casper-example --secret-key ./resources/local/secret_keys/node-1.pem --payment-amount 1
cargo run --bin casper-client -- put-deploy --chain-name casper-example --node-address http://localhost:50101 --secret-key Foo_secret_key.pem --session-path ./target/wasm32-unknown-unknown/release/do_nothing.wasm  --payment-amount 5000000000
```
Result:
```
thread 'main' panicked at 'unable to put deploy ResponseIsError(Error { code: 32008, message: …
```

NDRS-809: Add "insufficient balance" variant

---

grpc/test_support/src/internal/deploy_item_builder.rs
grpc/tests/src/test/contract_api/account/authorized_keys.rs
node/src/types/deploy.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-805
- Node will correctly passes all public keys from deploy's approvals
- Old authorization tests were reviewed and compared against old CasperLabs/CasperLabs repo, and test cases were fixed where possible
- Added multisig test cases to ensure wasmless transfers are also respecting deploy thresholds

NDRS-805: Fix multisig

---

node/src/components/network.rs
node/src/components/network/tests.rs
node/src/components/small_network.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
resources/maintainer_scripts/casper_node/casper-node.service

This PR reverses the behaviour of which networking component is chosen by default: now libp2p is the default, and users need to set the env var `CASPER_ENABLE_LEGACY_NET` to enable the old `small_network` component.

NO-TICKET: enable libp2p component by default

---

node/src/app/cli.rs
node/src/components/chainspec_loader/chainspec.rs
node/src/components/fetcher.rs
node/src/components/linear_chain.rs
node/src/components/rest_server.rs
node/src/components/rpc_server.rs
node/src/components/storage.rs
node/src/config_migration.rs
node/src/data_migration.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/lib.rs
resources/test/valid/auction_install.wasm
resources/test/valid/mint.wasm
resources/test/valid/pos.wasm
resources/test/valid/standard_payment.wasm
resources/test/valid/upgrade.wasm

This PR lays the groundwork for adapting the casper-node to properly handle protocol upgrades.
The first commit adds new two new subcommands to the node: `migrate-config` and `migrate-data`.  The former will be run post-install to migrate any config changes.  The latter will be run by the casper-node-launcher just before running the node in normal mode to migrate stored data as required.
The second commit refactors storage to handle providing switch blocks by era ID.  This is required as part of the upgrade story as a newly-started node will need to be able to determine the current list of validators and their key weights.
However, this commit is also required as part of the task which @fizyk20 is currently working on, hence this PR only covers part of the changeset required to handle …

NDRS-797: Initial work on casper-node upgrades

---

execution_engine/src/core/runtime/scoped_instrumenter.rs

Due to being run on systems with a non-monotonically-increasing clock, the `drop` implementation of the `ScopedInstrumenter` was seen to panic on rare occasions.
This PR resolves that issue by using a checked subtraction.
It also appears to be the only instance of `elapsed() - ` in our codebase.

NO-TICKET: fix potential panic in ScopedInstrumenter::drop

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/tests/consensus_des_testing.rs
node/src/components/consensus/tests/queue.rs

This prevents the remaining validators from creating more and more units (increasing the protocol state size, and thus memory usage) while too many validators are offline to finalize anything. E.g. if there's a 34% fault tolerance threshold, we need more than 67% = 50% + 34% / 2 online for liveness, so if 33% or more are offline, the other validators will pause.
During a pause, instead of units, they gossip new `Ping` messages, so that others can keep track of who's still online. Once enough validators are back online again, they resume.
https://casperlabs.atlassian.net/browse/HWY-239

HWY-239: Pause if too much stake is offline

---

utils/nctl/activate
utils/nctl/sh/node/svc_systemd.sh
utils/nctl/sh/scenarios/sync_test.sh
utils/nctl/sh/utils/infra.sh
utils/nctl/sh/utils/queries.sh
utils/nctl/sh/views/utils.sh
utils/nctl/sh/views/view_chain_lfb.sh

https://casperlabs.atlassian.net/browse/NDRS-803
Adds an integration test that exercises a scenario where a new node is joining an already running network.
Test scenario:
1. Send a batch of Wasm transfers.
2. Send a batch of native transfers.
3. Take a note of the LFB hash.
4. Send a batch of Wasm transfers.
5. Send a batch of native transfers.
6. Start a new node and join the network using LFB hash from **3)**
7. Verify that eventually, the LFB hash on the new node matches the hash on one of the old nodes.
This PR also adds new nctl command `nctl-view-chain-lfb` which will query nodes for the hash of the last finalized block.
Note that this requires `nctl` set up (as described in the `nctl` directory) and that there's an already running network.
Example usage:
```shell
nctl-assets-setup …
```

NDRS-803: Add an integration test for a new node joining the network.

---

README.md
utils/nctl/docs/usage.md

This removes the last instances of `make build-system-contracts` from our docs.

NO-TICKET: update node readme

---

node/src/components/rpc_server/http_server.rs
node/src/components/rpc_server/rpcs.rs

This PR brings the JSON-RPC server more in line with [the error object as defined in the specs](https://www.jsonrpc.org/specification#error_object).
* -32601, "Method not found" is now handled correctly
* -32602, "Invalid params" is now handled correctly
* -32603, "Internal error" is not required
* our server error codes have been negated to fit the range -32000 to -32099
Due to shortcomings in a third-party crate, we're not able to distinguish between an error due to the request containing invalid JSON, or the request containing valid JSON, but not a valid JSON-RPC request.  As such our server returns -32700, "Parse error" for both cases.

NO-TICKET: update RPC server

---

node/src/components/network.rs
node/src/components/network/tests_bulk_gossip.rs

This replaces the yamux multiplexer in the libp2p network component with an mplex one.
This change was observed to significantly lower the memory usage of test network.
The PR also temporarily disables the `send_large_message_across_network` test while investigations proceed into its sporadic failure.

NO-TICKET: replace yamux with mplex

---

README.md

Removing the options for CLI config overrides, IIRC, @Fraser999 indicated that this is no longer possible with the node-launcher architecture.  Cleaned up some broken links to docs, and put nctl front and center for tooling to run a local network.

Cleaning up and simplifying

---

execution_engine/src/core/engine_state/error.rs
execution_engine/src/core/engine_state/execution_result.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine_testing/test_support/src/internal/mod.rs
execution_engine_testing/tests/src/test/regression/ee_1160.rs
execution_engine_testing/tests/src/test/regression/ee_1163.rs
execution_engine_testing/tests/src/test/regression/mod.rs
execution_engine_testing/tests/src/test/wasmless_transfer.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1163
- This PR will now use a precomputed finalization result for user errors (https://github.com/CasperLabs/casperlabs-node/blob/4ad2e250ac839c41c9761e1aaba3281b17e34bb2/execution_engine/src/core/engine_state/execution_result.rs#L254-L275) in native transfer instead of early exit with 0 cost.
- During refactor I noticed I used wrong field for charging cost of wasmless transfer
- I also verified other test correctness in the meantime by changing default gas price to >1 and corrected failing tests.

EE-1163: Native transfer error charge

---

client/build.rs
client/examples/ffi/CMakeLists.txt
client/examples/ffi/README.md

Ref: [NDRS-841](https://casperlabs.atlassian.net/browse/NDRS-841).
This PR makes bindgen generate the C header of our client FFI in the project's target folder rather than the client's source tree.  This allows `cargo publish` to function as expected.

NDRS-841: avoid generating the client ffi header in the source tree

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/types/timestamp.rs

This removes all `Timestamp::now()` calls from the synchronizer and adds a unit test that doesn't use the wall clock. The test purges vertices from all three queues, and in the process also exercises pushing and popping vertices, and enqueueing vertices with a future timestamp.
https://casperlabs.atlassian.net/browse/HWY-238

HWY-238: Highway synchronizer unit test

---

node/src/components/linear_chain.rs
node/src/components/storage.rs

As part of the work on NDRS-833 I've noticed that we don't store new finality signatures in the persistent storage. This PR fixes that problem.

NO-TICK: Store new finality signatures in the storage.

---

.drone.yml

Sets `CARGO_FLAGS=--release` for the cargo-test step.
https://casperlabs.atlassian.net/browse/OP-1807

OP-1807: adding CARGO_FLAGS to cargo-test

---

execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/engine_state/step.rs

This PR changes StepResult::PreconditionError and splits it into separate, more detailed variants that also holds the error instance.

NO-TICKET: More detailed preconditions.

---

node/src/components/storage.rs

LMDB is configured with `MAX_TRANSACTIONS = 1` but we tried to create second txn without dropping the first one.

NO-TICK: Reuse LMDB txn.

---

execution_engine_testing/tests/src/test/regression/eco_863.rs
execution_engine_testing/tests/src/test/regression/mod.rs

Ref: https://casperlabs.atlassian.net/browse/ECO-863
This PR validates that recent changes to the faucet contract preserved the existing behavior.

ECO-863: add faucet tests

---

node/src/components.rs
node/src/components/networking_metrics.rs
node/src/components/small_network.rs
node/src/components/small_network/error.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This adds generic networking metrics, counting queued message and requests for outgoing broadcasts, as well as direct messages.
Currently only implemented for `small_net` due to some time constraints, but the same structure should be used for the libp2p `networking` component. Having the same metrics on both will allow for some comparability.
These metrics should be especially useful when tweaking the chattiness of consensus.

NO-TICKET/networking metrics

---

Cargo.lock
node/src/components/chainspec_loader.rs
node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/fetcher/tests.rs
node/src/components/rest_server.rs
node/src/components/rpc_server.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/effect/requests.rs
node/src/reactor/initializer.rs
node/src/reactor/initializer2.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/chainspec/protocol_config.rs
node/src/types/status_feed.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-860
This PR provides the next upgrade activation point in the status endpoints.
Manual testing via nctl showed that the status endpoints showed correct values for the activation point (`null` at start, then a valid era ID, then an updated era ID).  Example output:
```json
{
"api_version": "1.0.0",
"chainspec_name": "casper-net-1",
"genesis_root_hash": "4ae2..e47d",
"peers": [
{
"node_id": "NodeId::P2p(A5Rc..k9qM)",
"address": "/ip4/127.0.0.1/tcp/49474"
},
{
"node_id": "NodeId::P2p(HzXd..yzFM)",
"address": "/ip4/127.0.0.1/tcp/49428"
},
{
"node_id": "NodeId::P2p(NCPU..Hsim)",
"address": "/ip4/127.0.0.1/tcp/49442"
},
{
"node_id": "NodeId::P2p(PBzu..AfgF)",
"address": "/ip4/127.0.0.1/tcp/49458"
}
],
"last_added_block_info": {
"hash": …
```

NDRS-860: include next upgrade activation point in status endpoints

---

node/src/components/consensus.rs
node/src/components/consensus/candidate_block.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/protocols/highway/tests.rs

Validity of a proto block depends on the timestamp. If there are two different candidate blocks (belonging to different units) with the same proto block, we must not apply the validity result to both.
https://casperlabs.atlassian.net/browse/HWY-249

HWY-249: Add the timestamp to `CandidateBlock`.

---

node/src/components/block_validator.rs

https://casperlabs.atlassian.net/browse/HWY-251
After this PR, if fetching a `Deploy` fails due to a timeout then `BlockValidator` will retry downloading a deploy from an alternative source.

HWY-251: BlockValidator accepts alternative sources of data.

---

node/src/components/consensus/candidate_block.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/traits.rs

Instead of storing the whole `ConsensusValue` as a key in the map (where `ConsensusValue` is a set of all deploys that the block includes), we will store a hash of `ConsensusValue`. This will improve memory management.
https://casperlabs.atlassian.net/browse/HWY-250

HWY-250: Use `ConsensusValue`'s hash as a key in map.

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs

We are seeing high memory usage in tests, due to pending vertices in the Highway synchronizer. Currently a new entry in a synchronizer queue is created whenever we receive a vertex that we can't add to the protocol state yet, e.g. due to missing dependencies. If we receive the same vertex multiple times, it will be duplicated in multiple queue entries.
This PR turns the queues into maps, keyed by the vertex and the sending peer, and when we receive a duplicate it only updates the timestamp of the existing entry instead of creating a duplicate.
https://casperlabs.atlassian.net/browse/HWY-246

HWY-246: Deduplicate synchronizer entries.

---

execution_engine/src/core/runtime/mod.rs

No functional changes here, just joticed that this check wasn't correctly factoring in access rights so that we weren't actually short-circuiting when transferring from a given source to itself.

NO-TICKET: fix short-circuit in Runtime::transfer_to_account

---

node/src/components/consensus/candidate_block.rs

I missed that when rebasing https://github.com/CasperLabs/casper-node/pull/879 on https://github.com/CasperLabs/casper-node/pull/881.

NO-TICKET: Use timestamp in candidate block hash.

---

node/src/components/network.rs
node/src/components/network/tests.rs
node/src/components/network/tests_bulk_gossip.rs
node/src/components/small_network.rs
node/src/components/small_network/tests.rs
node/src/reactor/initializer.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Make the `small_net` the default networking component.
In order to enable the libp2p-based version, one has to export `CASPER_ENABLE_LIBP2P_NET` variable.

NO-TICKET: Make the small_net a default networking layer.

---

node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/protocols/highway.rs

We don't count faulty validators towards the "online" ones anyway, so there's no point processing their pings.

NO-TICKET: Reject pings by faulty validators.

---

node/Cargo.toml
node/build.rs
node/src/app/cli.rs
node/src/lib.rs

When building from a repo where the git tags were not up to date, the version the node reported was highly misleading, using the latest git tag rather than the version specified in `Cargo.toml`.  This misleading version is used to populate the output when running the node with `-h` or `-V` and is also reported via the status endpoints.  However, when the node first starts, a further version is output which is based upon the value in `Cargo.toml`.
This PR ensures the proper crate version as specified in the `Cargo.toml` is used in all these cases.

NO-TICKET: generate node version consistently

---

node/src/components/consensus/metrics.rs
node/src/components/linear_chain.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Adds metrics for `time_of_last_finalized_block`, `block_completion_duration` and fixes an unregistered metric `time_of_last_proposed_block`. 
Talking with @EdHastingsCasperLabs `time_of_last_added_block` wasn't going to be meaningful, so we pivoted to instead record `block_completion_duration.`

NDRS-876 - track metric for last block time

---

client/src/account_address.rs
client/src/main.rs

REF: https://casperlabs.atlassian.net/browse/NDRS-837
CHANGELOG:
- Added a new sub-command called `account-address` with a single arg `--public-key` which takes a hex formatted public key or a path to a key and outputs the associated account-hash for the public key
Sample Output:

NDRS-837: Add account-address subcommand

---

node/src/types/chainspec/deploy_config.rs
node/src/types/deploy.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/production/validation.md5
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml

Ref: https://casperlabs.atlassian.net/browse/NDRS-851
This PR adds two configuration switches to a chainspec
```diff
+ [deploys]
+ payment_args_max_length = 1024
+ session_args_max_length = 1024
```
which makes deploy acceptor verify that both payment runtime args and session runtime args are not larger than the configured values.

NDRS-851: Enforce deploy's runtime args len.

---

execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/engine_state/upgrade.rs
execution_engine_testing/test_support/src/internal/upgrade_request_builder.rs
execution_engine_testing/tests/src/test/system_contracts/upgrade.rs
node/src/types/chainspec/protocol_config.rs
types/src/access_rights.rs
types/src/account.rs
types/src/bytesrepr/bytes.rs
types/src/key.rs
types/src/transfer.rs
types/src/uref.rs

https://casperlabs.atlassian.net/browse/NDRS-834
Currently there are no upgrade points per se - the chainspec as a whole is kind of an upgrade point. So maybe the `global_state_update` doesn't really belong in `ProtocolConfig` - could be an additional field in the chainspec itself, maybe? I'm open to moving it somewhere else.

NDRS-834: Extend upgrade points

---

node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/reactor/validator/tests.rs

In practice, with reasonably long eras, this won't make any difference, but in some tests with single-block eras we observed that everyone got evicted because they did not have a chance to create a unit before the last (and only) block.
This PR makes Highway only report a validator as inactive if there was enough time before the first and last block of an era for them to create a unit.

NO-TICKET: Don't evict validators if era was too short to produce a unit.

---

node/src/components/gossiper/gossip_table.rs

For some reason, we skipped measuring the memory allocation of `Timeouts` collections in the `GossipTable` struct.

NO-TICKET: Measure memory allocation by `Timeouts` collection.

---

node/src/components/network/config.rs

This PR changes two config settings to their default values as specified in the libp2p crate.

NO-TICKET: change libp2p config settings to their default values

---

execution_engine/src/core/engine_state/executable_deploy_item.rs
execution_engine/src/core/engine_state/mod.rs
node/src/types/chainspec/deploy_config.rs
node/src/types/deploy.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/production/validation.md5
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml

This PR adds a new deploy config chainspec parameter for a minimum transfer amount and logic to reject native transfer deploys with an amount less than the minimum. 
https://casperlabs.atlassian.net/browse/DEV-21
I defaulted the configured amount to the minimum balance required to exec deploys using an account; but the value can be tweaked if necessary.

DEV-21: enforce minimum native transfer amount

---

utils/nctl/sh/scenarios/sync_test.sh

This PR decreases the batch sizes of Wasm deploys and native transfers used in the `sync_test.sh`.
The main goal of the `sync_test.sh` is correctness, not performance, so the number of deploys in the network does not matter as long as that number is positive and we have a different type of deploys (native vs Wasm) both before and after the trusted hash.

NO-TICKET: Speed up sync/join integration test.

---

node/src/components/fetcher.rs
node/src/components/fetcher/metrics.rs
node/src/components/fetcher/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Adds three metrics do the fetcher:
* found_in_storage
* found_on_peer
* timeouts
Metrics are prefixed with the "type" of the fetcher:
* linear_chain
* deploy
* block_by_height.

NDRS-889: Add `Fetcher` metrics.

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/validators.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/participation.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/utils.rs

This adds a once-per-minute INFO-level log statement listing all faulty and inactive validators, and their total weight as a percentage. Example output:
`validator participation; participation=Participation { instance_id: 248c7d082e44ad352e10dcbdac6a442f2cb675d247d9732c276aefce1dddf5a6, faulty_stake_percent: 1, inactive_stake_percent: 0, validators: [(ValidatorIndex(1), PublicKey::Ed25519(2575b4c621544fa3dda5c06bd26eed6304ea10bc57aa4bef4af9d7483ae95115), Equivocated)] }; instance_id=248c..f5a6
`
https://casperlabs.atlassian.net/browse/NDRS-879

NDRS-879: Log active/inactive stake.

---

utils/nctl/sh/scenarios/sync_test.sh

On master there is now a minimum transfer amount for "native" transfers, configured in the chainspec (deploy section, native_transfer_minimum_motes), and defaulted to 2_500_000_000 motes;

NCTL: meet minimum native transfer amount

---

execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
types/src/auction.rs
types/src/auction/detail.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1171
This PR introduces an automatic undelegation of delegator funds when a validator fully unbonds their stakes.

EE-1171: Automatically undelegate delegators when a validator fully unbonds

---

.drone.yml
ci/build_update_package.sh
ci/upgrade_package_s3_storage.sh

This builds `bin.tar.gz` and `config.tar.gz`.
`config.tar.gz` includes `chainspec.toml`, `accounts.csv`, and `config-example.toml` from `/resources/production`.
`bin.tar.gz` includes `casper-node` built for Ubuntu 18.04 and `README.md` with repo link and github commit hash used to build, to allow other platforms to build casper-node from same code.
Upload script will place these artifacts at http://genesis.casperlabs.io/drone/[git-hash]/[protocol_version].  Where protocol_version is from `resources/production/chainspec.toml` with underscores replacing periods.  
These can be used in upgrade tests and one can be selected for network upgrade and moved into the correct location in the `genesis.casperlabs.io` S3 bucket.

OP-1820: Building upgrade package release candidates and staging on S3.

---

node/src/components/block_executor.rs
node/src/types/block.rs
types/src/protocol_version.rs
types/src/semver.rs

https://casperlabs.atlassian.net/browse/NDRS-898
NOTE: we still populate the header with the hardcoded version `1.0.0`. Once #918 is merged, I will create a follow-up PR that uses `BlockExecutor`'s protocol version when creating new blocks.

NDRS-898: Add `ProtocolVersion` to the block header.

---

utils/nctl/sh/scenarios/sync_test.sh

Previous change caused the synchronization function to always be true. Reverting back to how it originally was.

NO-TICK: set lfb hash back to original

---

Cargo.lock
client/Cargo.toml
client/tests/integration_test.rs
node/Cargo.toml

REF: https://casperlabs.atlassian.net/browse/NDRS-862
CHANGELOG:
- Refactored client integration tests to use `tempdir` for test file
- Removed `remove_dir` in `keygen` integration tests as it was outmoded due to use of `tempdir`
- Changed `rand-core` in `Cargo.toml` to account for a RUSTSEC advisory

NDRS-862: Client Intergration Tests using Tempdir

---

Cargo.lock
execution_engine/Cargo.toml
execution_engine/src/shared/stored_value.rs
execution_engine/src/storage/trie/mod.rs
execution_engine/src/storage/trie/tests.rs
types/src/key.rs

This PR fixes a bug whereby `Key::from_formatted_str()` doesn't handle parsing a `Key::EraInfo` variant.  It also adds check for that variant to existing tests and adds a couple of serialization round trip tests, one using `bincode` and the other using `serde_json`.

NO-TICKET: fix issue in Key::from_formatted_str

---

node/src/components/network.rs
node/src/components/network/error.rs
node/src/components/network/tests.rs
node/src/components/network/tests_bulk_gossip.rs
node/src/components/networking_metrics.rs
node/src/components/small_network.rs
node/src/components/small_network/error.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Adds the regular networking metrics to the networking component, except for `open_connections`.
Some things are left as `TODO`, as the work has already been done in another branch that is pending a merge in the future.

NDRS-878: Add networking metrics for `network` component

---

node/src/components/chainspec_loader.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-859
This PR changes the behaviour of the chainspec loader to look for the immediate next version of casper-node as per semver ordering as opposed to the maximum version.
This brings it in line with the launcher's behaviour, and allows for multiple future versions to be installed concurrently, letting the launcher walk up through the versions sequentially.

NDRS-859: use next semver version rather than max when looking for upgrades

---

.drone.yml
Cargo.lock
ci/upgrade_package_s3_storage.sh
client/Cargo.toml
execution_engine/Cargo.toml
execution_engine/src/lib.rs
execution_engine_testing/cargo_casper/Cargo.toml
execution_engine_testing/cargo_casper/src/common.rs
execution_engine_testing/cargo_casper/src/tests_package.rs
execution_engine_testing/test_support/Cargo.toml
execution_engine_testing/test_support/src/lib.rs
node/Cargo.toml
node/src/lib.rs
node_macros/Cargo.toml
node_macros/src/lib.rs
smart_contracts/contract/Cargo.toml
smart_contracts/contract/src/lib.rs
smart_contracts/contract_as/package-lock.json
smart_contracts/contract_as/package.json
types/Cargo.toml
types/src/lib.rs

Bringing master up to 0.9.0 from 0.7.0 to not confuse with cherry-pick versions for release-0.8.0

NO-TICK: Bump to 0.9.0

---

node/src/components/chainspec_loader.rs
node/src/components/fetcher/tests.rs
node/src/components/gossiper/tests.rs
node/src/components/storage.rs
node/src/components/storage/tests.rs
node/src/reactor/initializer.rs
node/src/reactor/initializer2.rs
node/src/types/block.rs
node/src/types/chainspec/protocol_config.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/production/validation.md5
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml

Ref: https://casperlabs.atlassian.net/browse/NDRS-895
This PR adds functionality which allows an upgrade chainspec to specify that the node should ignore all blocks created during and after a given era ID.
This will hopefully never be needed, but until our upgrades can handle starting mid-era, we can use this as a fallback mechanism.

NDRS-895: provide hard reset chainspec option

---

utils/nctl/activate
utils/nctl/sh/node/upgrade.sh

This PR adds a new nctl command `nctl-upgrade-protocol`. The command takes two arguments `version` and `era`. Version is expected to be in format `X_Y_Z`.
The command will create `version` directories in all `node-X` directories and copy required files (`casper-node` binary, chainspec and config files). Chainspec will only be updated with the new protocol version and `activation_point.era`. No other changes to the protocol are made.
We recognize that this code is not exactly up to `nctl` standards but the command is proving very useful when testing the node upgrades so we want to give it to people early while committing to improving the code as soon as possible.

NDRS-880: Add `nctl-upgrade-protocol` command.

---

node/src/components/chainspec_loader.rs

If the node was started in a valid state, it sometimes didn't transition past the initializer phase.

NO-TICKET: Fix bug in the chainspec_loader.

---

node/src/types/json_compatibility/auction_state.rs

This PR adds the inactive field to the JsonBids structure.
https://casperlabs.atlassian.net/browse/NDRS-915

NDRS-915: add inactive field to JsonBids

---

node/src/reactor.rs

Adds a metric `consumed_ram_bytes` for total ram consumed as reported by sys-info. This is useful to compare and contrast what value we get from internal memory metrics.

NO TICKET memory stat gathering from sys-info for consumed mem

---

node/src/components/consensus/era_supervisor.rs

For the first 90 days we only evict equivocating validators instead of slashing them.
https://casperlabs.atlassian.net/browse/NDRS-912

NDRS-912: Disable slashing.

---

node/src/components/consensus.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/rest_server.rs
node/src/components/rpc_server.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/types/status_feed.rs

This PR enhances the status endpoints by providing the public signing key of the node and the next round length if the node is a validator.  Example output:
```json
{
"api_version": "1.0.0",
"chainspec_name": "casper-net-1",
"starting_state_root_hash": "fd7b..0314",
"peers": [
{
"node_id": "NodeId::Tls(470b..d032)",
"address": "127.0.0.1:34554"
},
{
"node_id": "NodeId::Tls(606d..b959)",
"address": "127.0.0.1:34555"
},
{
"node_id": "NodeId::Tls(a0ef..4e84)",
"address": "127.0.0.1:34557"
},
{
"node_id": "NodeId::Tls(e85b..0726)",
"address": "127.0.0.1:34556"
}
],
"last_added_block_info": {
"hash": "4453a99848956ad0b81883c78e6434a58997e0532314b4125746a0ee7e7accb6",
"timestamp": "2021-02-19T00:28:12.672Z",
"era_id": 3,
"height": 39,
"state_root_hash": …
```

NO-TICKET: add public key and round length to status endpoint

---

node/src/testing/multi_stage_test_reactor/test_chain.rs

The test used to be flaky, but it just passed 60 times in a row for me, so the problem seems to be fixed.
https://casperlabs.atlassian.net/browse/NDRS-887

NDRS-887: Enable test_joiner again.

---

Cargo.lock
node/Cargo.toml
node/src/components/network.rs
node/src/components/network/behavior.rs
node/src/components/network/gossip.rs
node/src/components/network/one_way_messaging.rs
node/src/components/networking_metrics.rs
node/src/reactor/validator/memory_metrics.rs
node/src/utils.rs
node/src/utils/counting_channel.rs
node/src/utils/ds.rs
shell.nix
utils/nctl-metrics/gen_prometheus_config.py
utils/nctl-metrics/prometheus.sh

This PR rolls up a few things:
* Completes the memory metrics for the `networking` component, including adding a special counting channel that makes it possible to inspect queues.
* Adds debug-metrics to the libp2p component that track the number of futures created.
* Fixes a few bugs in metrics reporting (some still present) for memory in the validator.
* Improves/fixes the `nctl-utils` prometheus metrics setup.
Almost all changes are confined to `components::network`, thus should have little impact on production.

NO-TICKET/Improve libp2p network memory metrics

---

node/src/components/contract_runtime.rs

Increase the number of buckets for our `contract_runtime` histograms. The old value resulted in values being skewed to 320ms exactly. I'm leaving a note that the last bucket before a similar cutoff would occur at 10.24 seconds as a result of our math here. I tested this in my environment and the metric appears to be fixed.

NO TICKET increase number of buckets for contract_runtime metrics

---

client/lib/validation.rs
execution_engine/src/core/engine_state/balance.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/engine_state/transfer.rs
execution_engine/src/core/runtime/mint_internal.rs
execution_engine/src/core/runtime/mod.rs
execution_engine/src/core/runtime_context/mod.rs
execution_engine/src/core/tracking_copy/ext.rs
execution_engine/src/core/tracking_copy/mod.rs
execution_engine_testing/test_support/src/internal/wasm_test_builder.rs
execution_engine_testing/tests/src/test/contract_api/create_purse.rs
execution_engine_testing/tests/src/test/contract_api/transfer_purse_to_purse.rs
execution_engine_testing/tests/src/test/get_balance.rs
node/src/components/rpc_server/rpcs/state.rs
types/src/key.rs
types/src/system/mint/mod.rs
types/src/system/mint/storage_provider.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1168
This PR
- introduces a `Key::Balance` variant, under which balance values are stored.  These values are only readable and writable by host-side code.
- removes the various URefs used for indirection in the mint code.
- simplifies the structure of balance proofs now that the indirection is gone.

EE-1168: refactor Mint to remove use of named keys

---

node/src/components/contract_runtime.rs

NO TICKET: increase number of buckets for contract_runtime metrics

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/event.rs
node/src/components/event_stream_server/sse_server.rs
node/src/components/linear_chain.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

https://casperlabs.atlassian.net/browse/NDRS-913
https://github.com/CasperLabs/casper-node/pull/892 moved `deploy_hashes`, `transfer_hashes` and `proposer` from the `BlockHeader` structure to the new `BlockBody`. Up until now, we've been pushing only `BlockHeader` to the event stream, which means that since #892 got merged those three were missing from the event stream events. This PR changes what gets pushed to the event stream – we're now pushing the whole `Block`.
The main differences are in the structure of the event. Instead of `block_header` field containing `BlockHeader` structure, there's now a `block` field with `Block` struct. Structure of the `Block` can be found [here](https://github.com/CasperLabs/casper-node/blob/master/node/src/types/block.rs#L1023).

NDRS-913: Push whole block to the event stream.

---

node/src/types/chainspec/accounts_config.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-933
This PR makes `[[delegators]]` entries in `accounts.toml` optional.

NDRS-933: Make delegator entries optional.

---

.drone.yml

Turns on the publishing of `@casper/contract`
https://casperlabs.atlassian.net/browse/OP-1844

OP-1844: publish contract-as on tag

---

client/lib/deploy.rs

This PR directs output for the client functions `make_deploy()` and `sign_deploy()` to a [`std::io::Sink`](https://doc.rust-lang.org/std/io/fn.sink.html) rather than stdout when in test configuration.  This avoids cluttering the client test output.

NO-TICKET: clean up client test output

---

node/src/components/linear_chain_sync.rs

We used to mark syncing as done if none of the peers gave us any new block (successor of the latest block we downloaded). This proves to be problematic when we have many peers and they don't respond to us in time, before the next block is created. This way we end up being stuck in a syncing loop.
This PR considers newly downloaded block to be the tip of a chain if it was created less than 1 minute ago.

NDRS-940: Stop sync after very recent block.

---

node/src/components/linear_chain_sync.rs

@fizyk20 found a bug in my code where it would replace the `self.state` with `curr_state` from before `mark_done()`.
We return `Effects::new()` (no effects) to stop the syncing process and let the reactor progress from joiner to validator.

NDRS-940: Do not return any effects after sync done.

---

ci/nightly-test.sh

Disables the `sync_upgrade_test` integratoin test until the relevant PR in consensus is merged.

NDRS-880: Disable the test.

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/network.rs
node/src/components/small_network.rs
node/src/components/storage.rs
node/src/effect.rs

If the total weight of equivocators exceeds the configured fault tolerance threshold, consensus cannot continue and the node shuts down. This PR adds a delay for the shutdown so we can still broadcast evidence of the equivocations.
https://casperlabs.atlassian.net/browse/NDRS-939

NDRS-939: Add a delay before shutdown due to too many equivocations.

---

node/src/components/chainspec_loader.rs

The chainspec loader was doing an unnecessary base64 decoding when preparing an `UpgradeConfig` struct (it's already being done when parsing the chainspec) - this is removing it.

NDRS-897 fixup: fix conversion to EE format

---

execution_engine_testing/tests/src/test/regression/ee_1119.rs
execution_engine_testing/tests/src/test/regression/ee_1120.rs
execution_engine_testing/tests/src/test/step.rs
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
execution_engine_testing/tests/src/test/system_contracts/auction/distribute.rs
execution_engine_testing/tests/src/test/system_contracts/auction_bidding.rs
types/src/system/auction/bid/mod.rs
types/src/system/auction/mod.rs

This PR updates the auction module to disable fully-unstaked and slashed bids instead of removing them from the bids map. 
This precedes upcoming changes to how bids are persisted in the auction module.
~**NOTE**: This PR depends on #984.~ (MERGED) 
~**Actual diff here**: https://github.com/henrytill/casper-node/compare/EE-1178...henrytill:EE-1179~

EE-1179: deactivate bids instead of removing them

---

node/src/components/small_network.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Handshake cannot use the chainspec hash anymore since post-upgrade nodes
will be using different chainspec from the joining node (which hasn't
upgraded yet).

Backport the change to make handshake depend on network name.

---

node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/validators.rs
node/src/utils/ds.rs

Reduces heap measuring of large collections by sampling only a subset of their contents.

NDRS-857/sample memory metrics in consensus

---

execution_engine/src/core/engine_state/error.rs
execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine_testing/cargo_casper/src/tests_package.rs
execution_engine_testing/cargo_casper/tests/integration_tests.rs
execution_engine_testing/test_support/src/internal/mod.rs
execution_engine_testing/test_support/src/lib.rs
execution_engine_testing/test_support/src/test_context.rs
execution_engine_testing/tests/src/test/check_transfer_success.rs
execution_engine_testing/tests/src/test/regression/eco_863.rs
execution_engine_testing/tests/src/test/regression/ee_1045.rs
execution_engine_testing/tests/src/test/regression/ee_1103.rs
execution_engine_testing/tests/src/test/regression/ee_1119.rs
execution_engine_testing/tests/src/test/regression/ee_1120.rs
execution_engine_testing/tests/src/test/regression/ee_1129.rs
execution_engine_testing/tests/src/test/regression/ee_1152.rs
execution_engine_testing/tests/src/test/regression/ee_597.rs
execution_engine_testing/tests/src/test/regression/ee_598.rs
execution_engine_testing/tests/src/test/step.rs
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
execution_engine_testing/tests/src/test/system_contracts/auction_bidding.rs
execution_engine_testing/tests/src/test/system_contracts/genesis.rs
execution_engine_testing/tests/src/test/system_costs.rs
node/src/types/chainspec/accounts_config.rs
node/src/types/json_compatibility/auction_state.rs
types/src/system/auction/bid/mod.rs
types/src/system/auction/delegator.rs
types/src/system/auction/error.rs
types/src/system/auction/mod.rs
types/src/system/auction/seigniorage_recipient.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1138
Ref: https://casperlabs.atlassian.net/browse/EE-1172
This PR adds vesting schedule to genesis delegators which has similar behavior to vesting schedule of genesis validators. This PR also modifies genesis process which will create entries for each defined delegator in `accounts.toml`.

EE-1172: Delegators vesting schedule

---

node/src/components/small_network.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This PR reverts the recent relaxation of the network handshake process in order to allow v0.7.7 nodes to communicate with v0.7.6 nodes.

NO-TICKET: revert handshake change

---

execution_engine/src/core/tracking_copy/mod.rs
execution_engine/src/core/tracking_copy/tests.rs
execution_engine/src/storage/global_state/in_memory.rs
execution_engine/src/storage/global_state/lmdb.rs
execution_engine/src/storage/global_state/mod.rs
execution_engine/src/storage/trie_store/operations/mod.rs

This PR adds a `keys_with_prefix` method to `StateReader`.  
This is yet another move towards optimizing the way bids are stored in the auction.  It will be used to read all of the keys in the `Key::Bid` keyspace.

EE-1184: add StateReader::keys_with_prefix

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/evidence.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/highway_core/validators.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/tests.rs

All bonded eras are kept in memory because we still need to handle messages for them and detect equivocations.
However, since each era can refer to evidence from previous eras for cross-era slashing, even eras older than that are kept in memory, so that that evidence can be validated. This PR clears the protocol state of all unbonded eras and retains only evidence, to free up the memory. The dropped information is not needed anymore, since evidence cannot have any dependencies.
This should reduce consensus memory usage by almost 50%.
https://casperlabs.atlassian.net/browse/HWY-257

HWY-257: Clear the protocol state of unbonded eras.

---

.drone.yml
ci/build_update_package.sh

Switches from `upgrade_package_s3_storage.sh` wrapper script to drone s3 plugin.
Reconfigures build wrapper to output into a protocol dir. Borrowed this logic from the `upgrade_package_s3_storage.sh` wrapper.

OP-1853: fix upload to genesis s3

---

utils/nctl/sh/scenarios/sync_upgrade_test.sh

Instead of waiting 2 eras we can wait 1.

NO-TICKET: Wait a bit shorter after an upgrade.

---

execution_engine/src/core/tracking_copy/meter.rs
execution_engine/src/core/tracking_copy/mod.rs
execution_engine/src/core/tracking_copy/tests.rs
types/src/key.rs
types/src/lib.rs

This PR adds `get_keys` method to TrackingCopy which reads through the cache to `StateReader::keys_with_prefix`.
The caching behavior is marginally different than how we handle key-value pairs: cached writes must be unioned with reads rather than replace them.

EE-1185: add TrackingCopy::get_keys

---

node/src/components/small_network.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-927
This PR re-introduces the relaxation of the network handshake message.  However to ensure it is compatible with 0.7.6 nodes currently running (which require the handshake to provide the chainspec hash), the handshake message has been updated to hold the chainspec hash and the network name.
The change is required in order to support future potential upgrades to the delta network.  For example, a new user would need to run this version of the node to initially join an upgraded delta network, and so the node must be able to communicate with nodes at a newer protocol version.  This would not be possible if we used the chainspec hash to handshake as the protocol version difference would be reflected in the hash, and the nodes would refuse …

NDRS-927: support flexible handshake for delta and upgraded delta nodes

---

node/src/components/consensus.rs
node/src/components/consensus/config.rs
node/src/components/consensus/era_supervisor.rs
node/src/reactor/joiner.rs

Don't use the state root hash for computing new era's instance IDs anymore: It's unnecessary since the chainspec and era ID should make it unique, and it's not necessarily available at that point in the code.
(It is still important that all instance IDs are unique: If you participate with the same key in two different instances with the same ID, your messages could be combined to provide a valid proof of an equivocation.)
https://casperlabs.atlassian.net/browse/NDRS-945

NDRS-945: Compute instance IDs from chainspec hash and era ID.

---

node/src/components/gossiper.rs
node/src/components/gossiper/gossip_table.rs

This PR fixes an issue in the gossip table whereby gossip items could avoid being moved to the `finished` or `paused` state, hence leaving the item in the `current` state indefinitely, blocking any further attempts to handle gossip for that item.
We have a termination condition of knowing about `x` peers which hold the data in question, `x` being configurable and set to 15 currently.  We could reach this termination condition in a few different ways:
1. by receiving a response from a peer we gossiped the item to
2. by timing out a response we never got from a peer we gossiped the item to
3. by receiving the item as a gossip request from a peer
The issue is that we currently only move an item from `current` to `finished` or `paused` when handling situation 1.  Situation 2 was assumed to be …

NO-TICKET: fix issue in gossip table

---

node/src/reactor.rs
node/src/utils.rs
node/src/utils/rlimit.rs

To address issues with networks with > 400 connections, set the open files limit (`ulimit -n`) at the startup.
If this fails, settle for the closest possible maximum. This code will never panic or abort, but warn if the limit cannot be increased.

NDRS-899: Set ulimit

---

.drone.yml
node/src/components/consensus/era_supervisor.rs

The code accidentally cleaned up the current era instead of the old one.

NO-TICKET: Fix era cleanup.

---

ci/nightly-test.sh

`master` branch is now ready for this test. I have also disabled the regular `sync_test` as the upgrade version tests the superset of the functionality.

NO-TICKET: Enable the "sync over upgrades" IT test.

---

resources/production/accounts.toml
resources/production/chainspec.toml
resources/production/config-example.toml
resources/production/validation.md5

Setup accounts.toml for 4 genesis validating nodes and preloading bitgo's balance.
Changed finality_threshold_fraction to [1, 3] instead of [1, 10] to match the changes Andreas made to local.
Total supply: 10_000_000_000 . 000_000_000  CSPR
This will test first full release of the protocol version by CI.

Genesis setup for mainnet-release-test-1 network.

---

.drone.yml
Makefile
node/src/reactor/validator.rs

This PR removes a couple of `todo!`s which could allow a malformed or more likely malicious message to cause the node to panic.

NO-TICKET: avoid panicking on handling get responses

---

node/src/components/small_network.rs

Backport of https://github.com/CasperLabs/casper-node/pull/1041

NDRS-964: (backport to 0.8.0) Remove outdated assertion on failed bootstrap connection

---

ci/nightly-test.sh

Currently hangs. Tracked with https://casperlabs.atlassian.net/browse/NDRS-966

NO-TICK: Disable nightly itst02

---

node/src/components/small_network.rs

Backport of https://github.com/CasperLabs/casper-node/pull/1041

NDRS-964: (backport to 0.7.7) Remove outdated assertion on failed bootstrap connection

---

node/src/components/small_network.rs

The assertion in the code is causing crashes in the wild right now, as it is based on an otherwise harmless-if-failed assertion. It used to check for a double-deletion from a list of pending connections, but failing to remove the value should have no ill effects otherwise.
The code was built when we supported only a single initial node to connect to - either two nodes racing or a duplicate entry in the list of bootstrap are likely what could triggers this (although @sacherjj has not been able to reproduce the latter issue quickly).

NDRS-964: Remove outdated assertion on failed bootstrap connection

---

.drone.yml
Makefile
node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/state.rs

This PR adds two new conditions for when to stop syncing and transition to an active node:
1. When the most recently downloaded block was created less than the longest possible round ago.
2. When the last downloaded block was a switch block of a currently active era.

[Delta] NDRS-962: Stop syncing early.

---

node/src/components/consensus/era_supervisor.rs

This changes the logic for retrieving the validator set from the global state as discussed [here](https://github.com/CasperLabs/casper-node/pull/1023#discussion_r585640105).

NO-TICKET: Use the era's earliest block to get activation era validators.

---

node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/state.rs
node/src/types/chainspec/highway_config.rs
utils/nctl/sh/scenarios/sync_test.sh

https://casperlabs.atlassian.net/browse/NDRS-949
This PR adds two new stop conditions for when a node can consider being sync'd with the chain:
1. When a newly downloaded block has been created less than `max_round_length` ago. Works in situations when the network is running with the highest possible round exponent and otherwise there's a long list of known peers to ask for a new block.
2. When a newly downloaded block is a switch block of the currently active era. Works in situations when the finalization takes more than the longest possible round and condition **1** wouldn't kick in.

NDRS-962: Add more stop conditions for syncing.

---

node/src/types/chainspec.rs
node/src/types/chainspec/accounts_config.rs
node/src/types/chainspec/accounts_config/account_config.rs
node/src/types/chainspec/accounts_config/delegator_config.rs
node/src/types/chainspec/accounts_config/validator_config.rs
resources/test/valid/0_9_0_unordered/accounts.toml
resources/test/valid/0_9_0_unordered/chainspec.toml

Ref: https://casperlabs.atlassian.net/browse/NDRS-946
Changes the way AccountsConfig is deserialized so accounts and delegators are always sorted. Adds a test case that ensures that even with different accounts.toml both Chainspec objects are equal.

NDRS-946: Make sure Chainspec::hash is the same for everyone

---

execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/runtime/mod.rs
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
smart_contracts/contracts/test/auction-bids/src/main.rs
types/src/system/auction/constants.rs

`Auction::read_seigniorage_recipients` was not being used other than in tests.  Keeping it as a public auction entrypoint presents challenges for iterating on the `SeigniorageRecipient` structure and related.  This PR removes it as a public entrypoint to enable future changes.

EE-1190: remove entrypoint for read_seigniorage_recipients

---

.drone.yml
Makefile
node/src/components/chainspec_loader.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-927
This PR is a workaround for the lack of protocol version in block headers.  Currently, when we restart after an upgrade from the delta network where the upgrade was a hard-reset, the joining node will start with a cached/stored version > 1.0.0.  When the second binary is started, this causes it to attempt to call the EE `commit_upgrade` passing the same version for the current and new protocols.
To get round this, we simply ignore the cached/stored version when calling `commit_upgrade`.  Instead we use a hard-coded `1.0.0` for the current version and the one provided in the chainspec as the new version.  This will need extended if we end up running 0.8.0 nodes on delta in order to be able to upgrade from those.  Hopefully this will not …

NDRS-927: work around blocks not holding protocol version

---

types/src/system/auction/mod.rs
types/src/system/auction/seigniorage_recipient.rs

This PR replaces the `Delegator` values in the `SeigniorageRecipient` map with stake values, which are all that are necessary for users of this structure.

EE-1191: reduce footprint of SeigniorageRecipient

---

node/src/components/block_executor/metrics.rs
node/src/components/block_proposer/metrics.rs
node/src/components/consensus/metrics.rs
node/src/components/fetcher/metrics.rs
node/src/components/gossiper.rs
node/src/components/gossiper/metrics.rs
node/src/components/linear_chain.rs
node/src/components/networking_metrics.rs
node/src/reactor.rs
node/src/reactor/event_queue_metrics.rs
node/src/reactor/joiner.rs
node/src/reactor/joiner/memory_metrics.rs
node/src/reactor/validator/memory_metrics.rs
node/src/utils.rs

This PR fixes the gossiper metrics, some of which are fairly useless at the moment.
* `items_received` now correctly represents the total of all gossip items received, whether passed to the component by a client, by a different component (e.g. the small network in the case of starting a new round of gossiping its own address) or by a peer gossiping it.
* `items_gossiped_onwards` has been replaced by `times_gossiped` and now represents the total number of outbound gossip messages the node has sent.
It also standardises the unregistering of metrics from the Prometheus registry to remove the risky calls to `expect` in the `Drop` impls of many of the metrics structs.  If there are objections to the introduction of a macro to achieve this, I would be happy to change it back to normal function …

NO-TICKET: fix gossip metrics

---

node/src/components/chainspec_loader.rs
node/src/components/consensus.rs
node/src/components/consensus/config.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/tests/utils.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/reactor/validator/tests.rs
node/src/testing/multi_stage_test_reactor/test_chain.rs
node/src/types/chainspec.rs
node/src/types/chainspec/activation_point.rs
node/src/types/chainspec/network_config.rs
node/src/types/chainspec/parse_toml.rs
node/src/types/chainspec/protocol_config.rs
node/src/types/status_feed.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/production/validation.md5
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/0_9_0_unordered/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml
utils/casper-tool/casper-tool.py
utils/nctl/sh/assets/setup.sh

This PR unifies the genesis timestamp and upgrade activation point into a single enum type.
During a discussion with @EdHastingsCasperLabs, it was noted that genesis timestamps for all chainspecs after the genesis one become meaningless and could be omitted.  Conceptually, the genesis timestamp can be considered the activation point for the first version, hence it seems natural to absorb it into the activation point type.

NO-TICKET: change activation point to represent era ID or genesis timestamp

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/reactor/validator/tests.rs
node/src/testing/multi_stage_test_reactor/test_chain.rs

This changes the configuration used in the reactor tests so that the 5-era tests cause eras to become unbonded and dropped in the era validator.
This would have made the tests catch the bug fixed in https://github.com/CasperLabs/casper-node/pull/1038.
https://casperlabs.atlassian.net/browse/NDRS-955

NDRS-955: Make tests include unbonding and dropping eras.

---

node/src/components/chainspec_loader.rs
node/src/reactor/initializer.rs
node/src/types/block.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-963
This PR fixes an issue whereby a restarting node on a network which has upgraded would call the contract runtime's `commit_upgrade()` with an incorrect `current_version`.  Rather than storing the protocol version in storage and using that on restart, we now use the protocol version from the highest block now that it is available to us.
The PR also temporarily disables the trie store check as it is too slow to support as is.  It will be re-enabled in some form once a decision on how to address this issue permanently has been made.

NDRS-963: chainspec loader now gets the protocol version from the highest block

---

smart_contracts/contract_as/package-lock.json
smart_contracts/contract_as/package.json

upgraded typedoc to not-latetst version but dependency version (highlight.js) is no longer giving alert about EOL.
@mpapierski please check that this version generates proper documentation :)

typedoc upgrade to 0.19.1

---

execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
types/src/system/auction/delegator.rs
types/src/system/auction/mod.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1188
- Sets all delegator stakes to 0 for slashed validator
- Adds a test that ensures delegators of a validator have their stake set to 0 after slashing

EEE-1188: Restore delegator slashing

---

Cargo.lock
types/Cargo.toml
types/src/account.rs
types/src/bytesrepr.rs
types/src/cl_value.rs
types/src/semver.rs
types/src/system/auction/error.rs
types/src/system/handle_payment/error.rs
types/src/system/mint/error.rs
types/src/system/mod.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-974
Removes failure and uses optional thiserror for std case, and for no_std (i.e. wasm32 target) is hidden behind cfg_attr. This complication happens because thiserror does not support no_std upstream but a PR is pending https://github.com/dtolnay/thiserror/pull/64

NDRS-974: Get rid of failure

---

execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/runtime/auction_internal.rs
execution_engine/src/core/runtime/mod.rs
execution_engine/src/core/runtime_context/mod.rs
execution_engine/src/core/tracking_copy/byte_size.rs
execution_engine/src/core/tracking_copy/mod.rs
execution_engine/src/shared/stored_value.rs
execution_engine/src/shared/transform.rs
execution_engine_testing/test_support/src/internal/wasm_test_builder.rs
execution_engine_testing/tests/src/test/regression/ee_1119.rs
execution_engine_testing/tests/src/test/regression/ee_1120.rs
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
execution_engine_testing/tests/src/test/system_contracts/auction_bidding.rs
node/src/types/json_compatibility/stored_value.rs
types/src/execution_result.rs
types/src/gens.rs
types/src/key.rs
types/src/system/auction/constants.rs
types/src/system/auction/detail.rs
types/src/system/auction/mod.rs
types/src/system/auction/providers.rs
types/src/system/auction/unbonding_purse.rs

This PR removes the `UnbondingPurses` map stored under the auction's `UNBONDING_PURSES_KEY` named key and instead persists bids directly in the state trie under `Key::Withdraw` keys.

 EE-1192: store unbonds under Key::Withdraw

---

node/src/components/linear_chain.rs

This fixes rustfmt and removes some unnecessary `Event` variants.
(Found in preparation of [NDRS-892](https://casperlabs.atlassian.net/browse/NDRS-892).)

NO-TICKET: Simplify linear_chain.

---

node/src/crypto/asymmetric_key_ext.rs
node/src/utils.rs

This change ensures that private keys generated by the casper-client are only read/writeable by the owner. Since keys are commonly generated using root, they are protected against regular user access this way.
**Note**: The documentation needs to be updated to reflect this (keys need to be either generated as `casper` or `chown`ed).

NDRS-1000/Restrict private key permissions

---

node/src/components/linear_chain_fast_sync.rs
node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/event.rs
node/src/components/linear_chain_sync/traits.rs
node/src/reactor/joiner.rs

https://casperlabs.atlassian.net/browse/NDRS-1006
Instead of failing when we run out of peers before we manage to synchronize _any_ linear chain block, we will wait up to 5 minutes (same as in consensus). When we run out of peers, after we started syncing blocks, we will fail and exit. The behavior has been modified only for the "initial sync".
As part of the work in this PR, I've also removed some of the `panic!` calls from the `LinearChainSync` and replaced them with calls to `fatal!` macro that should allow the node to drop all components cleanly.

NDRS-1006: Add timeout-based sync failure.

---

node/src/components/linear_chain_fast_sync.rs
node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/event.rs
node/src/components/linear_chain_sync/traits.rs
node/src/reactor/joiner.rs

Backports https://github.com/CasperLabs/casper-node/pull/1091 to `release-0.9.2` branch.

[Delta] NDRS-1006: Do not fail sync if we run out of peers before we download anything.

---

.drone.yml
Cargo.lock
types/Cargo.toml

"hex" crate likely got updated as part of other batched deps update and `hex::encode` in newer version is hidden behind a feature switch. This PR fixes `cargo publish` failure that occurs in 
```
Compiling casper-types v0.9.0 (/drone/src/target/package/casper-types-0.9.0)
error[E0425]: cannot find function `encode` in crate `hex`
--> src/cl_value/jsonrepr.rs:58:30
|
58 |             Some((json![hex::encode(bytes)], remainder))
|                              ^^^^^^ not found in `hex`
```

NO-TICKET: Fix hex issue

---

node/src/components/deploy_acceptor.rs
node/src/components/fetcher.rs
node/src/components/gossiper.rs
node/src/components/gossiper/gossip_table.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/utils.rs

This PR adds debug-level logging to the gossiper component and the gossip table.
It also adds a new variant `Ourself` to the `Source` enum to account for cases where the current node generates gossip items, for example when gossiping its own public address.

NO-TICKET: improve gossiper logging

---

node/src/components/linear_chain.rs
node/src/components/linear_chain_sync.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Formatting in `linear_chain_sync.rs` was broken — if it can't fix it, `rustfmt` won't touch it —, there were Clippy warnings in that file, and `BlockAdded` had a redundant `block_hash` argument: Since the `Block` contains its hash and doesn't need to recompute it, this is not needed.
(Found while working on [NDRS-892](https://casperlabs.atlassian.net/browse/NDRS-892).)

NO-TICKET: Fix Clippy warnings, formatting and remove a redundant argument.

---

node/src/reactor.rs

PR fixes building casper-node on target osx by not setting constant TARGET_OPEN_FILES_LIMIT

NO-TICKET: Limit not in scope on osx

---

types/src/key.rs

This PR changes the serialized representation of `Key::EraInfo`, ensuring that this keys has a consistent length with the other key variants.  This is done for the sake of maintaining trie integrity.

EE-1196: pad serialized repr of Key::EraInfo

---

execution_engine/src/core/engine_state/error.rs
execution_engine/src/core/engine_state/execute_request.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine_testing/test_support/src/internal/execute_request_builder.rs
execution_engine_testing/tests/src/test/deploy/receipts.rs
node/src/components/block_executor.rs
node/src/components/block_executor/event.rs
node/src/effect.rs
node/src/effect/requests.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1131
This PR removes specialized "RootNotFound" struct-error which was moved into `engine_state::error::Error` as a separate variant.
Since RootNotFound is not a special case error anymore and now changed methods shares the same error type with other call sites there is still room for improvement in the error handling.

EE-1131: Get rid of RootNotFound

---

Cargo.lock
client/Cargo.toml

REF: https://casperlabs.atlassian.net/browse/NDRS-987
CHANGELOG: 
- Updated `cbindgen` build dependency in `casper-client` from `0.15` to the latest version `0.18`

Update cbindgen dependency

---

node/src/components/small_network.rs
node/src/components/small_network/message.rs

This PR effectively reverts [0dd0fdd](https://github.com/CasperLabs/casper-node/commit/0dd0fdd9ea87e88213821732857fba0dd2be3fe8) which created an issue whereby failed bootstrap connections would live forever in the small_network's `pending` set, meaning these bootstrap peers could never be connected to in that session.

NO-TICKET: remove failed bootstrap address from pending set

---

node/src/components/block_executor.rs
node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/event_stream_server.rs
node/src/components/event_stream_server/event.rs
node/src/components/linear_chain.rs
node/src/components/linear_chain_sync.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/effect/requests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This rewires events used during syncing so that they do not have to pass through the Era Supervisor anymore:
- removes `ConsensusRequest::HandleLinearBlock`
- removes `ConsensusAnnouncement::Handled`
- makes `LinearChainSync` progress on either `LinearChainAnnouncement::BlockAdded` or `BlockExecutorAnnouncement::BlockAlreadyExecuted` (a new announcement type)
- adds `ConsensusAnnouncement::CreatedFinalitySignature`, triggered by `LinearChainAnnouncement::BlockAdded` and replacing the response to `ConsensusRequest::HandleLinearBlock` for the purposes of collection of finality signatures.

NDRS-893: Make the syncing process not depend on the Era Supervisor

---

node/src/components/consensus/era_supervisor.rs

Backport of https://github.com/CasperLabs/casper-node/pull/1115.
https://casperlabs.atlassian.net/browse/NDRS-1010

NDRS-1010: Don't create a new era when we should shutdown for an upgrade. (backport to 0.9.3)

---

node/src/components/consensus/era_supervisor.rs

Backport of #1115.
https://casperlabs.atlassian.net/browse/NDRS-1010

NDRS-1010: Don't create a new era when we should shutdown for an upgrade. (backport to 0.9.2)

---

node/src/reactor/joiner/memory_metrics.rs

This PR fixes an omission to register the runtime memory metric in the joiner reactor.

NO-TICKET: register runtime memory estimator in joiner reactor

---

node/src/components/consensus/highway_core/active_validator.rs

When determining whether enough nodes are online, we can't use
```
(total_weight + target_ftt) / 2
```
because `total_weight` could already be close to `u64::MAX`.
https://casperlabs.atlassian.net/browse/HWY-267

HWY-267: Fix arithmetic overflow.

---

node/src/components/consensus/highway_core/active_validator.rs

When determining whether enough nodes are online, we can't use
```
(total_weight + target_ftt) / 2
```
because `total_weight` could already be close to `u64::MAX`.
https://casperlabs.atlassian.net/browse/HWY-267

HWY-267: Fix arithmetic overflow. (Backport to 0.9.2)

---

node/src/components/consensus/highway_core/active_validator.rs

When determining whether enough nodes are online, we can't use
```
(total_weight + target_ftt) / 2
```
because `total_weight` could already be close to `u64::MAX`.
https://casperlabs.atlassian.net/browse/HWY-267

HWY-267: Fix arithmetic overflow. (Backport to 0.9.3)

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/reactor/validator/tests.rs

This would have caught the overflow in HWY-267.
https://casperlabs.atlassian.net/browse/HWY-267

HWY-267: Use higher stakes in test to catch overflow issues.

---

node/src/effect.rs

Instead of crashing, quietly sweep a missing response under the rug. This will prevent us crashing on harmless drops, at the cost of potentially not crashing on an important one. Be extra vigilant for ERROR-level log entries.

NDRS-1003: do not panic on dropped responder

---

node/src/app/cli.rs
node/src/app/main.rs

This PR fixes an issue where the exit code returned by the validator reactor is ignored.
It also borrows code from #1070 which ensures all destructors are run before exiting `main`.

NO-TICKET: use actual exit code returned by validator reactor

---

node/src/reactor.rs
node/src/testing/network.rs

This PR does a little cleanup and fixes a few issues with `async` tracing instrumentation. It also adds an additional span around the runner initialization.
https://tracing.rs/tracing/struct.span#method.enter has some background information on why these changes were necessary.

NDRS-349/fix tracing issues

---

node/src/components/consensus.rs
node/src/components/consensus/config.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
resources/local/config.toml
resources/production/config-example.toml

Right before an upgrade it can happen that some nodes lag behind and, since the others restart, fail to find peers who complete their protocol state so they can see the switch block finalized. This change will make them restart after a while, so they can download the finalized executed blocks and then trigger the upgrade as well.
https://casperlabs.atlassian.net/browse/HWY-266

HWY-266: Shut down era supervisor in case it hasn't received any messages for the last era in a while

---

node/src/reactor.rs

This changes the behavior of memory metrics collection in the validator slightly. First, it removes the special casing for the `event_count == 0`, as `event_count % ANYTHING` should already cover this. Second, it simply subtracts the delay from the initial timestamp, if possible, to achieve the same effect.
A second change is that `last_metrics` is updated _after_ metrics collection; this skews the collection interval a bit but ensures that we are guaranteed to get `event_metrics_min_delay` time of uninterrupted (by memory metrics collection) event handling.

NDRS-811/cleanup memory usage dump in logs

---

Cargo.lock
execution_engine_testing/cargo_casper/Cargo.toml

This PR partially addresses the concerns raised by @sorpaas in #1136.
Specifically, it changes our code to use [colour](https://crates.io/crates/colour) at version 0.6 which is dual licensed under MIT and Apache 2.0.

NO-TICKET: update dependency to avoid using GPL license

---

.drone.yml

Path was incorrect in .drone.yml step breaking CI tag.

NO TICK: Correcting path to smart_contracts/contract_as.

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/linear_chain.rs
node/src/components/rpc_server.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This PR makes the Linear Chain check whether a validator is bonded with the Contract Runtime or the Storage, instead of the Era Supervisor. This way it will be able to function without an Era Supervisor present.

NDRS-892: Remove the dependency on the Era Supervisor from the Linear Chain

---

execution_engine/src/core/engine_state/genesis.rs
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1203
This PR validates `delegated_amount` of accounts.toml and disallows 0 as it's invalid.

EE-1203: Validate delegated amount

---

node/src/components/linear_chain.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This PR makes a couple of changes that optimize how finality signatures are being handled by the node:
* we gossip finality signatures created only by our node
* we validate the cryptographic signature at the end (as it's the most expensive test)
* validator reactor will inform `LinearChain` when a already-exected block is finalized, so that `LinearChain` can update its view about the tip of the chain and handle `IsBonded` queries properly.

NDRS-1028: Optimize handling of finality signatures in the linear chain component.

---

Cargo.lock
execution_engine/src/core/engine_state/genesis.rs
execution_engine_testing/tests/src/test/system_contracts/mod.rs
execution_engine_testing/tests/src/test/system_contracts/system_hashes.rs
smart_contracts/contract_as/assembly/index.ts
smart_contracts/contracts/test/system-hashes/Cargo.toml
smart_contracts/contracts/test/system-hashes/src/main.rs
types/src/system/mod.rs

Ref: https://casperlabs.atlassian.net/browse/EE-1134
Stripped down version of #1127 
This change introduces a fixed contract hashes only for system contracts without breaking any downstream users. Only genesis is affected.

EE-1134: Fixed addresses minimal

---

node/src/components/fetcher/tests.rs
node/src/components/gossiper/tests.rs
node/src/components/storage.rs
node/src/components/storage/tests.rs
node/src/reactor/initializer.rs
node/src/reactor/initializer2.rs

The idea behind hard-reset is to ignore blocks that might have been created in to-be-upgraded eras before an upgrade. If blocks were legitimately created after an upgrade, we shouldn't be trying to forget them. In order to differentiate the two situations, we'll check the protocol version - an old protocol version in the blocks will indicate that they are no longer valid and shouldn't be indexed. A current protocol version will indicate that they were created after the upgrade and thus can be safely re-indexed.

NO-TICKET: Only hard-reset blocks with old protocol versions

---

node/src/components/storage.rs
node/src/components/storage/tests.rs

This PR changes the behaviour of the storage component to avoid returning an error in the case where we overwrite execution results with a different value.  There is no requirement for repeated executions of a given deploy to produce identical output under all circumstances, hence the previous behaviour was incorrect.

NO-TICKET: avoid exiting if overwriting execution results with different ones

---

Cargo.lock
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
smart_contracts/contracts/client/activate-bid/Cargo.toml
smart_contracts/contracts/client/activate-bid/src/main.rs

This PR adds an `activate-bid` client contract, that:
* compiles to `activate_bid.wasm`,
* takes a single argument named `validator_public_key`,
* and must be deployed using the validator keys in question.
I replaced use of direct contract calls to `Auction::activate_bid` with calls to this contract in tests, so it has been confirmed to work.

EE-1204: add activate-bid client contract

---

node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs

https://casperlabs.atlassian.net/browse/HWY-271
Adds a new timer `TIMER_ID_SYNCHRONIZER_QUEUE` that is recreated every 5 seconds for every _unfinalized_ era. Upon handling the timer, lengths of synchronizer queues will be logged at the `debug` level. This is to aid in debugging the protocol state synchronization problems. Example:
```
{"timestamp":"Mar 19 00:00:18.685","level":"DEBUG","fields":{"message":"synchronizer queue lengths","era_id":"2c9fb42bf82a564db5ffde1f13dcce7c36ff9f66bf70b633f06ac083b2c022fa","vertices_to_be_added_later":0,"vertex_deps":0,"vertices_to_be_added":0},"target":"casper_node::components::consensus::protocols::highway::synchronizer"}
```

HWY-271: Log synchronizer queue size.

---

node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/highway_core/validators.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs

https://casperlabs.atlassian.net/browse/HWY-272
Adds logging of the oldest (lowest sequence number) unit seen per validator while syncing. Shows the progress of synchronization per validator.

HWY-272: Log oldest seen panorama when syncing.

---

node/src/components/consensus/highway_core.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/finality_detector.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/block.rs
node/src/components/consensus/highway_core/state/panorama.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/highway_core/state/tallies.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/highway_core/state/weight.rs
node/src/components/consensus/highway_core/test_macros.rs
node/src/types/timestamp.rs

This enables the warnings for all arithmetic operations in `highway_core` that could potentially overflow. It also replaces them with safe (e.g. saturating) operations in some places.
https://casperlabs.atlassian.net/browse/HWY-268

HWY-268: Enable integer_arithmetic Clippy warnings to prevent overflows.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/unit.rs
node/src/components/consensus/highway_core/test_macros.rs
node/src/components/consensus/protocols/highway.rs

We haven't seen any unexpected panics from these `unwrap`s/`expect`s, but it's still better to avoid them where possible, or thoroughly document them.
https://casperlabs.atlassian.net/browse/HWY-270

HWY-270: Remove or document more expect/unwrap calls.

---

.drone.yml

This adds the new repo steps for test packages. Right now it will go to my test repo but I will switch it over to prod once I confirm it works as expected.

OP-1913: testing new repo

---

node/src/components/deploy_acceptor.rs
node/src/utils.rs

This PR fixes an issue introduced when the `Source` enum was extended to hold a third variant.  Account verification of deploys should only be performed when receiving a deploy from a client.

NO-TICKET: fix issue for deploy validation in deploy acceptor

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/protocols/highway.rs

This adds INFO-level logs for receiving and validating proposed blocks, and whenever we send a witness unit in a round where we didn't receive a block.

NO-TICKET: Add more logging to track block proposals.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/protocols/highway.rs

This adds INFO-level logs for receiving and validating proposed blocks, and whenever we send a witness unit in a round where we didn't receive a block.
Backport of #1191 to 0.9.5.

NO-TICKET: Add more logging to track block proposals. (Backport to 0.9.5)

---

ci/nightly-test.sh

Disables itst14, passing locally but stalls in ci, tracking here: https://casperlabs.atlassian.net/browse/OP-1932
Pushes era back 1 (default is 3) in test to allow ci to pass. See: https://casperlabs.atlassian.net/browse/OP-1932

NO-TICK: nctl nightly bugs

---

node/src/components/linear_chain.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

https://casperlabs.atlassian.net/browse/NDRS-1031
NDRS-1028: Optimize handling of finality signatures in the linear chain component. r=goral09 a=goral09
This PR makes a couple of changes that optimize how finality signatures are being handled by the node:
* We gossip finality signatures created only by our node
* We validate the cryptographic signature at the end (as it's the most expensive test)
* validator reactor will inform `LinearChain` when an already-exected block is finalized so that `LinearChain` can update its view about the tip of the chain and handle `IsBonded` queries properly.

NDRS-1031: Port back NDRS-1028 to `dev` branch.

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/era_supervisor/era_id.rs
node/src/components/consensus/highway_core.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/participation.rs
node/src/components/consensus/protocols/highway/round_success_meter.rs
node/src/components/consensus/protocols/highway/round_success_meter/config.rs
node/src/types/timestamp.rs
node/src/utils.rs

This enables the warnings for all arithmetic operations in `consensus` that could potentially overflow. It also replaces them with safe (e.g. saturating) operations in some places.
https://casperlabs.atlassian.net/browse/HWY-268

HWY-268: Enable integer_arithmetic lints in the whole consensus component.

---

node/src/components/consensus/highway_core/highway/vertex.rs
node/src/components/consensus/highway_core/validators.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs

Ports PRs that add additional logging to the Highway synchronizer.
https://github.com/CasperLabs/casper-node/pull/1172
https://github.com/CasperLabs/casper-node/pull/1173

HWY-{271,272}: Port additional synchronizer logging to `dev` branch.

---

node/src/components/block_validator.rs
node/src/types/deploy.rs

This PR adds validation for the size of a block (as defined by the sum of `ToBytes::serialized_length()` of it's deploys) to the `BlockValidator`. Also included is a stop-gap fix for the `DeployAcceptor` to ensure no deploy can be larger than the allowed `max_block_size` in the chainspec.
Ref: https://casperlabs.atlassian.net/browse/NDRS-1013

NDRS-1013 validate block size in BlockValidator

---

node/src/components/consensus/protocols/highway.rs

https://casperlabs.atlassian.net/browse/HWY-273
Adds a cache for pending prevalidated vertices (vertices that are currently being synchronized) and for every new vertex received, checks if it's already in that cache. If not, don't request it again.
Also, checks the node's protocol state if the incoming vertex is already known before trying to validate it.

HWY-273: Add cache for prevalidated vertices.

---

execution_engine/src/storage/trie/mod.rs
execution_engine/src/storage/trie_store/operations/mod.rs
execution_engine/src/storage/trie_store/operations/tests/delete.rs
execution_engine/src/storage/trie_store/operations/tests/mod.rs
types/src/gens.rs

This PR introduces a `delete` operation to the trie, along with tests validating its behavior.  Future work will surface this through the `TrackingCopy` up to the Contract API.

EE-{1197,1198}: add initial trie delete

---

ci/nightly-test.sh

This is a quick fix which seems to work in my test forks drone setup.

OP-1934: reorder the tests to help with non-determinism

---

node/src/components/linear_chain_sync.rs
node/src/types/block.rs

https://casperlabs.atlassian.net/browse/NDRS-1051
https://casperlabs.atlassian.net/browse/NDRS-1050
`LinearChainSync` does no longer consider `State::None` as a trigger for finishing syncing.
When downloading linear chain blocks by height, we compare the block's protocol version with the version this node is running with.

NDRS-{1050,1051}: Delta-11 fixes.

---

node/src/components/consensus.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/validators.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/config.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/reactor/validator.rs
resources/local/config.toml
resources/production/config-example.toml

https://casperlabs.atlassian.net/browse/HWY-274
Tested locally with `nctl`:
```mateusz@mateusz-XPS-15-9560:~/work/casperlabs/casper-node$ nctl-view-chain-era node=1
2021-03-23T13:42:55.083255 [INFO] [164287] NCTL :: chain era @ node-1 = 11
mateusz@mateusz-XPS-15-9560:~/work/casperlabs/casper-node$ nctl-view-chain-lfb node=1
2021-03-23T13:42:57.995937 [INFO] [164287] NCTL :: last finalized block hash @ node-1 = afa3941cf566bb5fe0bc7552e9d53ecce74152029cbdc48534d41a540904ee07
mateusz@mateusz-XPS-15-9560:~/work/casperlabs/casper-node$ nctl-start node=7 hash=afa3941cf566bb5fe0bc7552e9d53ecce74152029cbdc48534d41a540904ee07
2021-03-23T13:43:04.890631 [INFO] [164287] NCTL :: node-7: starting ...
2021-03-23T13:43:04.896021 [INFO] [164287] NCTL :: trusted hash = …
```

HWY-274: Request protocol state only for the latest era.

---

node/src/components/chainspec_loader.rs
node/src/components/linear_chain_fast_sync.rs
node/src/components/linear_chain_sync.rs
node/src/reactor/joiner.rs

All components use `LinearChainSync`'s last known block as an initial state. In the case when there's was syncing performed they failed to initialize properly. We need to return the highest block when there's no synchronization.

NDRS-1051: Use highest block as an init state for components when no syncing is performed.

---

node/src/components/block_proposer.rs

It was possible that handling an old finalized block would rewind the `next_finalized` value. This PR removes that possibility.

NO-TICKET: Bugfix for Block Proposer

---

node/src/components/block_proposer.rs

It was possible that handling an old finalized block would rewind the next_finalized value. This PR removes that possibility.

NO-TICKET: Bugfix for Block Proposer (dev)

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/deploy_sets.rs
node/src/components/block_proposer/event.rs
node/src/components/storage.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/types/block.rs

Instead of persisting the `BlockProposerDeploySets` to LMDB and loading in on startup, we recreate that state from the collection of finalized deploys.
This fixes a bug where that set would be incorrectly initialized for joining/restarting/upgrading nodes.

NDRS-1052: Reconstruct `BlockProposerDeploySets` state from the block storage.

---

execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/runtime_context/mod.rs
execution_engine_testing/test_support/src/internal/mod.rs
execution_engine_testing/test_support/src/internal/wasm_test_builder.rs
execution_engine_testing/tests/src/test/contract_api/mint_purse.rs
execution_engine_testing/tests/src/test/regression/ee_1045.rs
execution_engine_testing/tests/src/test/regression/ee_1103.rs
execution_engine_testing/tests/src/test/regression/ee_1119.rs
execution_engine_testing/tests/src/test/regression/ee_1120.rs
execution_engine_testing/tests/src/test/regression/ee_1152.rs
execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
execution_engine_testing/tests/src/test/system_contracts/auction/distribute.rs
execution_engine_testing/tests/src/test/system_contracts/auction_bidding.rs
execution_engine_testing/tests/src/test/system_contracts/genesis.rs
execution_engine_testing/tests/src/test/system_contracts/handle_payment/finalize_payment.rs
types/src/system/auction/constants.rs
types/src/system/auction/detail.rs
types/src/system/auction/mod.rs
types/src/system/handle_payment/mod.rs
types/src/system/mint/mod.rs

This change will change the `AccountHash` bytes of the system account to:
```
blake2b(b"system0")
```
(as defined by `AccountHash::from_public_key`)

EE-1207: make definition of system account AccountHash consistent

---

node/src/components/block_proposer.rs
node/src/components/consensus.rs
node/src/components/consensus/candidate_block.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/components/consensus/traits.rs
node/src/types/block.rs

With deploy replay protection the validity of a candidate block depends not only on its contents and its timestamp, but also on its ancestors. So if there are two different vertices with identical consensus values, i.e. candidate blocks, one of them could be valid and one invalid. Whether a node would consider them valid would depend on which one was received first, because that would determine the set of ancestors we check against.
Adding the parent hash makes candidate block ancestors explicit so that consensus can rely on the validity result again: If a candidate block is deemed valid, we know that all vertices that carry it are valid.
https://casperlabs.atlassian.net/browse/NDRS-1053

NDRS-1053: Add a parent to CandidateBlock.

---

node/src/components/chainspec_loader.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/linear_chain.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/reactor/validator.rs

`get_era_validators` currently takes `activation_era_id`, `initial_state_root_hash` and `protocol_version` as arguments. All these values could, and should, be taken directly from the Chainspec Loader via a new request (or a set of new requests), so that the components calling `get_era_validators` won't have to store them.
https://casperlabs.atlassian.net/browse/NDRS-1025

NDRS-1025: Make get_era_validators take parameters directly from ChainspecLoader

---

node/src/components/chainspec_loader.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1043.
This PR changes the trigger for the chainspec loader to check for the next installed version of the chainspec.  The current trigger is the announcement of a new block; with this PR it is on a repeating minute timer.
With this being on a regular timed interval now, an upgrade will be detected even if block production has stalled.
I don't believe we need the interval to be a config setting, but if reviewers disagree, that can be changed.
I have tested this works via the `nctl-upgrade-protocol` command.

NDRS-1043: change trigger for upgrade checks to timed interval

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/deploy_sets.rs
node/src/components/block_proposer/event.rs
node/src/components/block_validator.rs
node/src/components/consensus.rs
node/src/components/consensus/candidate_block.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/highway_core/highway_testing.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/components/consensus/traits.rs
node/src/components/storage.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/types/block.rs

This is a port of https://github.com/CasperLabs/casper-node/pull/1216, https://github.com/CasperLabs/casper-node/pull/1218, https://github.com/CasperLabs/casper-node/pull/1219, https://github.com/CasperLabs/casper-node/pull/1223 to the `dev` branch.
* Instead of persisting the `BlockProposerDeploySets` to LMDB and loading in on startup, we recreate that state from the collection of finalized deploys. This fixes a bug where that set would be incorrectly initialized for joining/restarting/upgrading nodes.
* Blocks are considered invalid if they contain the same deploy twice, or if they contain a deploy that was already present in any of their ancestors.
https://casperlabs.atlassian.net/browse/NDRS-1052
https://casperlabs.atlassian.net/browse/NDRS-1053

NDRS-{1052,1053}: Prevent deploy replays. (Ports #1216, #1218, #1219, #1223 to dev.)

---

node/src/components/block_proposer/tests.rs
node/src/components/block_validator.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/contract_runtime.rs
node/src/effect.rs
node/src/types.rs
node/src/types/block.rs

The goal is to remove the `BlockLike` trait; this change limits its use to `block_validator` as a first step.
https://casperlabs.atlassian.net/browse/NDRS-1061

NDRS-1061: Move BlockLike into block_validator.

---

node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/highway/vertex.rs

While not as important as for other vertex types, it's still better to distinguish pings by instance ID, so that they are only handled in the era and the network they were meant for.
https://casperlabs.atlassian.net/browse/HWY-278

HWY-278: Add an instance ID to Pings.

---

node/src/components/linear_chain.rs

- Fixes the block_completion_duration metric

NDRS-1104: Emitting Event::PutBlockResult after putting execution results to storage

---

ci/nightly-test.sh
utils/nctl/sh/scenarios/accounts_toml/bond_its.accounts.toml
utils/nctl/sh/scenarios/bond_its.sh

CHANGELOG:
- Updated the `bond_its.accounts.toml` file to help improve the consistency of the test 
- Added a timeout inside the scenario to timeout incase of failure

OP-1951: NCTL - new bonds test hanging Fix

---

node/src/components/linear_chain.rs
node/src/components/linear_chain/event.rs
node/src/components/linear_chain/metrics.rs
node/src/components/linear_chain/signature.rs
node/src/components/linear_chain/signature_cache.rs
node/src/components/linear_chain/state.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

This PR moves some `struct`s from the `linear_chain.rs` file to separate files. No functional changes.
I recommend reviewing this commit-by-commit.

NDRS-833: Clean up the `LinearChain` component.

---

node/src/components/consensus/tests/utils.rs
node/src/types/chainspec.rs

This PR:
- changes `new_test_chainspec` to look for chainspecs in `local` rather than `test/valid/0_9_0`
- ignores two existing tests that check disparate versions of the chainspec.
**NOTE**: This second change is only meant to unblock us at the current juncture.  We should address how we intend to fix/replace these tests.

NO-TICKET: fix new_test_chainspec, ignore chainspec tests

---

node/src/components/small_network.rs
node/src/components/small_network/error.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/chainspec/network_config.rs
node/src/types/chainspec/parse_toml.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/0_9_0_unordered/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml
utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in

This ensures that nodes are in agreement about what the maximum message size is through the chainspec.

NO-TICKET: Limit message size in chainspec

---

Cargo.lock
node/Cargo.toml
node/src/components/small_network.rs
node/src/components/small_network/chain_info.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/chainspec.rs

This introduces a protocol version field into the handshake, which is ignored by the V1.0.0 node. At the same time, if absent, V1.0.0 is filled in. As a result, every version of the release node software has a correct protocol version field.
~~**NOTE** This PR is due a rebase & force push once https://github.com/CasperLabs/casper-node/pull/1256 is merged to master.~~

NO-TICKET: Include chainspec version in handshake

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/event.rs
node/src/components/block_proposer/tests.rs
node/src/components/block_validator.rs
node/src/components/consensus/candidate_block.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/contract_runtime.rs
node/src/reactor/validator.rs
node/src/types/block.rs

This is a refactoring, and a preparation for simplifying the block types, specifically for replacing `ProtoBlock` and `CandidateBlock` with a single type.
This PR removes `ProtoBlock` from `FinalizedBlock`, because the new type will contain fields (`accusations`) that would be redundant as a part of `FinalizedBlock`. It also renames `ProtoBlock::wasm_deploys` to `deploy_hashes`, and `transfers` to `transfer_hashes`, so that it is in line with `BlockBody`.
https://casperlabs.atlassian.net/browse/NDRS-1061

NDRS-1061: Remove ProtoBlock from FinalizedBlock and rename wasm_deploys.

---

node/src/components/linear_chain.rs
node/src/components/linear_chain/pending_signatures.rs
node/src/components/linear_chain/signature.rs
node/src/components/linear_chain/signature_cache.rs
node/src/components/linear_chain/state.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/block.rs

Cleanup of the `LinearChain` component (in preparation for unit tests) continued. The main thing that changed in this PR is the addition of `LinearChainComponent` struct that wraps `LinearChain` and `LinearChainMetrics`. All component-level logic is now moved to the `LinearChainComponent` struct, rather than `LinearChain`. The latter does not deal with `Effect`, `REv`, `EffectBuilder`, `I` (peer id type), or any other code related to the reactor or networking. The functionality should be mostly unchanged. I tried working iteratively so reviewing commit-by-commit should be simpler than trying to do it all at once (although not necessarily take less time). I've found a couple of inconsistencies and potential sources of bugs around the handling of pending/cached finality signatures. Those …

NDRS-833: `LinearChain` cleanup part 3.

---

node/src/components/storage.rs
node/src/components/storage/tests.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1076.
In a hard reset, blocks created in or after the specified era are deleted from storage, but associated data is left behind.  Associated data includes block bodies, block signatures and crucially deploy execution results associated with the deleted blocks.
This PR resolves that issue by removing the above mentioned associated data on a hard reset.

NDRS-1076: on hard reset of storage, remove all data associated with a removed block

---

node/src/components/storage.rs
node/src/components/storage/tests.rs
node/src/effect.rs
node/src/effect/requests.rs

This is the first part of changes for compatibility with Fast Sync.
https://casperlabs.atlassian.net/browse/NDRS-1026

NDRS-1026: Make get_era_validators use only block headers instead of full blocks

---

node/src/components/linear_chain.rs
node/src/components/linear_chain/state.rs

This is the last PR in the "clean up `linear_chain` for tests" series. 
In this PR all the logic of the linear chain component that needs to access (and modify) the state of the component is moved to methods on the `LinearChain` state that are called `handle_*`. Each of these methods returns `Outcome(s)` that "describe" the type of effect we want to create. This allows for writing unit tests that exercise the high-level API of the `LinearChain` state without involving effects, futures, etc.

NDRS-833: Refactor `LinearChain` to return outcomes not effects.

---

client/src/deploy/creation_common.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1122
This PR updates the client by making the default time-to-live for a deploy 30 minutes.

NDRS-1122: reduce default deploy TTL to 30 minutes

---

Cargo.lock
node/Cargo.toml
node/src/components/small_network.rs
node/src/components/small_network/chain_info.rs
node/src/components/small_network/error.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/types/chainspec.rs
node/src/types/chainspec/network_config.rs
node/src/types/chainspec/parse_toml.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/0_9_0_unordered/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml
shell.nix
utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in

This backports two 1.1.0 changes to `dev`, with the necessary alterations: https://github.com/CasperLabs/casper-node/pull/1256 (making the maximum message size depend on the chainspec instead of being hardcoded) https://github.com/CasperLabs/casper-node/pull/1263 (include the chainspec version in the handshake)
It also introduces the first set of rountrip tests that are ensuring we can serialize/deserialize network messages from 1.0.0 and onwards.

NDRS-1117: Backport handshake

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/tests.rs
node/src/components/block_validator.rs
node/src/types.rs
node/src/types/appendable_block.rs

This adds the `AppendableBlock` type, which checks block validity when adding deploys and transfers, and uses that type both for proposing and validating blocks, to make sure the same criteria are applied in both cases.
https://casperlabs.atlassian.net/browse/NDRS-1121

NDRS-1121: Deduplicate block validity criteria.

---

node/src/reactor.rs

I was wondering about the "large event size" warnings in the tests, so I added more logging. Turns out the event itself is test-only, but it's still better to log the event type:
```
WARN  [c:reactor :448] large event size, consider reducing it or boxing; event_size=328; type_name="casper_node::components::gossiper::tests::Event"
```

NO-TICKET: Log the event type if it is too large.

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/config.rs
node/src/components/block_proposer/deploy_sets.rs
node/src/components/block_proposer/tests.rs
node/src/lib.rs
node/src/reactor/validator.rs
node/src/reactor/validator/config.rs
node/src/types/timestamp.rs
resources/local/config.toml
resources/production/config-example.toml

This adds a configurable delay between the time we receive a deploy (from a client or another full node) and the time we propose it in a block. The intention is to give deploys time to spread across the network via gossip, so that when we include them in a new block, the other nodes won't all have to ask us for the deploy.
https://casperlabs.atlassian.net/browse/NDRS-1120

NDRS-1120: Add a delay before proposing dependencies.

---

node/src/components/linear_chain/state.rs

First PR, out of n, that adds tests to the `LinearChain` high-level API.

NDRS-833: Unit test handling incoming finality signatures.

---

node/src/components/small_network.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1113.
This PR fixes a bug where a node which is a member of the known addresses can become isolated but not retry to connect to other known addresses.
It also improves the logging of an outgoing connection failure in two ways:
1. A lost outgoing connection where the peer ID is known is now only logged once
2. The log messages for peer ID known vs unknown are now even more different to help disambiguate them.

NDRS-1113: fix reconnecting if isolated

---

client/tests/integration_test.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway/participation.rs
node/src/components/linear_chain.rs
node/src/components/small_network.rs
node/src/types/timestamp.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1126.
This PR removes `impl Sub<Timestamp> for Timestamp` as it made it somewhat easy to create code which could potentially panic in non-obvious edge cases.

NDRS-1126: remove impl Sub for Timestamp

---

utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in
utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in
utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in

Changes:
- Bug: Removes `timestamp` from `[network]` section of itst13 chainspec 
- Syncs other testing chainspecs with new `maximum_net_message_size`
Both introduced here: https://github.com/CasperLabs/casper-node/commit/8572d2946e9c0f40936a6a73920ef5c540da1fa6

NO-TICK: nctl bug fix

---

Cargo.lock
client/Cargo.toml
execution_engine/Cargo.toml
execution_engine/src/lib.rs
execution_engine_testing/cargo_casper/Cargo.toml
execution_engine_testing/cargo_casper/src/common.rs
execution_engine_testing/cargo_casper/src/tests_package.rs
execution_engine_testing/test_support/Cargo.toml
execution_engine_testing/test_support/src/lib.rs
node/Cargo.toml
node/src/components/rpc_server/rpcs/docs.rs
node/src/lib.rs
node_macros/Cargo.toml
node_macros/src/lib.rs
resources/production/chainspec.toml
smart_contracts/contract/Cargo.toml
smart_contracts/contract/src/lib.rs
smart_contracts/contract_as/package-lock.json
smart_contracts/contract_as/package.json
types/Cargo.toml
types/src/lib.rs

Era 359 is around 2021-04-30T13:00:00Z and expected activation time for casper network.

Update version to 1.1.0 and chainspec.toml for upgrade.

---

node/src/reactor.rs
node/src/utils/round_robin.rs

This prevents fatal errors from being skipped by clearing the `Control` queue and looking for datal events before successfully exiting.

NDRS-1049: Drain reactor queue switch

---

node/src/components/small_network.rs
node/src/components/small_network/error.rs
node/src/logging.rs

This PR introduces the `display_error` function, which causes errors to be properly **lazily** formatted when logging errors.
Currently, in our codebase, we often log errors like this:
```rust
match result {
Error(err) {
warn!(%err, "something happened');
}
// ...
}
```
This has the drawback of swallowing the errors causes, which are often more interesting than the potentially wrapping error itself.
This can now be addressed by using the `display_error` function:
```rust
match result {
Error(ref err) {
warn!(err=display_error(err), "something happened');
}
// ...
}
```
Which will cause the error to be output as "error: cause1: cause 2" instead.
Ideally this would be handled using `tracing`'s built-in functionality, but the implementation is lagging behind/buggy; the `display_error` …

NDRS-1116: display full cause chain when logging errors

---

execution_engine/src/core/engine_state/mod.rs
execution_engine_testing/test_support/src/internal/wasm_test_builder.rs
execution_engine_testing/tests/src/test/get_balance.rs

REF: https://casperlabs.atlassian.net/browse/EE-1213
CHANGELOG:
- Added a new function `EngineState::get_balance` which uses a `PublicKey` and returns a `BalanceResult`
- Added a new function `get_public_key_balance_result` to the WASM test builder to help with testing
- Added `get_balance_using_public_key_should_work` unit test

EE-1213: Added get_balance using PublicKey

---

execution_engine/src/core/engine_state/genesis.rs
execution_engine/src/core/runtime/mod.rs
execution_engine/src/core/runtime/standard_payment_internal.rs
execution_engine/src/shared/system_config/handle_payment_costs.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/0_9_0_unordered/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml
smart_contracts/contracts/client/named-purse-payment/src/main.rs
smart_contracts/contracts/test/ee-549-regression/src/main.rs
smart_contracts/contracts/test/ee-601-regression/src/main.rs
smart_contracts/contracts/test/finalize-payment/src/main.rs
smart_contracts/contracts/test/get-payment-purse/src/main.rs
smart_contracts/contracts/test/get-phase-payment/src/main.rs
smart_contracts/contracts/test/refund-purse/src/main.rs
smart_contracts/contracts/test/test-payment-stored/src/main.rs
types/src/system/handle_payment/constants.rs
types/src/system/handle_payment/mod.rs
utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in
utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in
utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in

Ref: https://casperlabs.atlassian.net/browse/EE-1223
Removes `get_refund_purse` entry point altogether as we were returning an `URef` there without access rights which could pose a security risk.

EE-1223: Remove get refund purse

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/config.rs
resources/local/config.toml
resources/production/config-example.toml

Ref: https://casperlabs.atlassian.net/browse/NDRS-1086.
This PR removes `broadcast_channel_size` from the SSE config, instead making the value a factor (120%) of the `event_stream_buffer_length`.
We always want the broadcast channel size to be greater than the event stream buffer length so that a new client can retrieve the entire set of buffered events if desired.
@sacherjj @momipsl note that this PR changes the config.toml.

NDRS-1086: change SSE broadcast channel size to be a factor of event stream buffer size

---

node/src/components/consensus/era_supervisor.rs
node/src/effect.rs

Fast sync will not execute all the deploys that were included in the past blocks, so we can't rely on execution results to detect replays.
https://casperlabs.atlassian.net/browse/NDRS-1088

NDRS-1088: Change replay detection to not use execution results

---

types/src/system/mint/mod.rs

CHANGELOG:
- Added a checked in `Mint::transfer` that checks the `Read` access for the source of the transfer and returns an `InvalidAccessRights` error should the check fail

EE-1220: Add Read check in Mint::transfer

---

utils/nctl/sh/assets/compile_client.sh
utils/nctl/sh/utils/constants.sh

After #1282 got merged in bypassing bors CI, it introduced a regression in nightly builds. This PR fixes the references to absent contracts in nctl scripts.

NO-TICKET: Fix nightly build

---

node/src/types/chainspec.rs
node/src/types/chainspec/activation_point.rs
node/src/types/chainspec/parse_toml.rs
node/src/types/chainspec/protocol_config.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml
types/src/era_id.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1073.
This PR introduces a field `last_emergency_restart` to the chainspec for use by fast sync.
Fast sync needs to ensure it doesn't traverse an emergency restart.  Since this information is not recorded anywhere on-chain, we need to provide it via the chainspec.

NDRS-1073: add last_emergency_restart field to chainspec

---

node/src/components/block_validator.rs
node/src/components/block_validator/tests.rs
node/src/components/consensus.rs
node/src/components/consensus/cl_context.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/traits.rs
node/src/components/linear_chain_fast_sync.rs
node/src/components/linear_chain_fast_sync/traits.rs
node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/traits.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
node/src/reactor/validator/memory_metrics.rs

This replaces the `BlockLike` trait with an enum that is used only within the block validator, and adds checks that the `transfer_hashes` contain only transfers, and the `deploy_hashes` contain none.
**Renames the metric `mem_block_payload_validator` to `mem_block_validator`!**
https://casperlabs.atlassian.net/browse/NDRS-1130

NDRS-1130: Remove BlockLike; verify deploy type in block validator.

---

node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs

https://casperlabs.atlassian.net/browse/HWY-282
Prior to the addition of [new logic](https://github.com/goral09/casper-node-1/blob/hwy-282/node/src/components/consensus/protocols/highway/synchronizer.rs#L373) we would try downloading a dependency (`c1`) that is already in the synchronizer's state. Now, instead, we will follow the vertices we already have and what those depend on and request the "lowest" one.

HWY-282: Do not request dependency that is already in the synchronizer queue.

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/tests.rs
node/src/components/block_validator.rs
node/src/types.rs
node/src/types/appendable_block.rs

This adds the `AppendableBlock` type, which checks block validity when adding deploys and transfers, and uses that type both for proposing and validating blocks, to make sure the same criteria are applied in both cases.
Backport of https://github.com/CasperLabs/casper-node/pull/1276.
https://casperlabs.atlassian.net/browse/NDRS-1121

NDRS-1121: Deduplicate block validity criteria. (1.0.2 backport)

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/effect.rs
node/src/reactor/validator.rs
node/src/types/block.rs

Fast sync won't download all block bodies, so in preparation, the consensus component needs to not rely on them.
https://casperlabs.atlassian.net/browse/NDRS-1142

NDRS-1142: Use only block headers, not bodies, in the consensus component.

---

node/Cargo.toml
node/src/components/small_network.rs
node/src/components/small_network/message_pack_format.rs

This pins the message pack version to the one used in 1.0.0

NDRS-1173: Fix message pack formatter to rmp-serde 0.14

---

node/src/components/linear_chain/state.rs

https://casperlabs.atlassian.net/browse/NDRS-1186

NDRS-1186: Fix a bug where finality signatures received after storing a block were not gossiped or stored.

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/deploy_sets.rs
node/src/components/block_proposer/tests.rs
node/src/components/consensus/era_supervisor.rs

This removes some code left over from when the block proposer state used to be persisted. It also fixes an issue in the era supervisor where `next_block_height` could _decrease_ (only temporarily, though), and increases log levels for the messages related to the block proposer queues.
(Related to [NDRS-1175](https://casperlabs.atlassian.net/browse/NDRS-1175).)

NDRS-1175: Minor fixes in block proposer and era supervisor.

---

node/src/components/block_proposer.rs
node/src/components/linear_chain_sync.rs
node/src/reactor/joiner.rs

Fixes a bug where a restarted node might end up with an incorrectly seeded block proposer.
https://casperlabs.atlassian.net/browse/NDRS-1175

NDRS-1175: Make sure that validator has access to the correct latest block

---

node/src/components/networking_metrics.rs
node/src/components/small_network.rs
node/src/components/small_network/counting_format.rs
node/src/utils.rs

This fixes a race condition where new metrics were being replaced before the networking component had shut down completely, resulting in a panic. As a fix `small_network` now drops its own strong reference first and waits for any stragglers.

NDRS-1188: Metrics race condition cleanup

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/highway.rs

* Don't activate old eras on initialization: When the era supervisor starts, the validator should only actively participate in the latest era.
* Delete the unit hash file only once the era becomes obsolete.
https://casperlabs.atlassian.net/browse/NDRS-1190

NDRS-1190: Make sure an era is not activated twice without a unit hash file.

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/sse_server.rs
node/src/components/rpc_server/rpcs/chain.rs
node/src/types/block.rs

Ref: https://casperlabs.atlassian.net/browse/DEV-50
This PR changes the block reported in the node's event stream to match that returned by the JSON-RPC server for consistency.
Closes #1334

DEV-50: use consistent json format for block representation

---

node/src/components/block_proposer.rs
node/src/components/consensus/highway_core/active_validator.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state/params.rs
node/src/components/consensus/traits.rs

* Log who missed their slot as a leader.
* List the individual steps of the rewards calculation: Which block got which quorum and who got rewards.
* Log when the block proposer queues a request due to the `next_finalized` value.
https://casperlabs.atlassian.net/browse/NDRS-1159

NDRS-1159: Add more consensus and block proposer log messages. 

---

node/src/components/consensus/highway_core/highway_testing.rs

When we introduced the `TemporarilyMute` variant, we accidentally made `PermanentlyMute` validators not mute at all! This re-enables simulation of permanently mute validators (i.e. offline/crashed nodes) in the Highway DES tests.

NO-TICKET: Fix liveness_test_some_mute.

---

node/src/components/storage/tests.rs

https://casperlabs.atlassian.net/browse/NDRS-1197
Fixes random block generators used in the storage tests so that they don't lead to flaky tests.

NDRS-1197: Fix flaky storage tests.

---

node/src/components/chainspec_loader.rs
node/src/effect.rs

https://casperlabs.atlassian.net/browse/NDRS-1079
This boils down to using the last emergency restart instead of the last activation point in the `get_era_validators` effect, and that is provided by the chainspec loader.

NDRS-1079: Era Supervisor Needs to Account For Last Emergency Restart

---

node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/round_success_meter.rs

Initializing it with the era start time makes it likely to unnecessarily slow down after downtime, because it will count all rounds since the era's beginning as "failed".
https://casperlabs.atlassian.net/browse/HWY-283

HWY-283: Initialize round success meter with current timestamp.

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/small_network.rs
node/src/types/timestamp.rs

That way we can't use the potentially underflowing `timestamp - timediff` in production anymore, and have to use `timestamp.saturating_sub(timediff)`. A panic in production would be unlikely, since the result of the subtraction would have to be before 1970, but it's better to err on the side of caution. The problem did show up in a unit test that used timestamps close to 0 (i.e. beginning of 1970).
https://casperlabs.atlassian.net/browse/HWY-286

HWY-286: Make unchecked timestamp subtraction test-only.

---

execution_engine_testing/tests/src/test/system_contracts/upgrade.rs
types/src/protocol_version.rs

This PR removes the strict expectation that minor and patch versions must always increase by 1, per @Fraser999 
https://casperlabs.atlassian.net/browse/NDRS-1172

NDRS-1172: relax minor and patch protocol version validity check

---

client/lib/deploy.rs
client/lib/error.rs
client/lib/ffi.rs
client/lib/lib.rs
client/lib/rpc.rs
node/src/types.rs
node/src/types/chainspec/deploy_config.rs
node/src/types/deploy.rs
resources/local/chainspec.toml.in
resources/production/chainspec.toml
resources/test/valid/0_9_0/chainspec.toml
resources/test/valid/0_9_0_unordered/chainspec.toml
resources/test/valid/1_0_0/chainspec.toml
utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in

This PR is a port of #1258 which limits the deploy size, both when accepting one in the node, and when creating one in the client.

NDRS-1167: limit deploy size to 1MiB

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/config.rs
node/src/components/consensus/protocols/highway/tests.rs
resources/local/config.toml
resources/production/config-example.toml

This adds a config option for logging the size of every incoming and outgoing unit, and an INFO-level log message for when finality is detected.
https://casperlabs.atlassian.net/browse/RES-419

RES-419: Add more logging for Highway units and finality.

---

execution_engine/src/core/engine_state/mod.rs
execution_engine/src/core/engine_state/step.rs
node/src/components/contract_runtime.rs
node/src/components/event_stream_server.rs
node/src/components/event_stream_server/event.rs
node/src/components/event_stream_server/sse_server.rs
node/src/effect.rs
node/src/effect/announcements.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

REF: https://casperlabs.atlassian.net/browse/NDRS-1114
CHANGELOG:
- Added a new `ContractRuntimeAnnouncement` that raises an event when a step has been committed
- Added a new SSE Event that puts the committed `ExecutionEffect` to the event stream
- Additional wire up to generate this event
Sample output attached
[ndrs1114.txt](https://github.com/casper-network/casper-node/files/6379671/ndrs1114.txt)

NDRS-1114: Step Information should be present on the event stream

---

.drone.yml
node/src/components/contract_runtime.rs
node/src/components/linear_chain_sync/error.rs
node/src/components/linear_chain_sync/operations.rs
node/src/components/storage.rs
node/src/effect.rs
node/src/effect/requests.rs

When retrieving a block header, we need to store them in storage.  This is because the `EraSupervisor` will use them later when determining era validators.

NDRS-1179: Store block headers on retrieval

---

utils/nctl/sh/scenarios/itst02.sh

Removes problemsome check between two remaining live nodes from test.
Adds additional logging on successful stall.
NOTES: 
Per the discussion in the huddle, we are fine checking that both the 2 two live node's LFBs do not progress. This check already exists at line 83.

OP-2031: NCTL itst02 bug fix

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs

Once all Highway dependencies are resolved, the synchronizer forgets about a proposed block and gives it to `HighwayProtocol` for inclusion into the protocol state. However, nonempty blocks are not immediately added: They are kept in the `pending_values` map while the block validator is downloading the deploys and checking the block limits. During that period, the synchronizer will request the same block again, if any dependent unit is added.
This PR should fix both the redundant requests for the block itself as well as the redundant requests to the block validator.
https://casperlabs.atlassian.net/browse/HWY-288

HWY-288: Avoid redundant requests caused by the Highway synchronizer.

---

node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs

Once all Highway dependencies are resolved, the synchronizer forgets about a proposed block and gives it to `HighwayProtocol` for inclusion into the protocol state. However, nonempty blocks are not immediately added: They are kept in the `pending_values` map while the block validator is downloading the deploys and checking the block limits. During that period, the synchronizer will request the same block again, if any dependent unit is added.
This PR should fix both the redundant requests for the block itself as well as the redundant requests to the block validator.
https://casperlabs.atlassian.net/browse/HWY-288
Port of https://github.com/casper-network/casper-node/pull/1381.

HWY-288: Avoid redundant requests caused by the Highway synchronizer. (dev port)

---

Cargo.lock
node/Cargo.toml

This removes the `rewests` crate, shaving 12% build time (from scratch) in my one-time my non-scientic build experiment. `assert_matches` is also removed, as it seems to unused.

NDRS-1235: Remove reqwests

---

Cargo.lock
node/Cargo.toml
node/src/components/network.rs
node/src/components/network/config.rs
node/src/components/network/tests.rs
node/src/components/network/tests_bulk_gossip.rs
node/src/components/small_network.rs
node/src/components/small_network/config.rs
node/src/components/small_network/error.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
resources/local/config.toml
resources/production/config-example.toml

Removes the now unused (superseded by `casper-node-launcher`) systemd notification support from all configurations and the functionality from the networking component.
**This does result in a change in configuration files**.

NDRS-1225: Remove systemd notify support

---

node/src/components/chainspec_loader.rs
node/src/types/chainspec.rs
node/src/types/chainspec/global_state_update.rs
node/src/types/chainspec/highway_config.rs
node/src/types/chainspec/protocol_config.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1156
This PR adds validation to the `ProtocolConfig` which ensures that the contained values make sense.  It also changes how such a failure is handled, now avoiding direct panics and instead using our own `ExitCode::Abort` to indicate that the process should stop.

NDRS-1156: validate chainspec protocol config

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/tests.rs
node/src/components/block_validator/tests.rs
node/src/components/consensus.rs
node/src/components/consensus/cl_context.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/config.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/effect.rs
node/src/effect/requests.rs
resources/local/config.toml
resources/production/config-example.toml

This fixes more edge cases where the synchronizer would send redundant requests for the same proposal.
It also uses `Arc<BlockPayload>` as the consensus value type, instead of `BlockPayload`, to avoid cloning all ancestor values for each block validation request.
https://casperlabs.atlassian.net/browse/HWY-292
https://casperlabs.atlassian.net/browse/NDRS-1237

HWY-292, NDRS-1237: Reduce duplication in block validation requests

---

node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/config.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs
resources/local/config.toml
resources/production/config-example.toml

With the `TIMER_ID_PANORAMA_REQUEST` firing periodically, a node would send out (to every peer) a request containing its latest panorama. The receiver, would then compare it with its local view of the DAG and either request a dependency from the sender, or send a newer unit (that the sender doesn't have yet). It would do that for every validator. This leads to `m * m * n` requests being made every `request_latest_panorama`, where `m` is the number of nodes in the network and `n` number of validators – everyone (`m`) would send a message to everyone else (`m - 1`) and trigger potentially `n` responses (one for every validator in the panorama), some of which (`RequestDependency`) would trigger a response (yet another message). That amount of additional messages being exchanged turned out to …

HWY-293: Request latest state only if stalled.

---

node/src/components/block_proposer.rs
node/src/components/block_proposer/tests.rs
node/src/components/block_validator/tests.rs
node/src/components/consensus.rs
node/src/components/consensus/cl_context.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/config.rs
node/src/components/consensus/protocols/highway/synchronizer.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/effect.rs
node/src/effect/requests.rs
resources/local/config.toml
resources/production/config-example.toml

Port https://github.com/casper-network/casper-node/pull/1389 and https://github.com/casper-network/casper-node/pull/1397 to the `dev` branch:
* Avoid requesting the same vertex redundantly from lots of peers.
* Add more logging to the synchronizer.
* Use `Arc` to avoid cloning consensus values (i.e. lists of deploy hashes) in memory.
* Change the default `pending_vertex_timeout` to 30 minutes.
* Only request our peers' latest states if we suspect we might be stuck.
https://casperlabs.atlassian.net/browse/HWY-292
https://casperlabs.atlassian.net/browse/HWY-293
https://casperlabs.atlassian.net/browse/NDRS-1237

HWY-292, HWY-293, NDRS-1237: Reduce redundant data and requests in Highway. (ports to dev)

---

client/lib/deploy.rs
client/lib/ffi.rs
client/lib/lib.rs
client/lib/parsing.rs
client/lib/rpc.rs
client/src/deploy.rs
client/src/deploy/make_transfer.rs
client/src/deploy/sign.rs
client/src/deploy/transfer.rs
client/src/main.rs
client/tests/integration_test.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1244
This PR introduces a separate subcommand to the Rust client `make-transfer` which is a mixture of the existing two subcommands `make-deploy` and `transfer`.  It allows for the creation of a Deploy for a transfer as a JSON-encoded file.  Using the existing `sign-deploy` and `send-deploy` subcommands on such a file allows us to use the Rust client to create multisig transfers.

NDRS-1244: add client support for multisig transfers

---

node/src/components/small_network.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1247
This PR fixes an oversight in the recent cleanup of small_network, whereby a recurring housekeeping task was never actually started on initialisation of the component.
I have run the integration test `itst01.sh` successfully three times after making this change.

NDRS-1247: start recurring connection housekeeping task

---

.drone.yml

Enables AJ to pickup the files from `genesis.casperlabs.io` for PRs against release branches.

OP-2041: upload genesis s3 files for PR to release

---

client/lib/deploy.rs
client/lib/ffi.rs
client/lib/lib.rs
client/lib/parsing.rs
client/lib/rpc.rs
client/src/deploy/make_transfer.rs
client/src/deploy/transfer.rs
client/tests/integration_test.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1245
This PR amends `--transfer-id` to be a non-optional argument of the Rust client's `transfer` and `make-transfer` subcommands.

NDRS-1245: make transfer-id a required arg in the Rust client

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/highway_core/finality_detector/rewards.rs
node/src/components/consensus/highway_core/highway.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/highway_core/state/tests.rs
node/src/components/consensus/highway_core/validators.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/synchronizer/tests.rs
node/src/components/consensus/protocols/highway/tests.rs

This implements [CEP 43](https://github.com/casper-network/ceps/pull/43) and excludes validators who were inactive for the whole duration of the previous era or faulty in a recent era from proposing blocks in the next one. Their slots are assigned to other validators instead. This is expected to improve liveness and make it less likely that proposals are missed.
https://github.com/casper-network/ceps/pull/43
https://casperlabs.atlassian.net/browse/HWY-289
https://casperlabs.atlassian.net/browse/NDRS-1158

HWY-289,NDRS-1158: Exclude inactive validators from proposing blocks.

---

node/src/components/small_network.rs

Simple fix that makes the code ~actually do what the comment says it does~ preserve the behavior before the refactoring.

Restore correct address preference in `/status` peer list

---

Cargo.lock
ci/casper_updater/Cargo.toml
ci/casper_updater/src/chainspec.rs
ci/casper_updater/src/dependent_file.rs
ci/casper_updater/src/main.rs
ci/casper_updater/src/package.rs
ci/casper_updater/src/regex_data.rs

Ref: https://casperlabs.atlassian.net/browse/NDRS-1217
This PR updates the `casper-updater` tool to handle changes required in the production chainspec and associated files.
The existing `--bump` arg which accepts values of `major`, `minor` or `patch` is used to also bump the appropriate part of the protocol version in the `resources/production/chainspec.toml` file.  If we need more fine-grained control over setting the protocol version, a new arg can be added to the tool for that.  But for now, it seems like our build version will be kept in lockstep with the protocol version.
The tool now has an `--activation-point` arg, which takes an integer used to set the activation point in the `resources/production/chainspec.toml` file.  There is no check that the value is being replaced with a …

NDRS-1217: handle chainspec in casper-updater

---

node/src/components/small_network.rs
node/src/components/small_network/chain_info.rs
node/src/components/small_network/counting_format.rs
node/src/components/small_network/error.rs
node/src/components/small_network/event.rs
node/src/components/small_network/message.rs
node/src/components/small_network/message_pack_format.rs
node/src/components/small_network/outgoing.rs
node/src/components/small_network/tasks.rs

Note: The size of this PR is in part due to some things being moved from one file to another, or fields being renamed.
This PR extracts tasks (asynchronous functions, most run as effects) from the small networking component into a submodule. In doing so it unifies what used to be broken up steps for establishing a new connection into linear `async` functions.
As a result there is a noticeable complexity reduction in the component itself. Handshake handling benefits immensely from this, as the code can now be properly shared and no longer leaks into the handling of other events.
Tasks become testable as a result.

NDRS-1202: Connection negotiation tasks

---

utils/nctl/sh/scenarios/common/itst.sh
utils/nctl/sh/scenarios/itst06.sh
utils/nctl/sh/scenarios/itst07.sh

Moves trap cleanup to common.
Extends cleanup to also print stderr/stdout on exit under certain criteria.
Disallows empty hashes for transfer scenarios.
Prints nctl-status if a node fails to start.
https://casperlabs.atlassian.net/browse/OP-2036
https://casperlabs.atlassian.net/browse/OP-2049.

OP-2036, OP-2049 NCTL Fixes

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/event_indexer.rs
node/src/components/event_stream_server/http_server.rs
node/src/components/storage.rs
node/src/reactor/joiner.rs

This PR provides the SSE server with a persistent cache for the last event index.  On dropping the server, the value is written to a file and read on starting.
The same folder used by the storage component is used for holding this file.  This has the advantage of not requiring any change to the config file type, and also restricts the number of locations the app will write to while running.
As well as the provided unit tests, I verified this works as expected by running an nctl upgrade test and asserting that the event indices were persisted across the upgrade by all nodes.
Closes #1417

Persist event stream event index

---

Cargo.lock
node/Cargo.toml
node/src/components/small_network.rs
node/src/components/small_network/bandwidth_limiter.rs
node/src/components/small_network/config.rs
node/src/components/small_network/event.rs
node/src/components/small_network/tasks.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs
resources/local/config.toml
resources/production/config-example.toml

Adds an optional bandwidth limiter to the networking component that allows limiting the amount of upstream consumed by nodes that are not validators or en route to becoming them in a little over an eras time.
Controlled through the `max_non_validating_peer_bps` setting; if it is set to 0, a no-op limiter is used instead.

Limit outgoing traffic

---

.drone.yml
ci/nctl_upgrade_stage.sh

Adds the 9 files used in the upgrade scenario to the nctl bucket
Runs on:
- push to `release-*` branches
- stored in matching branch name
- tagged releases
- stored in matching tag name
Ticket: https://casperlabs.atlassian.net/browse/OP-2030
Links for @sacherjj 
- push to release test: https://drone-auto.casperlabs.io/TomVasile/casper-node/117
- tag test: https://drone-auto.casperlabs.io/TomVasile/casper-node/118

OP-2030: NCTL Upgrades remote asset staging

---

types/src/json_pretty_printer.rs

This PR changes how pretty-printed JSON responses are displayed by the client.
Rather than shortening all strings over 100 chars (which was unhelpful in the case of an error message being hidden), only contiguous hex-strings of over 100 chars are replaced.  Since all our large blobs of binary data are hex-encoded when being encoded to JSON, this should still meet the objective of avoiding clutter in our JSON output, while retaining large, useful non-hex strings unchanged.
Closes #1456.

Restrict summarization when JSON pretty-printing to long hex strings

---

node/src/components/event_stream_server/sse_server.rs

This PR splits the SSE event stream into two discrete streams.  One stream emits only `FinalitySignature`s, the other emits all remaining event types.
The URL for the former is now `<IP:Port>/events/sigs` and the latter `<IP:Port>/events/main`.  The previous URL will now return a 404 with a body of `invalid path: expected 'events/main' or 'events/sigs'`.
The events continue to be indexed globally rather than per stream.  So for example, the main stream could yield event IDs of 1, 2, 4, 6.  In this case events 3 and 5 are `FinalitySignature`s filtered out of the main stream.  This allows consumers of both streams to interleave the events if desired, to recreate the original ordering.
Tagging @sacherjj @TomVasile @momipsl to draw attention to the changed URL path.
Closes #1452.

Move finality signatures to separate event stream

---

node/src/components/gossiper.rs
node/src/components/gossiper/gossip_table.rs
node/src/components/gossiper/metrics.rs

This PR simplifies the gossiper by removing the ability to pause and restart gossiping.
That functionality was added before there was a clear picture of how the networking component would operate.  The pause functionality is effectively unused and only serves to complicate the gossiper component.
Closes #1473.

Remove paused state from gossiper

---

node/src/components/linear_chain_sync/peers.rs

This fixes an issue where newly-connected peers are not considered as alternative sources for downloading a block during syncing the linear chain.
The issue meant that a node would stop trying to sync if the first attempt to download a block failed.  This was predominantly an issue in the context of nctl testing, where 5 nodes are started concurrently, attempting to join a network which had already gone through an upgrade.  The new nodes frequently attempted to use each other as the first source for downloading blocks, causing their linear chain sync processes to terminate (with success) early, and leaving them stalled, far behind the current tip of the chain.
Closes #1491.

Update peers_to_try with new peers in linear chain sync

---

node/src/components/small_network.rs
node/src/components/small_network/bandwidth_limiter.rs
node/src/components/small_network/tests.rs
node/src/reactor/joiner.rs
node/src/reactor/validator.rs

Contains a few minor fixes that are most prominent in testing:
* Disables bandwidth limiting when there is no information about validators at all. This can, for example, be triggered by setting absurdly low bandwidth limits and then starting a new network from genesis, stalling immediately.
* Respect existing known era IDs that are available. This is, due to the fix above, only a minor improvement, causing us to not having to wait until the next switch block.
* Log changes in known validator sets. This makes it possible to inspect traffic shaping behavior at all.
Changes in preparation to #1479.

Improve bandwidth limiting testing and edge cases

---

node/src/components/consensus/consensus_protocol.rs
node/src/components/storage.rs
node/src/crypto/hash.rs
node/src/types/block.rs
node/src/types/deploy.rs
utils/nctl/sh/scenarios/sync_upgrade_test.sh

This reverts changes to the way block hashes are calculated (NDRS-1082) due to issues it was causing with using a trusted hash after an upgrade.

Revert NDRS-1082

---

node/src/components/fetcher/tests.rs
node/src/components/gossiper/tests.rs
node/src/components/storage.rs
node/src/components/storage/tests.rs
node/src/reactor/initializer.rs

The behaviour where we usually skip integrity checks of global state has been extended to the storage component in this PR.  The integrity checks are now only performed if the node was detected to have crashed on the previous run.
Closes #1507.

Skip storage integrity checks if the node didn't previously crash

---

node/src/components/event_stream_server/sse_server.rs

This PR causes SSE event streams to be shut down gracefully rather than returning an error to the client.
For example, if `curl` is used to follow an event stream as a node stops for an upgrade, the stream exits with an error, reported to the user as `curl: (18) transfer closed with outstanding read data remaining` and `curl` exits with code `18`.  With the update in this PR, `curl` now exits with `0` and reports no error.
This also has the effect of avoiding `warp` logging errors on shutdown of the SSE server when client(s) are attached.
Closes #1512.

Shut down sse event streams gracefully

---

node/src/types/status_feed.rs

This PR re-targets #1336 to `dev`.
Closes #1489.

Avoid truncating state root hash

---

node/src/app/cli.rs
node/src/reactor.rs
node/src/reactor/validator/tests.rs
node/src/testing/network.rs
node/src/utils/round_robin.rs

This change makes it so that all queues are closed for further events and drained when a reactor is being extracted from a runner, preventing any resource leaks, assuming events are properly dropped.
Logging of the dropped events was not added, as it would add a trait bound for `Display` on everything calling `push`, which has historically not been the case. If necessary, this can be added at a later point in time.

Seal queues when shutting down reactors

---

utils/nctl/sh/scenarios/bond_its.sh
utils/nctl/sh/scenarios/common/itst.sh
utils/nctl/sh/scenarios/itst14.sh

Syncs `assert_node_proposed` function across the nctl tests.
Ticket: https://casperlabs.atlassian.net/browse/OP-2047

OP-2047: NCTL - Use assert_node_proposed with timeout

---

utils/nctl/sh/scenarios-upgrades/upgrade_scenario_01.sh
utils/nctl/sh/scenarios-upgrades/upgrade_scenario_02.sh
utils/nctl/sh/utils/os.sh

Changes the name of the `log_step` function used by the nctl upgrade scenarios. 
See Ticket: https://casperlabs.atlassian.net/browse/OP-2072

OP-2072: rename log_step used in upgrade scenarios

---

node/src/components/chainspec_loader.rs
node/src/components/linear_chain/state.rs
node/src/components/storage/tests.rs
node/src/types/block.rs

This PR improves the chainspec loader, in particular now properly handling the case of restarting after a chain fork rather than just debug asserting.
It also improves the logging during initialization, and adds unit tests.
Closes #1482.

Update chainspec loader initialization and add tests

---

node/src/components/small_network/outgoing.rs

I've moved the `warn!` and `info!` logs to `debug!` for logs that contain messages listed in ticket casper-network/casper-node#1519.

GH-1519 Change log level of certain logs.

---

Cargo.lock
node/Cargo.toml
node/src/components/event_stream_server.rs
node/src/components/event_stream_server/event_indexer.rs
node/src/components/event_stream_server/http_server.rs
node/src/components/event_stream_server/sse_server.rs
node/src/components/event_stream_server/tests.rs
node/src/types/block.rs
resources/test/sse_data_schema.json

This PR adds a comprehensive test suite for the SSE server.  In doing so, it revealed two issues in the server, both of which are fixed in this PR:
* The server did not handle malformed queries well.  In some cases it ignored them and in others it treated them as a bad path
* The server did not handle the `start_from` query properly in the case where the buffered events' IDs wrapped past `u32::MAX` back to `0`
The PR also introduces a test which checks the generated JSON schema for the `SseData` enum against a previously-generated, hard-coded schema (added to "resources/test").  Rather than being particularly useful as a unit test, it will instead make it somewhat simple to view differences between discrete versions of the data produced by the SSE server.
Closes #1525.

Add SSE server tests and fix issues exposed by these

---

node/src/components/consensus.rs
node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/validator_change.rs
node/src/effect.rs
node/src/effect/requests.rs
node/src/reactor/joiner.rs

This returns a list of changes to validators' states, i.e. whether they were added, removed, banned, etc.
Merging to a feature branch since it still requires work on the RPC side.
Closes #1526.

Add EffectBuilder::get_consensus_validator_info.

---

node/src/components/small_network/outgoing.rs

This changes some of the log levels back to the old levels, and fixes the bug where warnings are emitted upon a connection failure of an already blocked peer.

Outgoing logs: Levels and blocked failure reporting

---

node/src/components/event_stream_server/event_indexer.rs
node/src/components/event_stream_server/tests.rs

This makes the lagging client SSE server test more robust by changing it in a couple of ways:
* the test server now emits up to 100,000,000 events rather than the 100 previously
* the lagging clients now run slower by having a small sleep between reading each chunk of received data from the TCP stream
* the clients also pause for 5 seconds after connecting to the server but before starting to read data, to help ensure the server's TCP send buffer and client's TCP receive buffer are filled
Closes #1560.

Fix intermittent failure in SSE server test

---

node/src/components/consensus/era_supervisor.rs

This fixes the root cause of https://github.com/casper-network/casper-node/issues/1558.
To make the tests work reliably we should also set the standstill alert to a value lower than the minimum era duration and the `auction_delay` to 1, though. (See issue comment.)

Fix new_era() arguments mix-up.

---

node/src/components/small_network.rs

Cause for the bug:
- Recent changes to the `small_network` component removed the `peers` member from the component which was used to update the corresponding and the function `update_peers_metric` which did the update
Fix:
- The peers metrics now is set based on the current amount of symmetric connections

NDRS-1569: Fix peers metric

---

node/src/components/consensus/highway_core/synchronizer.rs
node/src/components/consensus/highway_core/synchronizer/tests.rs

If `c < b < a` and we already have `b` in the synchronizer queue when Alice sends us `a`, then we also know that Alice must be a holder of `c`, and request it from her.
With this PR, we will also remember later that Alice is a holder of `b`, and if `b` has further dependencies, we can request them from Alice.
Closes #1584.

Add holders of transitive dependencies in synchronizer.

---

client/lib/lib.rs
client/lib/rpc.rs
client/src/account_address.rs
client/src/common.rs
client/src/get_account_info.rs
client/src/main.rs
node/src/components/rpc_server/http_server.rs
node/src/components/rpc_server/rpcs.rs
node/src/components/rpc_server/rpcs/docs.rs
node/src/components/rpc_server/rpcs/state.rs
node/src/types/json_compatibility/account.rs

CHANGELOG:
- Added `get-account-info` command to the client
- Added `state_get_account_info` RPC method to the node which queries `GlobalState` for an `Account`

NDRS-1567: Add get-account-info command

---

.github/dependabot.yml

This PR adds explicit config for GitHub's dependabot with config for both npm and cargo with daily intervals.

GH-1602: dependabot config

---

node/src/components/rpc_server/rpcs/chain/era_summary.rs

This relates to [Issue 1604](https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/1604)
CHANGELOG:
- Fix the `seigniorage_allocations` which was previously empty by adding a `Delegator` and `Validator` to the era_summary
PS: @mpapierski could you please look at the output (attached to the PR) to see if the example provided is glaringly incorrect

NDRS-1604: Fix EraInfo schema representation

---

node/src/components/consensus/era_supervisor.rs
node/src/components/consensus/era_supervisor/era.rs
node/src/components/consensus/highway_core/state.rs
node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/tests.rs
node/src/reactor/participating.rs
node/src/reactor/participating/tests.rs

If someone equivocates in an old era N, we also mark them as faulty in era N + 1, N + 2, etc. (up to `unbonding_delay - auction_delay`). However, if the equivocation was detected _before_ era N + 1 was initialized, we failed to mark them as faulty in era N + 1 on initialization. This PR fixes that:
Now, when initializing a new era, we immediately mark everyone as faulty against whom we have evidence in a recent era. Since the synchronizer ignores faulty validators' units, unless cited by a non-faulty one, this means you can't effectively equivocate two eras in a row.
I also renamed all "slashing" references in consensus, since there are no plans to enable slashing, and that isn't strictly a consensus question anyway.
Closes #1516.

Mark known faulty validators when initializing eras.

---

node/src/components/small_network.rs
node/src/components/small_network/config.rs
node/src/components/small_network/limiter.rs
node/src/components/small_network/message.rs
node/src/components/small_network/tasks.rs
node/src/protocol.rs
resources/local/config.toml
resources/production/config-example.toml
utils/nctl/sh/scenarios/configs/itst13.config.toml

This introduces request rate limiting as described in CEP58. There are two resource pools, an unlimited one for known current and upcoming validators, and a shared one controlled by `max_non_validating_peer_request_rate`. For example, setting `max_non_validating_peer_request_rate` to `10` limits the amount of allowed `GetRequest`s for `Deploy`s to 10 per second _total_.
A large part of this PR is just the renaming of the `bandwidth_limiter` to `limiter` and resulting changes of types, comments and documentation. It may help to look at the diff that omits this renaming commit (9851442).

CEP58 / request rate limiting

---

client/lib/validation.rs
node/src/components/consensus/consensus_protocol.rs
node/src/components/contract_runtime.rs
node/src/components/linear_chain_sync/operations.rs
node/src/components/storage.rs
node/src/components/storage/lmdb_ext.rs
node/src/crypto/hash.rs
node/src/types.rs
node/src/types/block.rs
node/src/types/deploy.rs
node/src/types/error.rs

- Creates the follow databases:
1. block_body_merkle: BlockBodyHash → vec![hash(deploy_hashes),
hash(transfer_hashes), hash(proposer)]
2. deploy_hashes: hash(deploy_hashes) → deploy_hashes
3. transfer_hashes: hash(transfer_hashes) → transfer_hashes
4. proposer: hash(proposer) → proposer
- This is to facilitate extensibility of the block body in the future.
- Closes #1457 #1547 #1599

Add databases storing block bodies split into parts

---

client/lib/ffi.rs
client/lib/lib.rs
client/lib/parsing.rs
client/src/deploy/creation_common.rs

* added a new Boolean flag to the `make-deploy` and `put-deploy` subcommands called `--session-transfer` that tells the client that we want to make the deploy a transfer.
* this flag is mutually exclusive with the other `--session-<command>` commands except for `--session-arg`.

Make / Put Deploy Should Handle Transfers

---

smart_contracts/contract_as/package.json

***What does this change do?***
- Added reference to the github repo
- Added reference to assembly script docs page in casperlabs docs
***Why is this change needed?***
- Improve DevX experience. Difficult to track it back to the code and
docs when found on npm.

Added: npm reference to the github and docs homepage

---

node/src/components/event_stream_server.rs
node/src/components/event_stream_server/config.rs
node/src/components/event_stream_server/sse_server.rs
node/src/components/event_stream_server/tests.rs
resources/local/config.toml
resources/production/config-example.toml

This PR introduces a new config option `[event_stream_server][max_concurrent_subscribers]`, which defines the maximum number of clients allowed to subscribe to a single event stream server at any given time.
The limit is coarse-grained, relating to the total number of clients, regardless of which stream(s) are subscribed to.  It is not a per-stream limit.
Tagging @sacherjj and @momipsl to advise of the change to config file options.
Closes #1633.

Add configurable upper limit of concurrent event stream clients

---

utils/nctl/sh/scenarios/configs/itst13.config.toml

adds `max_concurrent_subscribers` to `itst13.config.toml`

NCTL: re-sync itst13 config.toml

---

node/src/crypto/asymmetric_key.rs

This PR adds regression tests for signing via the Ed25519 and secp256k1 keys.  The intent is that should either of these change their implementations in a non-backwards-compatible manner, these tests will alert us.
Closes #1581.

Add regression tests for cryptographic signatures

---

Makefile
smart_contracts/contract/src/ext_ffi.rs
types/src/key.rs
types/src/lib.rs
types/src/system/mint/error.rs

CHANGELOG:
- Added `RUSTDOCFLAGS="-D warnings"` to the `Makefile` causing doc warnings to escalated to errors instead
- Resolve resulting errors in both `node` and `types`

NDRS-1617: Resolve doc warnings

---

.github/pull_request_template.md
client/CHANGELOG.md
execution_engine/CHANGELOG.md
execution_engine_testing/cargo_casper/CHANGELOG.md
execution_engine_testing/test_support/CHANGELOG.md
node/CHANGELOG.md
node_macros/CHANGELOG.md
smart_contracts/contract/CHANGELOG.md
smart_contracts/contract_as/CHANGELOG.md
types/CHANGELOG.md

This adds changelogs for all published projects, with details of changes from versions 1.0.0 onward.
Closes #1541.

Add changelogs to published projects

---

client/CHANGELOG.md
client/lib/deploy.rs
client/lib/error.rs
client/lib/ffi.rs
client/lib/lib.rs
client/src/deploy/creation_common.rs
client/src/deploy/make.rs
client/src/deploy/make_transfer.rs
client/src/deploy/sign.rs
client/tests/integration_test.rs

* Adds a `--force` Boolean flag that can be passed to `make-deploy`, `sign-deploy` or `make-transfer`.
closes casper-network/casper-node#1574

[NDRS-1574] Add `--force` Boolean flag to commands that may overwrite files.

---

ci/nightly-test.sh
utils/nctl/sh/assets/compile.sh
utils/nctl/sh/assets/compile_global_state_update_gen.sh
utils/nctl/sh/assets/upgrade.sh

- introduces `compile_global_state_update_gen.sh` to `compile.sh`.
- adds `emergency_upgrade_test` & `emergency_upgrade_test_balances` to nightly wrapper.
- small toml update for adding `last_emergency_restart`

Adding emergency upgrades to nctl nightly runs

---

types/src/system/mint/entry_points.rs
types/src/system/mint/error.rs

CHANGELOG:
- Removed the `PurseError` enum as it was not being used
- Changed inline documentation to account for the removal

NDRS-1623: Remove purse error

---

client/CHANGELOG.md
client/lib/deploy.rs
client/lib/lib.rs

* changes `make-deploy`, `make-transfer` and `sign-deploy` to ensure that they do not damage or overwrite existing files if something goes wrong when writing the output file.
closes casper-network/casper-node#1575

NDRS-1575 Ensure Client Does Not Damage Files On Failure.

---

node/CHANGELOG.md
node/src/components/event_stream_server/sse_server.rs

As described in #1648, there was an edge case where the event stream server could emit duplicate events when a client requested a number of historic events via the `?start_from=N` query string.
This PR fixes the issue and adds a regression test for it.
Closes #1648.

Avoid emitting duplicate events in the event stream

---

node/src/components/consensus/era_supervisor.rs

Don't automatically restart a running node when the current era doesn't make progress; only restart if that happens shortly after joining the network.
Closes #1501.

Apply standstill alert only for joining nodes.

---

node/src/components/linear_chain_sync.rs
node/src/components/linear_chain_sync/error.rs
node/src/components/linear_chain_sync/operations.rs
node/src/components/linear_chain_sync/state.rs
node/src/types/chainspec/network_config.rs

If the era of the last downloaded block cannot have ended yet, stop syncing and complete the joining process. This is the case if:
* the time elapsed since the era's switch block is less than the minimum era duration, or
* the number of past rounds since the most recently downloaded block is less than the number of blocks remaining to reach the minimum era height.
Closes #1549.

Finish fast sync when in current era.

---

utils/nctl/sh/scenarios/bond_its.sh
utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in
utils/nctl/sh/scenarios/common/itst.sh
utils/nctl/sh/scenarios/itst13.sh

Changes:
- Adds unbonding testing to `bond_its.sh`
- Turns off seignorage in `bond_its.chainspec.toml.in` for consistent unbonding
- Moved `is_trusted_validator` & `assert_eviction` to common for re-use
- Updated logging messages for `assert_no_equivocators_logs` function
Jira: https://casperlabs.atlassian.net/browse/NDRS-846

NDRS-846: Add unbonding to existing bonding scenario

---

node/src/components/storage.rs
node/src/components/storage/lmdb_ext.rs

Issue: #1610
(Edit: also closes #1630).
This fixes how block data is being deleted from the databases (some entries can be referred to by multiple blocks), which ensures some aspects of the integrity, and adds checks for other aspects.

Introduce Integrity Check For New Block Storage Scheme

---

.drone.yml
Makefile

CHANGELOG:
- Add exception for RUSTSEC-2021-0076 in both `Makefile` and `drone.yml` 
Closes: https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/1691

1691: Mitigate RUSTSEC-2021-0076

---

node/src/components/consensus/protocols/highway.rs
node/src/components/consensus/protocols/highway/config.rs
node/src/components/consensus/protocols/highway/tests.rs
resources/local/config.toml
resources/production/config-example.toml

Add a `shutdown_on_standstill` option: If this is disabled, nodes no longer shut down if no progress is made in consensus.
Closes #1680.

Make shutdown on standstill optional.

---

execution_engine/src/core/runtime/mod.rs

Ref #1697 
This changes the non-exhaustive pattern with risky `assert` into an exhaustive match.

GH-1697: Exhaustive pattern matching

---

ci/nctl_upgrade.sh
utils/nctl/sh/staging/set_remote.sh

Changes:
- Switched to check if the `vX.Y.Z` url exists.
- Uses `release-X.Y.Z` url if not

NCTL - Asset pathing fix for release vs release-candidate

---

ci/nctl_upgrade.sh
utils/nctl/sh/scenarios-upgrades/upgrade_scenario_03.sh

Changes:
- rebalances bid/delegation to be more realistic and similar to `upgrade_scenario_3.accounts.toml`
- waits auction_delay + 1 
- re-enables scenario 3

NCTL - re-enable scenario 3 in CI
