casper-network/casper-node

node/src/components/consensus/era_supervisor.rs
https://casperlabs.atlassian.net/browse/NDRS-393
=> NDRS-393: Don't start an era before its start timestamp.

client/src/common.rs, client/src/deploy.rs, client/src/deploy/creation_common.rs, client/src/deploy/make.rs, client/src/deploy/put.rs, client/src/deploy/send.rs, client/src/deploy/sign.rs, client/src/deploy/transfer.rs, client/src/generate_completion.rs, client/src/keygen.rs, client/src/main.rs
Here's the implementation of make, sign and send commands needed in the client as per NDRS-403, (requested a review from @darthsiroftardis as you have a task for put-deploy that will depend on these I think).
=> NDRS-403 client deploy (make, sign, send) commands

Cargo.lock, client/Cargo.toml, node/Cargo.toml, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/state.rs, node/src/reactor/validator/tests.rs, run-dev.sh
=> Backport #260, #261, #262, #264 to Charlie, update version to 0.1.2.

node/Cargo.toml, resources/charlie/CURRENT_RUN_NOTES.md, resources/charlie/chainspec.toml, resources/maintainer_scripts/casper_node/casper-node.service
Removed accounts.csv and chainspec.toml.
Reduced finality_threshold_percent to 12.
=> Update files for 2020-09-24 17:00:00 Charlie-5 run.

resources/charlie/CURRENT_RUN_NOTES.md
Update md5sum for chainspec.toml in document.
=> Update md5sum for chainspec.toml due to name change.

node/src/components/consensus/highway_core/evidence.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/validators.rs
https://casperlabs.atlassian.net/browse/HWY-150
=> HWY-150: Check signatures; fix & test other evidence checks.

node/src/components/api_server.rs, node/src/components/chainspec_loader.rs, node/src/effect.rs, node/src/effect/requests.rs, node/src/reactor/validator.rs, node/src/types/status_feed.rs
Related to JIRA ticket:
https://casperlabs.atlassian.net/browse/NDRS-413
=> NDRS-412: Add Chainspec information to GetStatus feed

client/src/deploy/creation_common.rs, client/src/deploy/make.rs, client/src/deploy/put.rs, client/src/deploy/transfer.rs
Here's my recent work on the options in NDRS-325
=> NDRS-325 put deploy variants

node/src/components/consensus/era_supervisor.rs
https://casperlabs.atlassian.net/browse/NDRS-421
=> NDRS-421: Don't panic if outdated block is executed.

execution_engine/src/core/runtime/mod.rs, smart_contracts/contracts/system/auction/src/lib.rs, types/src/auction/constants.rs
Ref: https://casperlabs.atlassian.net/browse/NDRS-416
This PR adds some bits from NDRS-392 to enable co-development of that work and NDRS-307.
=> NDRS-416: Add entry point stubs for Auction::distribute

node/src/components/block_executor.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/validators.rs, node/src/components/deploy_acceptor.rs, node/src/reactor/joiner.rs
Ports 3 PRs from `master` – #277 #269 #278
=> [charlie] cherry-picked: #277 #269 #278

node/src/components/consensus/highway_core/active_validator.rs
We should pass in the proper current timestamp, but for now, this is a workaround:
Instead of the proposal's timestamp, use the earliest possible timestamp for the confirmation vote. Also, take the two-votes-per-round rule into account when computing the earliest possible timestamp.
(I created https://casperlabs.atlassian.net/browse/NDRS-433 for a proper fix.)
=> NO-TICKET: Fix outdated confirmation warnings.

.drone.yml, upload.sh
=> OP-1540 testing cicd

node/src/components/deploy_acceptor.rs, node/src/components/deploy_buffer.rs
Cherry picks #281 on top of charlie branch.
=> [charlie] cache chainspec

resources/charlie/CURRENT_RUN_NOTES.md, resources/maintainer_scripts/casper_node/casper-node.service
Moving back to old method that required renaming as I can't get appending to run.
=> Can't get log fix to work, rolling back to be able to run.

resources/charlie/CURRENT_RUN_NOTES.md
Missed changing name of header and time.
=> Charlie-6 Correct all headers to have proper time and name.

client/src/query_state.rs, node/src/crypto/asymmetric_key.rs
While testing this I found an issue I'd overlooked in the hex-decoding of `PublicKey` and `Signature` types whereby a panic would happen if an input of length < 2 was given.  I added two tests for these cases and fixed the issue.
=> NDRS-450: accept public key as arg to client query for now

node/src/components/block_executor.rs, node/src/components/contract_runtime.rs, node/src/effect.rs, node/src/effect/requests.rs, node/src/types/block.rs
This implements calling of the `commit_step` method in the execution engine, which then executes slashing, rewards and the auction contract.
=> NDRS-434: Implement consensus instructions to auction contract

node/src/components/fetcher.rs, node/src/components/linear_chain.rs, node/src/components/storage.rs, node/src/effect.rs, node/src/effect/requests.rs, node/src/types/block.rs
https://casperlabs.atlassian.net/browse/NDRS-350
https://casperlabs.atlassian.net/browse/NDRS-351
=> NDRS-[350,351]: Add "fetch block by height" feature and replace in-mem cache usage with calls to the DB.

grpc/test_support/src/internal/wasm_test_builder.rs, grpc/tests/src/test/contract_api/transfer_purse_to_account.rs, grpc/tests/src/test/step.rs, grpc/tests/src/test/system_contracts/auction/distribute.rs, grpc/tests/src/test/system_contracts/genesis.rs, smart_contracts/contracts/system/mint-install/src/main.rs, types/src/mint.rs, types/src/mint/constants.rs, types/src/mint/round_reward.rs, types/src/system_contract_errors/mint.rs
This PR adds a running tracker of total supply created by the mint.
https://casperlabs.atlassian.net/browse/EE-1048
=> EE-1048: track total supply

resources/charlie/README.md
Added CPU, RAM, Drive space best guess.
=> OP-1607 README updates for system requirements.

node/src/components/chainspec_loader/chainspec.rs, node/src/reactor/initializer.rs, resources/local/chainspec.toml
This PR updates the Highway config and adds a sanity check for the future, printing a warning if the values don't make sense.
=> NDRS-488: Update default configs in `/local/chainspec.toml`

node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/finality_detector.rs, node/src/components/consensus/highway_core/finality_detector/rewards.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/validators.rs, node/src/components/consensus/protocols/highway.rs
I found these bugs and inconsistencies when working on [HWY-156](https://casperlabs.atlassian.net/browse/HWY-156), so I split off the parts that have nothing to do with HWY-156 itself.
=> NO-TICKET: Fix tests, missing panorama update, and some cleanups.

client/README.md, client/src/common.rs
This changed documentation is based upon #369 having been merged.  However, since this PR only includes changes to the README (except for changing the default value for the `--node-address` arg to suit the nctl tooling), I don't believe it needs to be blocked by #369.
=> NDRS-502: update client README.md

Cargo.lock, client/Cargo.toml, node/Cargo.toml, node/src/lib.rs
Bumping to 1.5.0 on master after the release of 1.4.0.
=> no-tick Post release branch version bump, per versioning standards.

node/src/components/consensus/consensus_protocol.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/finality_detector/rewards.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/panorama.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/validators.rs, node/src/components/consensus/protocols/highway.rs
https://casperlabs.atlassian.net/browse/HWY-156
=> HWY-156: Add fault type for evidence from other eras to Highway.

Cargo.lock, client/Cargo.toml, execution_engine/Cargo.toml, execution_engine/src/core/execution/address_generator.rs, execution_engine/src/core/runtime/externals.rs, execution_engine/src/core/runtime_context/mod.rs, execution_engine/src/shared/newtypes/blake2b256.rs, grpc/cargo_casper/Cargo.toml, grpc/cargo_casper/tests/integration_tests.rs, grpc/server/Cargo.toml, grpc/test_support/Cargo.toml, grpc/tests/Cargo.toml, node/Cargo.toml, node/src/components/consensus/era_supervisor.rs, node/src/crypto/hash.rs, node/src/types/block.rs, resources/charlie/chainspec.toml, resources/local/chainspec.toml, smart_contracts/contract/Cargo.toml, types/Cargo.toml, types/src/account.rs, utils/nctl/templates/chainspec.toml
This updates our dependencies, in particular those flagged as insecure at https://deps.rs/repo/github/CasperLabs/casper-node.
It also brings the three chainspec files in closer alignment with each other.
=> NO-TICKET: various updates

execution_engine/src/core/engine_state/execute_request.rs, execution_engine/src/core/engine_state/execution_result.rs, execution_engine/src/core/engine_state/genesis.rs, execution_engine/src/core/engine_state/mod.rs, execution_engine/src/core/runtime/mod.rs, grpc/server/src/engine_server/mappings/ipc/execute_request.rs, grpc/test_support/src/internal/execute_request_builder.rs, grpc/test_support/src/internal/mod.rs, grpc/test_support/src/internal/wasm_test_builder.rs, grpc/tests/src/test/contract_api/transfer.rs, grpc/tests/src/test/system_contracts/auction/distribute.rs, grpc/tests/src/test/system_contracts/pos_install.rs, grpc/tests/src/test/system_contracts/proof_of_stake/finalize_payment.rs, grpc/tests/src/test/system_contracts/standard_payment.rs, node/src/components/block_executor.rs, node/src/types/block.rs, smart_contracts/contracts/system/pos-install/src/main.rs, smart_contracts/contracts/system/pos/src/lib.rs, types/src/lib.rs, types/src/proof_of_stake.rs, types/src/proof_of_stake/constants.rs, types/src/public_key.rs
This PR updates finalization logic to pay the proposer of a block.
https://casperlabs.atlassian.net/browse/EE-1061
=> EE-1061: transaction fees to proposer

.drone.yml, update-rev.sh, upload.sh
- publish casper-client to bintray repo
=> [OP-1619] Deploy casper-client deb to bintray repo

Cargo.lock, node/src/components/fetcher.rs, node/src/components/fetcher/config.rs, node/src/components/fetcher/tests.rs, node/src/lib.rs, node/src/reactor/joiner.rs, node/src/reactor/validator.rs, node/src/reactor/validator/config.rs, resources/charlie/config-example.toml, resources/local/config.toml, resources/production/config-example.toml
This PR adds a separate config section for the fetcher component.
https://casperlabs.atlassian.net/browse/NDRS-547
=> NDRS-547: fetcher config

resources/maintainer_scripts/config_from_example.sh
Correcting bug introduced when refactor changed config to CONFIG in string.
=> OP-1636 [deb packaging] Fixing refactor change within the string for CONFIG to config.

node/src/components/consensus/highway_core/highway.rs
https://casperlabs.atlassian.net/browse/HWY-169
=> HWY-169: Gossip evidences of equivocations.

node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/test_macros.rs
https://casperlabs.atlassian.net/browse/HWY-171
=> HWY-171: Include list of votes' hashes that need endorsing in `WireVote`.

types/src/deploy_info.rs
This one comes up from time to time (odd), though hasn't surfaced in CI (yet).  Might as well nip it in the bud.
=> NO-TICKET: appease sporadic clippy complaint

grpc/server/protobuf/casper/ipc.proto, grpc/server/src/engine_server/mappings/ipc/upgrade_request.rs, grpc/test_support/src/internal/upgrade_request_builder.rs, node/src/components/chainspec_loader/chainspec.rs, node/src/components/consensus/era_supervisor.rs, resources/test/valid/chainspec.toml
Renamed Rank to Height as per: https://casperlabs.atlassian.net/browse/NDRS-441
=> NDRS-441: Rename Rank to Height

.drone.yml, ci/check_genesis_validation.sh, resources/production/generate_validation.sh, resources/production/validation.md5
Added CI checking of validation.md5 for genesis files in resources/production.
=> [packaging] Add CI checking of validation.md5 for genesis files

node/src/components/consensus.rs, node/src/components/consensus/consensus_protocol.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/protocols/highway.rs, node/src/reactor/joiner.rs, node/src/reactor/validator.rs
The node will now crash if it detects that consensus can't make progress.
Related to https://casperlabs.atlassian.net/browse/NDRS-544
=> NDRS-544: Add early crashes to improve UX

node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/endorsement.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/panorama.rs, node/src/components/consensus/highway_core/state/vote.rs
https://casperlabs.atlassian.net/browse/HWY-170
=> HWY-170: Create endorsements.

execution_engine/src/storage.rs, execution_engine/src/storage/global_state/lmdb.rs, execution_engine/src/storage/protocol_data_store/tests/proptests.rs, execution_engine/src/storage/transaction_source/lmdb.rs, execution_engine/src/storage/trie_store/lmdb.rs, execution_engine/src/storage/trie_store/operations/tests/mod.rs, execution_engine/src/storage/trie_store/tests/concurrent.rs, execution_engine/src/storage/trie_store/tests/proptests.rs, execution_engine/src/storage/trie_store/tests/simple.rs, grpc/server/src/main.rs, grpc/test_support/src/internal/wasm_test_builder.rs, node/src/components/contract_runtime.rs, node/src/components/contract_runtime/config.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1097
=> EE-1097: increase ContractRuntime max readers to 512

utils/nctl/README.md
added link to casper-node pre-requisites
=> Include node build requirements for nctl

Cargo.lock, smart_contracts/contracts/client/withdraw-delegator-reward/Cargo.toml, smart_contracts/contracts/client/withdraw-delegator-reward/README.md, smart_contracts/contracts/client/withdraw-delegator-reward/src/main.rs, smart_contracts/contracts/client/withdraw-validator-reward/Cargo.toml, smart_contracts/contracts/client/withdraw-validator-reward/README.md, smart_contracts/contracts/client/withdraw-validator-reward/src/main.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1099
See `README`s for usage instructions
=> EE-1099: add client contracts for withdrawing seigniorage

node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/state.rs
https://casperlabs.atlassian.net/browse/HWY-177
=> HWY-177: Log detected equivocations.

.drone.yml, ci/drone_s3_storage.sh, ci/test_deb.sh, docker_make.sh, node/Cargo.toml, resources/maintainer_scripts/config_from_example.sh, resources/maintainer_scripts/pull_genesis.sh
Testing deb on clean ubuntu image.
Updated to install curl with casper-node and reworked all of package to use curl.
drone_s3_storage to cache artifacts between pipelines on different machines.
This was tested on the release-test branch here: http://drone-auto.casperlabs.io/CasperLabs/casper-node/2557/5/3
=> OP-1642 test deb after build and pipeline parallel optimization.

node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/state/unit.rs, node/src/components/consensus/highway_core/test_macros.rs
https://casperlabs.atlassian.net/browse/HWY-190
Units endorsed by unit _u_ should be a superset of units endorsed by _u_'s panorama.
=> HWY-190: Monotonicity of endorsed units.

node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/test_macros.rs
https://casperlabs.atlassian.net/browse/HWY-191
=> HWY-191: Add basic tests for LNC validity.

node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/protocols/highway.rs
JIRA: https://casperlabs.atlassian.net/browse/HWY-160
=> HWY-160: Protect against fork spam

node/src/components/block_executor.rs, node/src/components/consensus/era_supervisor/tests.rs, node/src/components/consensus/tests/mock_proto.rs, node/src/types/block.rs
https://casperlabs.atlassian.net/browse/NDRS-512
=> NDRS-512: Test block proposal and finalization in era supervisor.

grpc/tests/src/test/system_contracts/auction_install.rs, smart_contracts/contracts/system/auction-install/src/main.rs, types/src/auction.rs, types/src/auction/bid.rs, types/src/auction/constants.rs, types/src/auction/delegator.rs, types/src/auction/detail.rs, types/src/auction/types.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1109
=> EE-1109: auction: remove {Delegator,Validator}RewardsMap

execution_engine/src/core/engine_state/mod.rs, execution_engine/src/core/engine_state/step.rs
This PR corrects the step function's error handling to handle all cases, and includes specific slashing, auction, and reward distribution errors where applicable.
https://casperlabs.atlassian.net/browse/EE-1110
=> EE-1110: improve step error handling

node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/protocols/highway.rs
https://casperlabs.atlassian.net/browse/HWY-172
=> HWY-172: Drop vertices dependent on invalid vertex.

node/src/components/consensus/consensus_protocol.rs, node/src/components/consensus/highway_core.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/tests.rs
JIRA: https://casperlabs.atlassian.net/browse/HWY-188
=> HWY-188: Introducing Tests for HighwayProtocol

node/src/logging.rs
This allows third party crates which use `log` macros rather than `tracing` ones to have their log lines output too.
This is going to be particularly useful for my ongoing work with libp2p.  Once that work is integrated, we might need to look to provide a `RUST_LOG` env var for users who wish to see debug or trace level logging, since we'd likely only want to include that level of logging from our own crates.
=> NDRS-557: enable logging for external crates which use log rather than tracing

node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs
This PR lays some groundwork that can be used when writing unit tests. Does not return LNC-compliant panoramas for our units yets.
=> HWY-167: Add `citable_panorama` to `State` struct.

node/src/components/block_executor.rs
This PR reduces the verbosity of execution result logging, to reduce log spam.
https://casperlabs.atlassian.net/browse/NDRS-568
=> NDRS-568: Dial down verbosity of execution result logging.

resources/production/chainspec.toml, resources/production/config-example.toml, resources/production/validation.md5
Updating files for Delta-3 including 34553 -> 35000 port change and new known IPs.
=> Delta 3 genesis files.

client/lib/ffi.rs, execution_engine/src/core/execution/address_generator.rs, execution_engine/src/core/runtime/mod.rs, execution_engine/src/core/runtime_context/mod.rs, execution_engine/src/shared/logging/settings.rs, execution_engine/src/storage/protocol_data.rs, execution_engine/src/storage/protocol_data_store/mod.rs, execution_engine/src/storage/trie_store/mod.rs, grpc/tests/src/profiling/concurrent_executor.rs, node/src/components/chainspec_loader.rs, node/src/components/event_stream_server.rs, node/src/components/event_stream_server/sse_server.rs, node/src/components/rpc_server.rs, node/src/components/rpc_server/rpcs.rs, smart_contracts/contract/src/ext_ffi.rs, types/src/uref.rs
REF: https://casperlabs.atlassian.net/browse/NDRS-318
=> NDRS-318: Fix Doc Links

node/src/components/storage.rs
Hotfix to restore performance on Mac OS X (even though not officially supported :))
=> Disable `WRITE_MAP` on Mac OS X

node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/era_supervisor/tests.rs, node/src/components/linear_chain.rs, node/src/components/storage.rs, node/src/components/storage/tests.rs, node/src/crypto/asymmetric_key.rs, node/src/effect.rs, node/src/effect/requests.rs, node/src/protocol.rs, node/src/reactor/joiner.rs, node/src/reactor/validator.rs, node/src/types/block.rs, run-dev.sh
https://casperlabs.atlassian.net/browse/NDRS-572
=> NDRS-572: Gossip finality signatures.

node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs
(Based on https://github.com/CasperLabs/casper-node/pull/575.)
https://casperlabs.atlassian.net/browse/HWY-167
https://casperlabs.atlassian.net/browse/HWY-205
=>  HWY-{167, 205}: Create LNC-compliant units; enable LNC check.

types/src/auction.rs
=> NDRS-646: add band-aid to auction

node/src/components/consensus/highway_core/evidence.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/unit.rs
Minor cleanups I extracted from my WIP on [HWY-168](https://casperlabs.atlassian.net/browse/HWY-168).
=> NO-TICKET: Minor cleanups and fixes.

node/src/components/small_network.rs
This reverts commit 2a3fa3b00b7b9e9da8b89f0a0664e1dec09cec92.
=> NO-TICKET: Revert "handshake on outgoing connections to avoid banning peers"

execution_engine/src/core/engine_state/execution_result.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1123
=> EE-1123: fix transfers field on execution result

node/src/components/consensus/highway_core/finality_detector.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/state/unit.rs
https://casperlabs.atlassian.net/browse/HWY-214
=> HWY-214: Better document some invariants; remove outdated TODOs.

node/src/components/chainspec_loader/chainspec.rs, node/src/components/consensus/protocols/highway.rs, node/src/reactor/validator/tests.rs, resources/local/chainspec.toml.in, resources/production/chainspec.toml, resources/production/validation.md5, resources/test/valid/chainspec.toml
https://casperlabs.atlassian.net/browse/NDRS-202
https://casperlabs.atlassian.net/browse/NDRS-364
=> {NDRS-202, NDRS-364}: Clean up chainspec

execution_engine/src/core/engine_state/transfer.rs, execution_engine/src/core/resolvers/v1_resolver.rs, execution_engine/src/core/runtime/auction_internal.rs, execution_engine/src/core/runtime/externals.rs, execution_engine/src/core/runtime/mint_internal.rs, execution_engine/src/core/runtime/mod.rs, execution_engine/src/core/runtime/proof_of_stake_internal.rs, execution_engine/src/core/runtime/standard_payment_internal.rs, grpc/server/protobuf/casper/state.proto, grpc/server/src/engine_server/mappings/state/transfer.rs, grpc/tests/src/test/deploy/receipts.rs, smart_contracts/contract/src/contract_api/system.rs, smart_contracts/contract/src/ext_ffi.rs, smart_contracts/contracts/system/mint-token/src/lib.rs, smart_contracts/contracts/test/modified-mint/src/lib.rs, types/src/mint.rs, types/src/mint/constants.rs, types/src/mint/system_provider.rs, types/src/transfer.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1126
(in support of a client integration)
=> EE-1126: include optional recipient field in Transfer

client/README.md, client/src/common.rs
Client port for users is defaulting to 50101 when it should be 7777. I believe this is about local tests.
=> Changing default client port to 7777 for master

node/src/logging.rs
This removes a common pitfall for new users of the node that are confronted without any output at all when starting it up.
=> Change the default log level to `info`, avoiding no output when starting a node

client/lib/validation.rs, node/src/types/block.rs
REF: https://casperlabs.atlassian.net/browse/NDRS-648
=> NDRS-648: Validate Get-Block Response

client/lib/ffi.rs, client/lib/lib.rs, client/lib/rpc.rs, client/lib/validation.rs, client/src/get_era_info.rs, client/src/main.rs, node/src/components/rpc_server/http_server.rs, node/src/components/rpc_server/rpcs.rs, node/src/components/rpc_server/rpcs/chain.rs, node/src/components/rpc_server/rpcs/docs.rs, node/src/components/rpc_server/rpcs/state.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1128
(needed for client integration)
=> EE-1128: add chain_get_era_info RPC endpoint

node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/finality_detector/horizon.rs, node/src/components/consensus/highway_core/finality_detector/rewards.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/test_macros.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/tests.rs
It's the convention elsewhere in the code.
=> NO-TICKET: Replace opt_ prefix with maybe_ for optional values.

execution_engine/src/core/runtime/mint_internal.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1129
A real fix that will properly handle the errors on the way in a follow
up PR.
=> EE-1129: Quick and dirty hack to ignore the errors

node/src/components/chainspec_loader.rs, node/src/components/consensus/config.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/tests.rs, node/src/reactor/joiner.rs
https://casperlabs.atlassian.net/browse/NDRS-578
=> NDRS-578: Use smaller subset of chainspec in era supervisor.

node/src/components/consensus.rs, node/src/components/consensus/consensus_protocol.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/protocols/highway.rs, node/src/effect.rs, node/src/effect/announcements.rs, node/src/reactor/joiner.rs, node/src/reactor/validator.rs
https://casperlabs.atlassian.net/browse/NDRS-216
=> NDRS-216: Raise an announcement that indicates when a node needs to be punished

node/src/types/block.rs
https://casperlabs.atlassian.net/browse/NDRS-688
=> NDRS-688: Include wasmless transfers in the deploy list in a block

node/src/components/consensus.rs, node/src/components/consensus/era_supervisor.rs
Since summits are not monotonous, it can happen that we see a switch block finalized but other honest validators don't, because they first see an equivocation that invalidates the summit.
To make it more likely that everyone sees the switch block finalized, we keep voting for a while, and only stop once we observed no new equivocations within a period that was sufficient to finalize the block.
https://casperlabs.atlassian.net/browse/NDRS-687
=> NDRS-687: Delay era deactivation.

node/src/components/consensus/highway_core/active_validator.rs
Prioritize new proposals over old ones, so that stale entries in `next_proposal` don't block us, even if the consensus component didn't receive a response from the block proposer.
=> NO-TICKET: Clear ActiveValidator::next_proposal earlier.

node/src/components/block_proposer.rs, node/src/components/block_proposer/deploy_sets.rs, node/src/components/block_proposer/event.rs, node/src/reactor/validator.rs
https://casperlabs.atlassian.net/browse/NDRS-693
=> NDRS-693: Fix incorrect next_finalized on Block Proposer initialization

node/src/components/block_executor.rs, node/src/components/block_executor/event.rs, node/src/components/consensus.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/era_supervisor/era.rs, node/src/reactor/validator.rs
https://casperlabs.atlassian.net/browse/NDRS-694
https://casperlabs.atlassian.net/browse/HWY-220
=> {NDRS-694, HWY-220} Re-joining bugfixes

node/src/components/deploy_acceptor.rs, node/src/components/deploy_acceptor/config.rs, node/src/components/deploy_acceptor/event.rs, node/src/components/fetcher/tests.rs, node/src/components/gossiper/tests.rs, node/src/effect.rs, node/src/lib.rs, node/src/reactor/joiner.rs, node/src/reactor/validator.rs, node/src/reactor/validator/config.rs, node/src/types/deploy.rs, node/src/utils.rs, resources/local/config.toml, resources/production/config-example.toml
This PR verifies associated account for received deploys.
https://casperlabs.atlassian.net/browse/NDRS-686
=> NDRS-686: verify account in deploy acceptor

execution_engine/src/storage/transaction_source/lmdb.rs, node/src/components/storage.rs
REF: https://casperlabs.atlassian.net/browse/EE-1114
Sample Output:
=> EE-1114: Rename LMDB files

node/src/components/consensus.rs, node/src/components/consensus/consensus_protocol.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/protocols/highway.rs, node/src/reactor/validator.rs
https://casperlabs.atlassian.net/browse/HWY-224
This should fix our issues when joining the network close to the end of an era.
=> HWY-224: Request latest state of the current era when connecting to a new peer

node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/evidence.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/state/unit.rs, node/src/components/consensus/highway_core/test_macros.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/tests.rs
https://casperlabs.atlassian.net/browse/HWY-105
=> HWY-105: Avoid unnecessarily recomputing unit hashes.

node/src/components/consensus/highway_core/finality_detector.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/test_macros.rs
https://casperlabs.atlassian.net/browse/HWY-221
=> HWY-221: Add a test, remove two TODOs.

node/src/components/consensus/highway_core/finality_detector.rs
Example output:
`finality detected; panorama=ValidatorMap([04e4..643c, 0ce6..edb9, 3309..9717]); finalized_block=FinalizedBlock { value: [9], timestamp: Timestamp(40960), height: 9, rewards: None, equivocators: [], proposer: ValidatorId(1) }`
https://casperlabs.atlassian.net/browse/HWY-228
=> HWY-228: Log the panorama on finality and equivocation catastrophe.

node/src/crypto/asymmetric_key.rs, node/src/crypto/asymmetric_key_ext.rs
Ref:
https://casperlabs.atlassian.net/browse/NDRS-747
=> NDRS-747: fix SecretKey::generate_ed25519

resources/maintainer_scripts/logrotate.d/casper-node
https://casperlabs.atlassian.net/browse/OP-1766
=> glob only *.log files

node/src/reactor/joiner.rs, node/src/reactor/joiner/memory_metrics.rs, node/src/reactor/validator/memory_metrics.rs
REF: https://casperlabs.atlassian.net/browse/NDRS-737
Created a memory_metrics for the joiner and wired it up for the joiner
=> NDRS-737: Add memory metrics for the joiner

client/src/deploy/creation_common.rs, execution_engine/src/core/engine_state/execution_result.rs, execution_engine/src/core/engine_state/mod.rs, grpc/test_support/src/internal/deploy_item_builder.rs, grpc/test_support/src/internal/mod.rs, grpc/test_support/src/test_context.rs, grpc/tests/src/test/contract_api/transfer.rs, grpc/tests/src/test/contract_api/transfer_stored.rs, grpc/tests/src/test/contract_api/transfer_u512_stored.rs, grpc/tests/src/test/deploy/non_standard_payment.rs, grpc/tests/src/test/deploy/stored_contracts.rs, grpc/tests/src/test/regression/ee_599.rs, grpc/tests/src/test/system_contracts/proof_of_stake/finalize_payment.rs, grpc/tests/src/test/system_contracts/standard_payment.rs, node/src/components/block_proposer.rs, node/src/components/block_proposer/tests.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1143
=> EE-1143: Use real gas price

node/src/components/linear_chain_sync.rs, node/src/components/linear_chain_sync/metrics.rs, node/src/reactor/joiner.rs
https://casperlabs.atlassian.net/browse/NDRS-764
=> NDRS-764: Add histogram metrics to `LinearChainSync`.

node/src/components/consensus/protocols/highway.rs
https://casperlabs.atlassian.net/browse/NDRS-770
=> NDRS-770: Don't disconnect based on 'invalid' value.

execution_engine/src/core/engine_state/mod.rs, execution_engine/src/core/engine_state/transfer.rs, grpc/tests/src/test/regression/ee_1160.rs, grpc/tests/src/test/regression/mod.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1160
=> EE-1160: Transfer bug

node/src/components/linear_chain.rs
This fixes a recent regression whereby the vast majority of finality signatures were not being sent to the event stream.
=> NO-TICKET: send finality signatures to event stream

types/src/cl_value.rs
This fixes an issue whereby the JSON schema derived for `CLValue` omitted the `parsed` field of the JSON representation.
=> NO-TICKET: fix JSON schema for CLValue

node/src/components/consensus/cl_context.rs, node/src/components/consensus/era_supervisor/era.rs, node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/endorsement.rs, node/src/components/consensus/highway_core/evidence.rs, node/src/components/consensus/highway_core/finality_detector.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/panorama.rs, node/src/components/consensus/highway_core/state/params.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/consensus/highway_core/state/unit.rs, node/src/components/consensus/highway_core/state/weight.rs, node/src/components/consensus/highway_core/validators.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/tests/consensus_des_testing.rs, node/src/components/consensus/traits.rs
`estimate_heap_size` was called on `&HighwayProtocol` instead of `HighwayProtocol` and returned `0`.
https://casperlabs.atlassian.net/browse/HWY-242
=> HWY-242: Fix DataSize implementation for HighwayProtocol

Cargo.lock, execution_engine/Cargo.toml, node/Cargo.toml, node/src/components/consensus/highway_core/active_validator.rs, node/src/components/consensus/highway_core/highway/vertex.rs, node/src/components/consensus/highway_core/state/unit.rs, types/Cargo.toml
https://casperlabs.atlassian.net/browse/HWY-242
=> HWY-242: Upgrade DataSize; remove skips.

node/src/components/network.rs, node/src/components/network/event.rs, node/src/components/network/tests.rs
https://casperlabs.atlassian.net/browse/NDRS-842
=> NDRS-842: Have network retry connecting

.drone.yml, upload.sh
Removed update-revision to stop changes to cargo.toml. 
Added package-tag flag to be used in tagging pipeline.
=> NO-TICK: Changes for fixing crates publish on tag

execution_engine/src/core/engine_state/genesis.rs, execution_engine_testing/tests/src/test/regression/ee_1119.rs, execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs, node/src/types/json_compatibility/auction_state.rs, types/src/auction.rs, types/src/auction/bid/mod.rs, types/src/auction/bid/vesting.rs, types/src/auction/constants.rs, types/src/auction/detail.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1136 (subtask)
=> EE-1164: add vesting schedule for validator bids

resources/production/chainspec.toml, resources/production/config-example.toml, resources/production/validation.md5
Updated validators to 75.
Corrected seigniorage rate for exp 16.
=> Updating genesis and config for Delta prep.

.drone.yml, Makefile, node/Cargo.toml, node/src/components.rs, node/src/components/linear_chain_fast_sync.rs, node/src/components/linear_chain_sync.rs, node/src/components/storage.rs, node/src/effect.rs, node/src/reactor.rs, node/src/reactor/initializer.rs, node/src/reactor/joiner.rs, node/src/reactor/validator.rs, node/src/testing.rs, node/src/testing/multi_stage_test_reactor.rs, node/src/testing/multi_stage_test_reactor/test_chain.rs
Co-authored-by:    Marc Brinkmann <marc@casperlabs.io>
=> NDRS-739: Testing the joiner reactor

node/src/components/networking_metrics.rs, node/src/components/small_network.rs
Add a metric for the total count of connected peers.
=> NDRS-875 - track metric for connected peers

node/src/reactor.rs
Add metrics for allocated/total ram (as reported by jemalloc_ctl)
=> NDRS-874 - track allocated and total ram use metrics

utils/nctl/sh/node/svc_supervisord.sh
workaround for known issue in supervisorctl.
https://github.com/Supervisor/supervisor/issues/1223
=> force supervisorctl status to exit 0

node/src/components/small_network.rs
Add decay to blocklist in small_network, along with an exclusion for anything already in `known_addresses`.
=> NO_TICKET small_network blocklist tweak

node/src/components/small_network.rs
fix timestamp comparison in small_network blocklist check
=> NO TICKET fix timestamp comparison in small_network blocklist check

.drone.yml, ci/nightly-test.sh, utils/nctl/sh/scenarios/sync_test.sh
Initial commit of nightly nctl cronjob.
=> OP-1811: nctl nightly run

node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/highway_core/state/params.rs, node/src/components/consensus/highway_core/validators.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/tests.rs
https://casperlabs.atlassian.net/browse/HWY-256
If there's a chance that we're starting an era after it's already finished – send the request for validators' latest panoramas.
=> HWY-256: Request latest units on era start.

node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/round_success_meter.rs, node/src/components/consensus/protocols/highway/round_success_meter/config.rs
https://casperlabs.atlassian.net/browse/HWY-164
=> HWY-164: Pass the round success meter between eras

node/src/components/block_executor.rs
https://casperlabs.atlassian.net/browse/NDRS-900
=> NDRS-900: Populate block header with correct protocol version.

utils/nctl/sh/scenarios/sync_test.sh
Verify that after syncing, new node is keeping up with the protocol state.
=> NO-TICKET: Improve joining IT test.

.drone.yml, ci/upgrade_package_s3_storage.sh
Typos in paths that caused issues with the upload script.
=> OP-1820: Correcting bugs with paths for upgrade_build.

node/src/components/consensus/era_supervisor/era.rs
Add an env var for opting-in to detail mem metrics logging.
=> Add env var to enable detailed consensus metric logging

client/examples/ffi/tests/ffi_tests.c, client/lib/error.rs, client/lib/ffi.rs, client/src/account_address.rs, client/src/block/get.rs, client/src/block/transfers.rs, client/src/command.rs, client/src/common.rs, client/src/deploy/get.rs, client/src/deploy/list.rs, client/src/deploy/make.rs, client/src/deploy/put.rs, client/src/deploy/send.rs, client/src/deploy/sign.rs, client/src/deploy/transfer.rs, client/src/docs.rs, client/src/generate_completion.rs, client/src/get_auction_info.rs, client/src/get_balance.rs, client/src/get_era_info_by_switch_block.rs, client/src/get_state_hash.rs, client/src/keygen.rs, client/src/main.rs, client/src/query_state.rs
Ref: https://casperlabs.atlassian.net/browse/NDRS-501
This PR is a joint effort by @darthsiroftardis and myself to replace panics in the casper-client with errors where these are not indicative of a programming error.  The result is simpler, clearer reporting to the user in cases of operator error.
=> NDRS-501: avoid unnecessary panics in casper-client

execution_engine_testing/tests/src/test/system_contracts/upgrade.rs, node/src/components/consensus/tests/utils.rs, node/src/reactor/validator/tests.rs, node/src/testing/multi_stage_test_reactor/test_chain.rs, node/src/types/chainspec/accounts_config.rs, node/src/types/chainspec/network_config.rs, resources/local/accounts.toml, resources/production/accounts.toml, resources/production/validation.md5, resources/test/valid/0_9_0/accounts.toml
This PR adds delegators to accounts.toml
https://casperlabs.atlassian.net/browse/NDRS-711
=> NDRS-711: add delegators to accounts.toml

ci/nightly-test.sh, utils/nctl/sh/assets/upgrade.sh, utils/nctl/sh/node/upgrade.sh, utils/nctl/sh/scenarios/sync_test.sh, utils/nctl/sh/scenarios/sync_upgrade_test.sh
https://casperlabs.atlassian.net/browse/NDRS-880
https://casperlabs.atlassian.net/browse/NDRS-849
=> NDRS-880: Add an integration test for a node syncing with upgraded network.

.drone.yml
Turning this on prior to dev branch cut.
=> NO TICK: Adding in dev as branch target for CI.

types/src/gens.rs, types/src/key.rs
This PR is a followup to to #960.  It addresses a few missing bits, typos, etc..
=> NO-TICKET: clean up Key::Balance

execution_engine/src/core/engine_state/mod.rs
This PR changes the order of operations in `EngineState::commit_step` so that we distribute rewards before slashing.  
This precedes upcoming changes to how bids are persisted in the auction module.
=> EE-1178: distribute rewards then slash

execution_engine/src/shared/stored_value.rs, execution_engine/src/storage/trie/tests.rs, types/src/crypto/asymmetric_key/gens.rs, types/src/deploy_info.rs, types/src/gens.rs, types/src/key.rs, types/src/transfer.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1183
This PR
- extends property testing coverage of `Key`s and `StoredValue`s
=> EE-1183: Added Property Testing Around Keys and Stored Values

node/src/components/block_executor.rs, node/src/components/chainspec_loader.rs, node/src/components/consensus.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/era_supervisor/era.rs, node/src/components/consensus/era_supervisor/era_id.rs, node/src/components/linear_chain_sync.rs, node/src/components/linear_chain_sync/event.rs, node/src/components/linear_chain_sync/state.rs, node/src/effect.rs, node/src/reactor/joiner.rs
This backports commits from #955 that were created to address review comments (all commits apart from the last one) and adds a fix for a bug in era initialization.
=> NO-TICKET: Backport of PR for upgrades + a fix

.drone.yml
=> NO-TICK: drone s3 fix 

node/src/components/chainspec_loader.rs, node/src/data_migration.rs
Ref: https://casperlabs.atlassian.net/browse/NDRS-927
This PR backports a couple of fixes to the upgrade process applied to the `release-0.8.0` branch.
=> NDRS-927: backport fixes from release branch

node/src/reactor.rs, node/src/utils.rs, node/src/utils/rlimit.rs
This backports #1027 to the 0.7.7 release.
=> Backport ulimit increase

.gitignore, node/src/components.rs, node/src/components/block_executor/event.rs, node/src/components/block_executor/metrics.rs, node/src/components/consensus.rs, node/src/components/contract_runtime.rs, node/src/components/gossiper/tests.rs, node/src/components/linear_chain_fast_sync/traits.rs, node/src/components/linear_chain_sync/traits.rs, node/src/effect.rs, node/src/effect/announcements.rs, node/src/effect/requests.rs, node/src/reactor.rs, node/src/reactor/initializer.rs, node/src/reactor/initializer2.rs, node/src/reactor/joiner.rs, node/src/reactor/joiner/memory_metrics.rs, node/src/reactor/validator.rs, node/src/reactor/validator/memory_metrics.rs, node_macros/src/gen.rs
Reverts CasperLabs/casper-node#1013
=> Revert "NDRS-925 block executor optimization (1/2)"

node/src/components/gossiper.rs, node/src/components/gossiper/gossip_table.rs
Ported #1021 to `release-0.8.0`.
=> NO-TICKET: fix issue in gossip table

node/src/reactor.rs, node/src/utils.rs, node/src/utils/rlimit.rs
This ports #1027 to the 0.8.0 release.
=> Port ulimit increase to release-0.8.0

node/src/components/small_network.rs
Fixes a very rare race condition where the node did not know how to handle a connection being dropped in the middle of being established. This has, so far, only been triggered once in the recent months, regardless this is a fix for it.
=> NDRS-944: Prevent panics on failed connection

ci/nightly-test.sh, utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in, utils/nctl/sh/scenarios/itst13.sh
Implements itst13 from https://casperlabs.atlassian.net/wiki/spaces/OPS/pages/1133707277/Casper+Network+Infra+Test+Scenarios.
Also refactor nightly ci script to take a non-default chainspec.
=> OP-1857: NCTL - Validator Ejection Scenario

node/src/testing/multi_stage_test_reactor/test_chain.rs
=> NO-TICKET: disable test_joiner

utils/nctl/sh/scenarios/common/itst.sh, utils/nctl/sh/scenarios/itst01.sh, utils/nctl/sh/scenarios/itst02.sh, utils/nctl/sh/scenarios/itst11.sh, utils/nctl/sh/scenarios/itst13.sh
Moves common functions used in itst scenarios into a common sourceable script.
=> OP-1882: refactor itst scenarios

node/src/components/small_network.rs, node/src/components/small_network/config.rs, node/src/components/small_network/event.rs, node/src/components/small_network/message.rs, node/src/components/small_network/tests.rs, node/src/types/timestamp.rs, resources/local/config.toml, resources/production/config-example.toml
This builds upon #1095 and is a larger changeset, attempting to be even more robust and performant. It changes substantially more code, so more testing on a large scale would be required for this one to merge.
=> NO-TICKET/reconnect at all costs big (bigger changeset)

node/src/components/chainspec_loader.rs, node/src/types/block.rs
Ports commit from `release-0.9.1` branch to `release-0.9.2`.
=> [Delta] NDRS-963: chainspec loader now gets the protocol version from the highest

Cargo.lock, client/Cargo.toml, execution_engine/Cargo.toml, execution_engine/src/core/engine_state/executable_deploy_item.rs, execution_engine/src/core/engine_state/genesis.rs, node/Cargo.toml, node/src/components/consensus/highway_core/highway_testing.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/state/tests.rs, node/src/components/gossiper/tests.rs, node/src/reactor/validator/tests.rs, node/src/testing/multi_stage_test_reactor/test_chain.rs, node/src/types/block.rs, node/src/types/chainspec/core_config.rs, node/src/types/chainspec/deploy_config.rs, node/src/types/chainspec/global_state_update.rs, node/src/types/chainspec/highway_config.rs, node/src/types/chainspec/protocol_config.rs, node/src/types/deploy.rs, node/src/types/timestamp.rs, types/Cargo.toml, types/src/bytesrepr/bytes.rs, types/src/execution_result.rs, types/src/key.rs
REF: https://casperlabs.atlassian.net/browse/NDRS-983
CHANGELOG:
- Updated the `rand`, `rand_chacha` and `rand_pcg` crates within the project
- Refactored to account for updates in rand dependency
=> NDRS-983: Update rand, rand_chacha, rand_pcg

Cargo.lock, client/Cargo.toml, execution_engine/Cargo.toml, execution_engine/src/lib.rs, execution_engine_testing/cargo_casper/Cargo.toml, execution_engine_testing/cargo_casper/src/common.rs, execution_engine_testing/cargo_casper/src/tests_package.rs, execution_engine_testing/test_support/Cargo.toml, execution_engine_testing/test_support/src/lib.rs, node/Cargo.toml, node/src/lib.rs, node_macros/Cargo.toml, node_macros/src/lib.rs, smart_contracts/contract/Cargo.toml, smart_contracts/contract/src/lib.rs, smart_contracts/contract_as/package-lock.json, smart_contracts/contract_as/package.json, types/Cargo.toml, types/src/lib.rs
Set correct version for release candidate branch.
=> NO-TICK: Bump for 0.9.3

node/src/components/consensus/era_supervisor.rs
https://casperlabs.atlassian.net/browse/NDRS-1010
=> NDRS-1010: Don't create a new era when we should shutdown for an upgrade.

node/src/components/consensus/config.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/config.rs, node/src/components/consensus/protocols/highway/round_success_meter.rs, node/src/components/consensus/protocols/highway/round_success_meter/config.rs, node/src/components/consensus/protocols/highway/tests.rs, node/src/reactor/validator/tests.rs, node/src/testing/multi_stage_test_reactor/test_chain.rs, resources/local/config.toml, resources/production/config-example.toml, utils/nctl/sh/assets/setup.sh
https://casperlabs.atlassian.net/browse/HWY-264
=> HWY-264: Extract `RoundSuccessMeter` constants to configuration file.

node/src/app/cli.rs, node/src/app/main.rs
Ported #1125 to release branch.
=> NO-TICKET: use actual exit code returned by validator reactor

node/src/components/block_proposer.rs
=> NDRS-1029/restore block proposer state correctly backport

execution_engine/src/core/engine_state/genesis.rs, execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs
Ref: https://casperlabs.atlassian.net/browse/EE-1203
Backport of #1147 into a release branch
=> EE-1203: Validate delegated amount backport

node/src/components/block_proposer.rs
There is a leftover type mismatch from storing and loading state that was not caught due to missing type annotations. Unfortunately, the serialization format, in the configuration we use, was perfectly happy to restore a `T` as an `Option<T>` in some cases, masking these bug until actual data was filled in.
This patch adds type annotations and fixes the restoration.
=> NDRS-1029/Restore block proposer state correctly

node/src/components/block_executor.rs, node/src/components/chainspec_loader.rs, node/src/components/consensus.rs, node/src/components/consensus/consensus_protocol.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/synchronizer.rs, node/src/components/linear_chain.rs, node/src/components/linear_chain_sync.rs, node/src/effect.rs, node/src/effect/requests.rs, node/src/reactor/joiner.rs, node/src/reactor/joiner/memory_metrics.rs, node/src/reactor/validator.rs, node/src/testing/multi_stage_test_reactor.rs, node/src/types/block.rs, node/src/types/status_feed.rs
https://casperlabs.atlassian.net/browse/NDRS-902
=> NDRS-902: Remove the Era Supervisor from the Joiner reactor

.drone.yml
Switch NCTL test to alert in a new channel for more awareness.
=> OP-1904: Send nightly alerts to new channel

node/src/components/consensus/highway_core/finality_detector.rs, node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/protocols/highway.rs, node/src/components/consensus/protocols/highway/synchronizer.rs
We haven't seen any unexpected panics from these `unwraps`, but it's still better to avoid them where possible, or thoroughly document them.
https://casperlabs.atlassian.net/browse/HWY-270
=> HWY-270: Revisit some unwraps in the consensus component.

node/src/components/fetcher/tests.rs, node/src/components/gossiper/tests.rs, node/src/components/storage.rs, node/src/components/storage/tests.rs, node/src/reactor/initializer.rs, node/src/reactor/initializer2.rs
This is a port of #1166 to `dev`.
https://casperlabs.atlassian.net/browse/NDRS-1033
=> NDRS-1033: Only hard-reset blocks with old protocol versions

Cargo.lock, execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs, smart_contracts/contracts/client/activate-bid/Cargo.toml, smart_contracts/contracts/client/activate-bid/src/main.rs
This PR ports changes in https://github.com/CasperLabs/casper-node/pull/1169 to dev.
=> EE-1204: add activate-bid client contract

.drone.yml
Adds new prod apt repo on tag.
=> OP-1913: new apt repo

node/src/components/deploy_acceptor.rs, node/src/utils.rs
=> NO-TICKET: fix issue for deploy validation in deploy acceptor

utils/nctl/sh/utils/queries.sh
ports changes from closed PR: `https://github.com/CasperLabs/casper-node/pull/1159/commits/39b5eeaf3115e3a276f31d0387b56fb8280fa9e3`
=> NO-TICK: port nctl fixes

node/src/components/block_validator.rs
If a single block contains the same deploy twice, reject it.
https://casperlabs.atlassian.net/browse/NDRS-1053
=> NDRS-1053: Reject blocks containing duplicated deploys.

utils/nctl/sh/node/svc_supervisord.sh
Adding back a pipe to true that was removed in a recent pr.
=> OP-1940: add back removed true

execution_engine/src/core/engine_state/genesis.rs, execution_engine/src/core/engine_state/mod.rs, execution_engine/src/core/runtime_context/mod.rs, execution_engine_testing/test_support/src/internal/mod.rs, execution_engine_testing/test_support/src/internal/wasm_test_builder.rs, execution_engine_testing/tests/src/test/contract_api/mint_purse.rs, execution_engine_testing/tests/src/test/regression/ee_1045.rs, execution_engine_testing/tests/src/test/regression/ee_1103.rs, execution_engine_testing/tests/src/test/regression/ee_1119.rs, execution_engine_testing/tests/src/test/regression/ee_1120.rs, execution_engine_testing/tests/src/test/regression/ee_1152.rs, execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs, execution_engine_testing/tests/src/test/system_contracts/auction/distribute.rs, execution_engine_testing/tests/src/test/system_contracts/auction_bidding.rs, execution_engine_testing/tests/src/test/system_contracts/genesis.rs, execution_engine_testing/tests/src/test/system_contracts/handle_payment/finalize_payment.rs, types/src/system/auction/constants.rs, types/src/system/auction/detail.rs, types/src/system/auction/mod.rs, types/src/system/handle_payment/mod.rs, types/src/system/mint/mod.rs
This PR ports changes from #1221 to `dev`.
=> EE-1207: make definition of system account AccountHash consistent (dev)

types/src/gens.rs, types/src/key.rs
This PR fixes both bincode encoding and human readable JSON encoding for `Key`s used in the trie.
Further property tests are also introduced.
=> NO TICKET: Fix key deserialization

node/src/components/block_validator.rs, node/src/types/deploy.rs
backport of https://github.com/CasperLabs/casper-node/pull/1141 to release-0.9.4 branch
=> Backport NDRS-1013 validate block size to 0.9.5 branch

node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/validators.rs
https://casperlabs.atlassian.net/browse/NDRS-1077
=> NDRS-1077: Fix potential index out of bounds error. (1.0.0 backport)

node/src/components/consensus/highway_core/state.rs, node/src/components/consensus/highway_core/validators.rs
https://casperlabs.atlassian.net/browse/NDRS-1077
=> NDRS-1077: Fix potential index out of bounds error.

ci/nightly-test.sh
tracking here: https://casperlabs.atlassian.net/browse/OP-1951?atlOrigin=eyJpIjoiMTJmZjE2NzVlYTI5NGQ2MjlmOWJlM2NmZWJmNmE5MmMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
=> NO-TICK: disable faulty nctl test

resources/production/accounts.toml
From: 01f8684089490edcdb5feab0eee3615f26621dfd7f16419d06299466bab6fcb9f8
To: 019b51d1b374644628d7741f6c0980654fbdace31208268b9db736d2f5e42cc83a
=> DEV-43: key change request

ci/nightly-test.sh
moves era back 1 for upgrade
moves upgrade test to last.
=> OP-1961: nightly bug fix

node/src/components/event_stream_server.rs, node/src/components/event_stream_server/config.rs, resources/local/config.toml, resources/production/config-example.toml
This is a port of #1294 to release-1.2.0 with no changes to the original commit.
=> NDRS-1086: change SSE broadcast channel size to be a factor of event stream buffer size

execution_engine/src/core/engine_state/engine_config.rs, execution_engine/src/core/engine_state/mod.rs, execution_engine/src/core/engine_state/query.rs, execution_engine/src/core/tracking_copy/mod.rs, execution_engine/src/core/tracking_copy/tests.rs, execution_engine_testing/test_support/src/internal/wasm_test_builder.rs, execution_engine_testing/tests/benches/transfer_bench.rs, execution_engine_testing/tests/src/profiling/host_function_metrics.rs, execution_engine_testing/tests/src/profiling/simple_transfer.rs, execution_engine_testing/tests/src/profiling/state_initializer.rs, node/src/components/contract_runtime.rs, node/src/components/contract_runtime/config.rs, resources/local/config.toml, resources/production/config-example.toml
Ref: https://casperlabs.atlassian.net/browse/EE-1076
Original PR #1213 
This PR applies a recursive query limit fix on top of 1.0.2
=> EE-1076: Recursive query backport

ci/nightly-test.sh, utils/nctl/sh/scenarios/common/itst.sh, utils/nctl/sh/scenarios/itst06.sh
Scenario mimics a node that fails as transfers are coming in mid-stream. Verifies that transfers that are sent get included in blocks.
https://casperlabs.atlassian.net/browse/OP-1838
=> OP-1838: itst06 scenario

utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in, utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in, utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in
Adds delete to the nctl scenario configs.
=> OP-1988: add delete to test configs

execution_engine/src/core/engine_state/genesis.rs, execution_engine/src/core/runtime/auction_internal.rs, execution_engine/src/core/runtime/mod.rs, execution_engine/src/core/runtime_context/mod.rs, execution_engine/src/core/tracking_copy/byte_size.rs, execution_engine/src/core/tracking_copy/mod.rs, execution_engine/src/shared/stored_value.rs, execution_engine/src/shared/transform.rs, execution_engine_testing/test_support/src/internal/wasm_test_builder.rs, execution_engine_testing/tests/src/test/step.rs, execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs, node/src/types/json_compatibility/stored_value.rs, types/src/era_id.rs, types/src/execution_result.rs, types/src/gens.rs, types/src/key.rs, types/src/system/auction/constants.rs, types/src/system/auction/detail.rs, types/src/system/auction/mod.rs, types/src/system/auction/providers.rs, types/src/system/auction/seigniorage_recipient.rs
Refs:
https://github.com/CasperLabs/casper-node/pull/1097
https://github.com/CasperLabs/casper-node/pull/1089
=> NO-TICKET: revert EE-{1195,1196}

execution_engine/src/core/engine_state/genesis.rs, execution_engine/src/core/runtime/mod.rs, execution_engine/src/core/runtime/standard_payment_internal.rs, execution_engine/src/shared/system_config/handle_payment_costs.rs, resources/local/chainspec.toml.in, resources/production/chainspec.toml, resources/test/valid/0_9_0/chainspec.toml, resources/test/valid/0_9_0_unordered/chainspec.toml, resources/test/valid/1_0_0/chainspec.toml, smart_contracts/contracts/client/named-purse-payment/src/main.rs, smart_contracts/contracts/test/ee-549-regression/src/main.rs, smart_contracts/contracts/test/ee-601-regression/src/main.rs, smart_contracts/contracts/test/finalize-payment/src/main.rs, smart_contracts/contracts/test/get-payment-purse/src/main.rs, smart_contracts/contracts/test/get-phase-payment/src/main.rs, smart_contracts/contracts/test/refund-purse/src/main.rs, smart_contracts/contracts/test/test-payment-stored/src/main.rs, types/src/system/handle_payment/constants.rs, types/src/system/handle_payment/mod.rs, utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in, utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in, utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in
Ref:
https://github.com/CasperLabs/casper-node/pull/1286
=> NO-TICKET: revert EE-1223

.drone.yml
See title
https://casperlabs.atlassian.net/browse/OP-1921
=> OP-1921: removing bintray from ci

node/src/components/rest_server.rs, node/src/components/rest_server/filters.rs, node/src/components/rest_server/http_server.rs, node/src/components/rpc_server/rpcs/docs.rs, node/src/effect/requests.rs
REF: https://casperlabs.atlassian.net/browse/NDRS-1194
CHANGELOG:
- Added an `/rpc-schema` REST endpoint which gives a OpenRPC compatible schema
=> NDRS-1194: OpenRPC schema REST endpoint

.drone.yml
Enables CI on all branches prefixed with `feat-`.
=> NDRS-1177: enable ci on prefixed feat- branches

resources/production/chainspec.toml
`Era: 347  2021-04-29 13:55:50+00:00 Z    2021-04-29 09:55:50-04:00 E    2021-04-29 06:55:50-07:00 W`
=> OP-2005: Upgrade stage 1.1.0 activation point

utils/nctl/sh/scenarios/bond_its.sh, utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in, utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in, utils/nctl/sh/scenarios/common/itst.sh, utils/nctl/sh/scenarios/itst13.sh
Adds re-join to itst13 eviction scenario.
Syncs chainspecs with new value from local/reseorces.
Moves function to common for reuse in scenarios.
=> OP-2022: Extend nctl eviction scenario

node/src/components/linear_chain_sync/operations.rs, node/src/testing/multi_stage_test_reactor/test_chain.rs
When joining right after genesis, fast sync will now use the genesis validators for finality signature verification.
=> NDRS-1227: Use Genesis Validators When Fast Sync Joins Around Genesis

ci/nightly-test.sh, utils/nctl/sh/scenarios/common/itst.sh, utils/nctl/sh/scenarios/itst07.sh
Same test as itst06 just utilizing wasm instead of native transfer.
=> OP-1839: initial commit itst07

utils/nctl/sh/contracts-transfers/do_dispatch_native.sh
adds `transfer-id ` to native transfers for nctl.
=> OP-2048: add transfer id for nctl

node/src/components/linear_chain_sync.rs, node/src/components/linear_chain_sync/state.rs, node/src/types/chainspec/highway_config.rs
=> Remove the acceptable_drift; stop syncing when we are in the current era

node/src/components/block_proposer.rs, node/src/components/block_proposer/deploy_sets.rs, node/src/components/block_proposer/event.rs, node/src/components/block_proposer/tests.rs, node/src/components/block_validator.rs, node/src/components/consensus/era_supervisor.rs, node/src/components/contract_runtime.rs, node/src/reactor/validator.rs, node/src/types.rs, node/src/types/appendable_block.rs, node/src/types/block.rs, node/src/types/deploy.rs
=> Separate transfers and other deploys in the block proposer

node/src/effect.rs
=> Enable reading validators for future eras in get_era_validators

node/src/components/consensus/highway_core.rs, node/src/components/consensus/highway_core/highway.rs, node/src/components/consensus/highway_core/synchronizer.rs, node/src/components/consensus/highway_core/synchronizer/tests.rs, node/src/components/consensus/protocols/highway.rs
=> Move synchronizer into highway_core. (#1476)

Cargo.lock, execution_engine/src/core/engine_state/genesis.rs, execution_engine/src/core/execution/error.rs, execution_engine/src/core/runtime/mod.rs, execution_engine_testing/tests/Cargo.toml, execution_engine_testing/tests/src/test/regression/gh_1470.rs, execution_engine_testing/tests/src/test/regression/mod.rs, smart_contracts/contracts/test/do-nothing-stored-upgrader/src/main.rs, smart_contracts/contracts/test/do-nothing-stored/src/main.rs, smart_contracts/contracts/test/gh-1470-regression-call/Cargo.toml, smart_contracts/contracts/test/gh-1470-regression-call/src/bin/main.rs, smart_contracts/contracts/test/gh-1470-regression-call/src/lib.rs, smart_contracts/contracts/test/gh-1470-regression/Cargo.toml, smart_contracts/contracts/test/gh-1470-regression/src/bin/main.rs, smart_contracts/contracts/test/gh-1470-regression/src/lib.rs, smart_contracts/contracts/test/transfer-purse-to-accounts-stored/src/main.rs, smart_contracts/contracts_as/client/undelegate/assembly/index.ts, smart_contracts/contracts_as/test/do-nothing-stored-upgrader/assembly/index.ts, smart_contracts/contracts_as/test/do-nothing-stored/assembly/index.ts, types/src/contracts.rs, types/src/runtime_args.rs
This PR incorrect group restriction and argument types validation to `call_contract` API.
Fixes #1470
=> Group restriction fix

node/src/components/consensus/protocols/highway.rs
This makes it more visible in the logs when a node periodically checks whether its protocol state is stalled.
#1498
=> Log more progress/standstill alert information.

utils/nctl/sh/utils/constants.sh
See https://github.com/casper-network/casper-node/issues/1478#issuecomment-858592003 for details.
=> Change the base ports for all services of nctl nodes

node/src/components/event_stream_server/sse_server.rs, node/src/components/event_stream_server/tests.rs
This PR changes how the SSE server tests terminate to avoid spurious failures.
Previously they used the arrival of the first keepalive as the signal that the server had finished sending all events in the tests.  However, even with a relatively large margin of error, this was insufficient to guarantee that a server in a running test wouldn't be so slow that it would never emit a keepalive before all events had been emitted.
The stopping criterion for a test client has been changed to a specific event ID.  The client consumes events until the expected ID is received, or panics if a keepalive is received.  As the keepalive interval has been reverted from 100 milliseconds for tests to the default 15 seconds, there is no reasonable way in which a client should receive a keepalive mid-test now. …
=> Make SSE tests not depend upon server emitting keepalives to terminate

smart_contracts/contract_as/package-lock.json
Implements current open dependabot PRs against dev.
- https://github.com/casper-network/casper-node/pull/1586
- https://github.com/casper-network/casper-node/pull/1585
- https://github.com/casper-network/casper-node/pull/1559
- https://github.com/casper-network/casper-node/pull/1430
- https://github.com/casper-network/casper-node/pull/1429
- https://github.com/casper-network/casper-node/pull/1412
=> Dependabot rebase fixes

node/src/components/gossiper/gossip_table.rs
I've added some tests and described behavior for `Timeouts`.
closes casper-network/casper-node#1510
=> 1510 - Test Timeouts

.drone.yml, ci/change_default_branch.py
Changes default branch on tag to matching release branch.
Updates branch protection on the tagged release branch.
=> OP-2097: default branch switching

utils/nctl/sh/scenarios/configs/itst13.config.toml
syncs `enable_mem_deduplication` and `mem_pool_prune_interval` to `itst13.config.toml`
=> NCTL: sync itst13.config.toml with local

utils/nctl/sh/assets/compile_client.sh
Adds `make setup-rs` to nctl client compile wrapper.
=> NCTL: run setup-rs

node/CHANGELOG.md
Add a changelog entry for https://github.com/casper-network/casper-node/pull/1681.
=> Add changelog entry for shutdown_on_standstill option.

ci/nctl_upgrade.sh, utils/nctl/activate, utils/nctl/sh/assets/setup_from_stage.sh, utils/nctl/sh/scenarios-upgrades/upgrade_scenario_03.sh, utils/nctl/sh/scenarios/accounts_toml/upgrade_scenario_3.accounts.toml, utils/nctl/sh/scenarios/chainspecs/upgrade_scenario_3.chainspec.toml.in, utils/nctl/sh/utils/blocking.sh
Changes: 
- `nctl-exec-upgrade-scenario-3` 
- Added to `activate`
- Added to `staging|trying` bors
- `upgrade_scenario_3.accounts.toml` to `$NCTL/sh/scenarios/accounts_toml` for use in scenario
- `upgrade_scenario_3.chainspec.toml.in ` to `$NCTL/sh/scenarios/chainspecs` for use in scenario
- `setup_from_stage.sh` modified for custom chainspecs
- `await_n_eras` modified for variable sleep interval
Issue: https://app.zenhub.com/workspaces/cn-sre-60d363546afb85000e491ff6/issues/casper-network/sre/9
=> NCTL: nctl-exec-upgrade-scenario-3

execution_engine_testing/test_support/src/test_context.rs, execution_engine_testing/tests/src/test/contract_api/dictionary.rs
Follow up for #1678 to support TestContext's ability to query dictionaries after late changes to the PR.
=> GH-1674: Update TestContext's ability to query dictionaries

execution_engine_testing/test_support/src/test_context.rs, execution_engine_testing/tests/src/test/contract_api/dictionary.rs
This PR is a port of #1714 onto 1.3.0 release branch.
This PR affects only `test_support` crate
Follow up for #1678 to support TestContext's ability to query dictionaries after late changes to the PR.
=> GH-1674: Update TestContext's ability to query dictionaries for 1.3.0
